### ISSUE TITLE
Depth of values I can read?

### ISSUE THREAD

**Issue by xnih** [KimiNewt/pyshark#103]
Doing something like:

import pyshark

cap = pyshark.FileCapture('somefile.pcap', display_filter='smb.cmd == 0x72')

for pkt in cap:
  print pkt.smb.flags
  print pkt.smb.flags.response

For 2 shark these are valid:
$ tshark -Y 'smb.cmd == 0x72' -T fields -e smb.flags.response -r ssomefile.pcap
0
1

There were 2 smb.cmd == 0x72 packets in there, but with pyshark I get:
$ python smb2.py
Traceback (most recent call last):
  File "smb2.py", line 7, in <module>
    pkt.smb.flags.response
  File "/usr/local/lib/python2.7/dist-packages/pyshark/packet/layer.py", line 115, in __getattr__
    return getattr(self.main_field, item)
AttributeError: 'LayerField' object has no attribute 'response'

From my testing with smb stuff it seems I can go 2 layers deep and that is it.
IE:  pkt.smb.flags, pkt.smb.server_timezone

But going a 3rd layer deep it fails:
pkt.smb.flags.response, pkt.smb.system.time

New to python, so not sure if this is just an issue of taking pkt.smb and shoving it into a "layer" and then peeling back a piece or what is going on here.

**Comment by xnih** [comment]
Reading through closed issues I found something that appears to work, though as they noted, it doesn't seem like it should be required:

  data = getattr(pkt.smb, 'smb.flags.response')
  print data

So I've got a work around, just curious if this is a limitation of the way things are stored or what?  But lets me move forward with the wrapper!

**Comment by KimiNewt** [comment]
You can also access it via pkt.smb.flags_response
I added the way you expected in the branch https://github.com/KimiNewt/pyshark/tree/inner-fields 
After some testing it can be merged into the master branch.
