### ISSUE TITLE
Can't capture icmp reply

### ISSUE THREAD

**Issue by GinesGarcia** [KimiNewt/pyshark#104]
Hi,
i'm trying to capture icmp request and reply but only request is captured by sniff_continuously method. My code:
for packet in capture.sniff_continuously(packet_count=1):
                if "ICMP" in packet and "reply" in packet:
                        print packet.icmp

With tcmdum or tshark i'm getting request and reply packages.

thanks.

**Comment by KimiNewt** [comment]
Try printing all incoming packets / all ICMP packets. I don't think "reply" in packet will work. The "in" syntax only works to check if protocols are in the packet. You should probably check one of the fields on the ICMP packet instead.
