### ISSUE TITLE
tcp_segments field for http packets is cut short

### ISSUE THREAD

**Issue by wouche** [KimiNewt/pyshark#109]
I have selected an HTTP-packet that is created by reassembly of TCP packets. This HTTP-packet has a 'tcp_segments' field in its data layer, that contains the numbers of the TCP packets that are used to reassemble this HTTP-request. But this value seems to be cut short.

An example for the 'tcp_segments' field value for an HTTP-packet is: 121 Reassembled TCP Segments (173003 bytes): #95(216), #96(1448), #97(1448), #99(1448), #100(1448), #101(1448), #103(1448), #104(1448), #105(1448), #107(1448), #108(1448), #109(1448), #111(1448), #112(1448), #114(1448), #115(1448), #116(14

This happens for every HTTP-packet with a large amount of TCP-segments. Is this a bug or am I doing something wrong?

**Comment by KimiNewt** [comment]
This can be attained very awkwardly, since Wireshark counts it as a separate layer. So you can get it via `packet.data.tcp_segments` and the segments themselves via `packet.data.tcp_segment.all_fields`
Quite awful, need to think of a better way to do that.

**Comment by zhangcongjiang** [comment]
so,how can i use remote capture on linux?
