### ISSUE TITLE
pyshark perfomance issue

### ISSUE THREAD

**Issue by sanyaden** [KimiNewt/pyshark#112]
I've faced with performance issue of pyshark.

I've used such script for getting data from eth0 interface:
import pyshark
from datetime import datetime

def checkpkt(pak):
    try:
         diff= datetime.today()-pak.sniff_time
         print "now: %s time: %s diff: %s" % (str(datetime.today()), str(pak.sniff_time), str(diff))
         if (pak.ranap.procedureCode=="19"):
            print "time: %s now: %s" % (str(pak.sniff_time), datetime.today())
    except (AttributeError, TypeError):
        pass

capture = pyshark.LiveCapture(interface='eth0',display_filter='bssap')
capture.sniff(timeout=5)

for pkt in capture.sniff_continuously():
    checkpkt(pkt)

And got such delay in data processing by pyshark:
now: 2016-01-06 14:46:08.859436 time: 2016-01-06 14:46:08.313823 diff: 0:00:00.545304
now: 2016-01-06 14:46:08.893584 time: 2016-01-06 14:46:08.314515 diff: 0:00:00.578828
now: 2016-01-06 14:46:08.917056 time: 2016-01-06 14:46:08.314624 diff: 0:00:00.602166
now: 2016-01-06 14:46:08.996593 time: 2016-01-06 14:46:08.314627 diff: 0:00:00.681760
now: 2016-01-06 14:46:09.022388 time: 2016-01-06 14:46:08.314877 diff: 0:00:00.707300
now: 2016-01-06 14:46:09.051132 time: 2016-01-06 14:46:08.314882 diff: 0:00:00.736043
now: 2016-01-06 14:46:09.067837 time: 2016-01-06 14:46:08.314976 diff: 0:00:00.752672
now: 2016-01-06 14:46:09.113264 time: 2016-01-06 14:46:08.315014 diff: 0:00:00.798021
now: 2016-01-06 14:46:09.181649 time: 2016-01-06 14:46:08.315123 diff: 0:00:00.866312
now: 2016-01-06 14:46:09.219635 time: 2016-01-06 14:46:08.315125 diff: 0:00:00.904281
now: 2016-01-06 14:46:09.326851 time: 2016-01-06 14:46:08.315220 diff: 0:00:01.011424
now: 2016-01-06 14:46:09.342916 time: 2016-01-06 14:46:08.315224 diff: 0:00:01.027504
now: 2016-01-06 14:46:09.361200 time: 2016-01-06 14:46:08.315264 diff: 0:00:01.045727
now: 2016-01-06 14:46:09.431664 time: 2016-01-06 14:46:08.315363 diff: 0:00:01.116096
now: 2016-01-06 14:46:09.455594 time: 2016-01-06 14:46:08.315415 diff: 0:00:01.139972
now: 2016-01-06 14:46:09.472916 time: 2016-01-06 14:46:08.315418 diff: 0:00:01.157286
now: 2016-01-06 14:46:09.540057 time: 2016-01-06 14:46:08.315470 diff: 0:00:01.224373
now: 2016-01-06 14:46:09.601578 time: 2016-01-06 14:46:08.315514 diff: 0:00:01.285858
now: 2016-01-06 14:46:09.628089 time: 2016-01-06 14:46:08.315569 diff: 0:00:01.312308
now: 2016-01-06 14:46:09.689064 time: 2016-01-06 14:46:08.315571 diff: 0:00:01.373298
now: 2016-01-06 14:46:09.735030 time: 2016-01-06 14:46:08.315663 diff: 0:00:01.419175
now: 2016-01-06 14:46:09.757128 time: 2016-01-06 14:46:08.315669 diff: 0:00:01.441267
now: 2016-01-06 14:46:09.789630 time: 2016-01-06 14:46:08.315673 diff: 0:00:01.473761
now: 2016-01-06 14:46:09.813865 time: 2016-01-06 14:46:08.315677 diff: 0:00:01.497972
now: 2016-01-06 14:46:09.837503 time: 2016-01-06 14:46:08.315679 diff: 0:00:01.521635
now: 2016-01-06 14:46:09.882390 time: 2016-01-06 14:46:08.316319 diff: 0:00:01.565878
now: 2016-01-06 14:46:09.898821 time: 2016-01-06 14:46:08.316326 diff: 0:00:01.582297
now: 2016-01-06 14:46:09.916304 time: 2016-01-06 14:46:08.316461 diff: 0:00:01.599654
now: 2016-01-06 14:46:09.950841 time: 2016-01-06 14:46:08.316466 diff: 0:00:01.634183
now: 2016-01-06 14:46:10.007635 time: 2016-01-06 14:46:08.316467 diff: 0:00:01.690951
now: 2016-01-06 14:46:10.053203 time: 2016-01-06 14:46:08.316512 diff: 0:00:01.736476
now: 2016-01-06 14:46:10.118052 time: 2016-01-06 14:46:08.316520 diff: 0:00:01.801308
now: 2016-01-06 14:46:10.146571 time: 2016-01-06 14:46:08.316561 diff: 0:00:01.829798
now: 2016-01-06 14:46:10.162774 time: 2016-01-06 14:46:08.316618 diff: 0:00:01.845967
now: 2016-01-06 14:46:10.188680 time: 2016-01-06 14:46:08.316711 diff: 0:00:01.871761
now: 2016-01-06 14:46:10.206430 time: 2016-01-06 14:46:08.316912 diff: 0:00:01.889329
now: 2016-01-06 14:46:10.221713 time: 2016-01-06 14:46:08.316917 diff: 0:00:01.904583
now: 2016-01-06 14:46:10.245260 time: 2016-01-06 14:46:08.316921 diff: 0:00:01.928127
now: 2016-01-06 14:46:10.275347 time: 2016-01-06 14:46:08.316922 diff: 0:00:01.958217
now: 2016-01-06 14:46:10.291911 time: 2016-01-06 14:46:08.317169 diff: 0:00:01.974557
now: 2016-01-06 14:46:10.428607 time: 2016-01-06 14:46:08.317267 diff: 0:00:02.111078

Do You know what is the reason for such processing delay? Is it possible to fix it?

**Comment by KimiNewt** [comment]
It's hard to tell what the cause is. It could be tshark-processing or more likely the XML parsing, you might want to check IO/CPU usage of tshark/python. Performance is something I'd like to improve in the future but I can't currently do anything about it.
