### ISSUE TITLE
How can I get details about SIP message SDP information using pyshark

### ISSUE THREAD

**Issue by vikramg85** [KimiNewt/pyshark#114]
I can read SIP message headers, however if SIP message has SDP message body in it. How to read it. Also where I can get complete documentation about pyshark?

**Comment by ratman** [comment]
Yeah thats a very good question actually.

**Comment by lowdef** [comment]
Looks like the sdp fields are decoded by the sip dissector:
>>> field_list=packets[0]['sip']._all_fields
>>> key_list=set(field_list)
>>> key_list
set(['sip.pai.addr', 'sip.from.tag', 'sip.Route.user', 'sip.Max-Forwards', 'sip.from.user', 'sip.Route', 'sip.tag', 'sdp.bandwidth', 'sip.to.host', 'sip.contact.uri', 'sip.r-uri.user', 'sdp.owner.sessionid', 'sip.pai.host', 'sip.CSeq', 'sip.to.addr', 'sip.Via', 'sip.Contact', 'sdp.media.proto', 'sip.Route.param', 'sdp.connection_info.address_type', 'sip.CSeq.method', 'sip.Min-SE', 'sdp.session_name', 'sip.Request-Line', 'sip.to.user', 'sdp.media', 'sip.CSeq.seq', 'sip.P-Charging-Function-Addresses', 'sip.Accept', 'sip.Via.sent-by.port', 'sip.from.addr', 'sip.to.port', 'sdp.owner.username', 'sip.resend', 'sdp.version', 'sdp.data', 'sip.Session-Expires', 'sip.msg_body', 'sdp.connection_info.network_type', 'sip.from.host', 'sip.contact.user', 'sdp.time', 'sdp.connection_info', 'sip.Allow', 'sip.contact.param', 'sdp.media.media', 'sip.r-uri.host', 'sip.P-Asserted-Identity', 'sip.From', 'sdp.time.stop', 'sip.from.port', 'sdp.media_attribute.value', 'sip.Via.branch', 'sip.msg_hdr', 'sdp.media_attribute.field', 'sdp.owner.address', 'sip.Route.uri', 'sdp.time.start', 'sip.P-Visited-Network-ID', 'sip.Accept-Contact', 'sip.contact.port', 'sip.P-Charging-Vector', 'sip.Content-Length', 'sip.P-Early-Media', 'sip.Supported', 'sdp.media.format', 'sip.Via.sent-by.address', 'sdp.owner.network_type', 'sdp.fmtp.parameter', 'sdp.owner.version', 'sip.to.param', 'sip.Call-ID', 'sdp.owner.address_type', 'sdp.bandwidth.modifier', 'sdp.media.port_string', 'sip.P-Access-Network-Info', 'sdp.connection_info.address', 'sip.r-uri', 'sip.User-Agent', 'sip.Route.port', 'sdp.bandwidth.value', 'sip.P-Served-User', 'sdp.mime.type', 'sip.Content-Type', 'sdp.media_attr', 'sdp.owner', 'sdp.sample_rate', 'sip.Method', 'sip.Route.host', 'sip.pai.user', 'sip.contact.host', 'sip.To', 'sip.Via.transport', 'sdp.media.port'])

**Comment by ratman** [comment]
If I want to reconstruct that sdp as printable text, that will be a BDSM session... I am unfortunately no tshark expert, but a sip.sdp field would be nice or even a sip.payloads, since there are a lot of possible Content-Types in a SIP message.

**Comment by KimiNewt** [comment]
Like @lowdef said, the individual fields can be accessed via pkt.sip.Route_port, etc. (in the new subfields branch you can access it via pkt.sip.Route.port as well).
I'm not too familiar with the SIP protocol, but if the field that you want is not built-in in Wireshark, pyshark cannot display it and you have to make a wrapper around it to reconstruct what you want.

If you create a specific wrapper for SIP (i.e. inherit from `Layer` and create a `SIPLayer`) and open a PR I'll add it.

**Comment by lowdef** [comment]
@ratman 

Assume your sip message is in frame 5, you can find this out by
looking at it in wireshark.

Then to investigate how the sip dissector dissassembles the sip
message, you can have a look at the xml representation:
```bash
tshark -r 'foo.pcap' -Y '(frame.number==5)' -T pdml
```

This way you can find that:
```python
pkt.sip.msg_hdr
```
or 

```python
field_list=packets[0]['sip']._all_fields
field_list['sip.msg_hdr']
```

should return a text representation of the complete message including
the sdp body: it should not be to difficult to extract the sdp body
from that.

Alternatively you can use tshark directly to retrieve this part:
```bash
tshark -r 'foo.pcap' -Y '(frame.number==5)' -T fields -e sip.msg_hdr
```

**Comment by ratman** [comment]
Thanks! I came to the same idea at the end, it's probably the simplest way.
