### ISSUE TITLE
Trollius vs Python 3.3+ asyncio

### ISSUE THREAD

**Issue by ganguin** [KimiNewt/pyshark#117]
pyshark is using trollius as asyncio implementation which is not directly compatible with python 3.3+ asyncio.

Trollius describes the differences between them and how to write code working on both:
http://trollius.readthedocs.org/asyncio.html

Can you please implement trollius's recommendation to be compatible with both implementations. In particular such that capture.packets_from_tshark() can be used with a python3.3+ asyncio eventloop.

**Comment by KimiNewt** [comment]
I'm aware of the difference, unfortunately there's no quick way to have it use one or the other according to what's available, unless you use only callbacks (no coroutines) as mentioned in the docs.

However we can probably do a custom "compatibility" layer. I'll give it some thought and might implement it when I have time.

**Comment by anthraxx** [comment]
trollius is officially end of life and should be replaced with some other asyncio library:
http://trollius.readthedocs.io/deprecated.html#deprecated

**Comment by KimiNewt** [comment]
Like I outlined in the previous comment, this is a bit of an issue as I don't want to drop python2 support. Other async packages I've looked at at the time did not have good Windows support which is why I elected to use trollius/asyncio.

I'll survey some packages again and see if anything's changed.

**Comment by anthraxx** [comment]
@KimiNewt yeah true, i get your point just saying trollius its a unmaintained dead-end and should be reconsidered :yum:

**Comment by cristianorolim** [comment]
Hi. I understand the reasons to keep supporting python 2. But is still still necessary to support version 2.6? The same for 3.3 and 3.4. Dropping these old version would simplify a little the support chain...

**Comment by KimiNewt** [comment]
I was specifically asked to keep Python 2.6 support, though I guess it's pointless at this point.
As for 3.3/3.4-- if we want to keep supporting Python 2 there's nothing to be done by 'dropping support' for them. 

I'm considering to just make a fork for a python2 version and have this only be python3.

**Comment by anthraxx** [comment]
for whom are you supporting 2.6 in 2016? :D debian stable ships 2.7. IMO it would be a waste of resources to fork of a python2 variant just because of 2.6 and from a distro packaging and user view its always nicer to have py2+py3 from within the same source. fells like supporting windows XP :yum:

**Comment by KimiNewt** [comment]
2.6 support is an old thing and I don't mind removing it (the difference is only around three lines anyway). Forking would be so we could use asyncio and even further the new syntax in Python 3.5 (trollius makes the code looks fairly awful, it's unsupported and we might get a performance boost). 

When I have time I'll convert everything to 3.5 and I'll see exactly how much we gain from it.

**Comment by cristianorolim** [comment]
I've cited theses version because they are in the Travis CI automatic building system.

**Comment by KimiNewt** [comment]
Only using asyncio now
