### ISSUE TITLE
no interface to add override parameters (can't easily apply esp.enable_null_encryption_decode_heuristic: TRUE)

### ISSUE THREAD

**Issue by monkut** [KimiNewt/pyshark#118]
I'm trying to use pyshark with some pcap files here null encryption key is used.
In wireshark, I can set the esp.enable_null_encryption_decode_heuristic option to TRUE and am able to see the RTP packets.

However, on linux (ubuntu), I'm have trouble finding where the wireshark.conf is located (not in ~/.wireshark/preferences...), and cannot easily apply this parameter.  

tshark allows parameter override via the, '-o' option, and this seems to be used internally to pyshark in Capture.get_parameters(), but there is no API available to send additional parameters to override.

A new option avilable in Capture, like, 'override_params={PARAM_NAME: PARAM_VALUE, ...} would be nice.

**Comment by KimiNewt** [comment]
That sounds good. If you make a PR, I'll approve it. Otherwise you'll have to wait until at least mid-Feb when I'll be less busy.

**Comment by monkut** [comment]
covered by pr121. 

https://github.com/KimiNewt/pyshark/pull/121
