### ISSUE TITLE
How to decrypt ZigBee packets?

### ISSUE THREAD

**Issue by xiaoyi10479** [KimiNewt/pyshark#122]
For now the library supports WLAN decrytion. But what parameters should I specify if ZigBee decrytion needed?

**Comment by Armonkee** [comment]
Parsing a packet for its ZigBee contents can be done for example like this:
                if 'zbee_nwk' in dir(packet):
                    zb=packet['ZBEE_NWK']
                    print int(zb.seqno),"0x%x->0x%x"%(int(zb.src),int(zb.dst)),int(zb.cmd_id)

**Comment by KimiNewt** [comment]
I'm not familiar with the decryption. Is this something that's possible to do on Wireshark?

**Comment by Smanar** [comment]
I m trying same.
This code is working

```
if 'zbee_nwk' in dir(packet):
    print ('\n *** NWK ***')
    zb=packet['zbee_nwk']
    print('Source: '+ zb.src + '  Destination: ' + zb.dst )
if 'zbee_zdp' in dir(packet):
    zb=packet['zbee_zdp']
    print ('\n *** ZDP ***')
    print(zb)
    #print (zb.seqno)
if 'zbee_aps' in dir(packet):
    zb=packet['zbee_aps']
    print ('\n *** APS ***')
    print(zb)
    print(dir(zb))

print('---')    
print (packet.layers)
```

![attribute example](https://user-images.githubusercontent.com/20152487/68709500-1859e800-0596-11ea-8d8c-502b8642fd0e.jpg)


But How acess to Zigbee Cluster library frame ?
