### ISSUE TITLE
Problems with Wireshark 2.0.1

### ISSUE THREAD

**Issue by dunkhong** [KimiNewt/pyshark#124]
Hello,

I am using pyshark 0.3.6 over python 2.7 and wireshark 2.0.1, 64bit over Gentoo Linux.
But, when i import pyshark in pythoin script, I got error message as following:
    - ImportError: lib{wireshark,wiretap,wsutil}.so.2: cannot open shared object file: No such file or directory

To solve problems, I make the symbolic link as following:
     - /usr/lib/libwireshark.so.2 -> libwireshark.so.6.0.1

But I also got other error message as follow:
     - ImportError: /usr/lib64/python2.7/pyshark.so: undefined symbol: dfilter_error_msg

How can I solve it?? 

Thanks in Advanced,

Choi,

**Comment by KimiNewt** [comment]
This seems like  a tshark problem rather than a pyshark one. Can you run tshark and get xml output? (Try `tshark -T pdml`)

**Comment by sikam** [comment]
Same problem here: 
```
capture1 = pyshark.FileCapture(file1_path_name, tshark_path=PathToTshark)
print(capture1[0])
capture1.close()

capture2 = pyshark.FileCapture(file2_path_name, tshark_path=PathToTshark)
print(capture2[0])
capture2.close()
```
Encountered this issue with pyshark 0.3.7.9 on Python 3.6.2 on Win7 64bit
Are there any plans on fixing this issue?
