### ISSUE TITLE
How can i get captured packet file?

### ISSUE THREAD

**Issue by dslab0915** [KimiNewt/pyshark#126]
import pyshark

def NetCap():
    livecapture = pyshark.LiveCapture(interface="eth0")
    livecapture.sniff(timeout=100)

if __name__ == "__main__":
    NetCap()

this is my code.

I want to live capture the packets using pyshark module.

but, I don't know this captured filed(.cap or .pcap) where is it? 

Can I configure the save path?

please help me...

**Comment by GinesGarcia** [comment]
Hi,
read about that at https://github.com/KimiNewt/pyshark#reading-from-a-live-interface, you have to specify "param output_file: Additionally save captured packets to this file."

**Comment by KimiNewt** [comment]
What @GinesGarcia said. If you use `LiveCapture(output_file="/path/to/cap")` it'll save it there.
