### ISSUE TITLE
Error when running pip install pyshark

### ISSUE THREAD

**Issue by chadianscot** [KimiNewt/pyshark#127]
I get the following install when trying to install pyshark.

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-BBO8WW/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sdIPhL-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-BBO8WW/lxml
Storing debug log for failure in /root/.pip/pip.log

Any idea why?

**Comment by KimiNewt** [comment]
Hard to tell exactly why, but it it looks to be a problem with the lxml install. Please try to install lxml separately (via pip or from a tar from their website).

**Comment by chadianscot** [comment]
I get this error when trying to install lxml via pip:

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Gzi_pl/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1DPWgY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-Gzi_pl/lxml
Storing debug log for failure in /root/.pip/pip.log

**Comment by chadianscot** [comment]
Thanks, managed to install lxml via apt-get install python-lxml. After that, pyshark installed with no problems!
