### ISSUE TITLE
Output live capture to a file

### ISSUE THREAD

**Issue by chadianscot** [KimiNewt/pyshark#128]
I get the following error when I try to output my live capture to a file:

`Exception pyshark.capture.capture.TSharkCrashException: TSharkCrashException(u'TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.',) in <bound method LiveCapture.__del__ of <LiveCapture (0 packets)>> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 109, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 201, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/local/lib/python2.7/dist-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
OSError: [Errno 3] No such process`

My live capture command is `capture = cap = pyshark.LiveCapture(interface='eth0',output_file="test.pcap",bpf_filter = 'ether[0]=0x00 and ether[1]=0x04 and ether[2]=0xa3')`

If I remove the bpf_filter though, it works... Any ideas?

**Comment by KimiNewt** [comment]
Works for me, both with BPF and without.

Can you please specify:
1. The exact command you use to capture the packets after creating the LiveCapture.
2. Any output you get after using "cap.set_debug()" and then capturing
3. Your OS.
4. Wireshark version.

**Comment by chadianscot** [comment]
Sorry should have updated this post. I went down the route of not using the filter and using the tshark process instead and I'm happy enough with what my code now does. I can't remember what commands I was using, so the only answer I can provide to your questions was that I was using Raspbian Jessie on a Raspberry PI.
