### ISSUE TITLE
Pyshark "Decode_as" doesn't seem to work

### ISSUE THREAD

**Issue by HansRingenbach** [KimiNewt/pyshark#130]
Using pyshark, version 0.3.6.1, to decode UDP packets as RTP.   Using wireshark I verified the UDP packets are RTP packets.

I am using the command cap = pyshark.FileCapture("my_file.pcap", {'udp.srcport>1023':'rtp'}, display_filter='ip').     the script runs until I use a command like I[3].marker and then I get an attribute error.

How can I use pyshark to decode udp packets as RTP?
Thanks

**Comment by JuhPuur** [comment]
If you're using that command you should specify that your dictionary is directed to the decode_as parameter. It looks like you're setting the keep_packets parameter instead.

**Comment by KimiNewt** [comment]
What @JuhPuur said. Reopen if still an issue.
