### ISSUE TITLE
TCP analysis Options

### ISSUE THREAD

**Issue by GinesGarcia** [KimiNewt/pyshark#132]
Hi,
i'm trying to get some information from tcp packet when parsing pcap files (tcp.analysis in tshark). ¿Can you help me with it?

Thanks in advance.

**Comment by KimiNewt** [comment]
packet.tcp.analysis_[analysis_type], i.e. packet.tcp.analysis_acks_frame
Not the easiest to access, maybe a better way would be packet.tcp.analysis.acks_frame (needs to change the way fields work)
