### ISSUE TITLE
Error Observed when running P-shark

### ISSUE THREAD

**Issue by flamecopper** [KimiNewt/pyshark#133]
Hi there,

I currently have these 3 files. But here is the error observed.
##  3-pyshark.py\*  pyshark/  test.pcap*

I am executing 3-pyshark.py but it says no
import pyshark
cap = pyshark.FileCapture('/test.pcap')
print cap[0]

---

Traceback (most recent call last):
  File "3-pyshark.py", line 1, in <module>
    import pyshark
ImportError: No module named pyshark

**Comment by HuangZhenyang** [comment]
Same problem.

**Comment by HuangZhenyang** [comment]
I just solved this problem by installing pyshark from the git repository
