### ISSUE TITLE
SIP msg_body is empty with pyshark

### ISSUE THREAD

**Issue by dyj216** [KimiNewt/pyshark#135]
When opening a packet in Wireshark, I can see a separate part inside the SIP, the Message Body. In my case there is an xml in the Message Body. The pyshark does only have "Message Body" in the sip.msg_body attribute. I know, that the sip.msg_hdr contains my needed xml, but I think it should be under sip.msg_body.

I don't know if this is an issue or not, so any clarification would be nice.
Thanks!

**Comment by dgudtsov** [comment]
Hi, 
sdp part is there, try to access it:
frame.sip.get_field("sdp_media_attr")

there are also another hack how to access all media lines from sdp:
sdp_media_attr = frame.sip.get_field("sdp_media_attr")
print sdp_media_attr.fields

**Comment by dyj216** [comment]
Hi,
I found out, that the necessary part can be found, thanks to @dgudtsov !
