### ISSUE TITLE
Memory increase?

### ISSUE THREAD

**Issue by tanyewei** [KimiNewt/pyshark#141]
Long time running LiveCapture. tshark memory usage infinitely increasing?

**Comment by renatosamperio** [comment]
I have seen this issue too. Could be possible the parameter "keep_packets" was not buffering packets?

**Comment by AMNeves** [comment]
Does pyshark with livecapture uses infinite memory if we let it run always? im working on a network manager system and need a background permanent sniffer, need to test this, if this is true is there a way to make livecapture discard packets after parsing each?

**Comment by mtis88** [comment]
I am using the tshark -M auto session reset parameter to solve this.
