### ISSUE TITLE
Multiple MQTT messages in one packet

### ISSUE THREAD

**Issue by armandokeller** [KimiNewt/pyshark#142]
Hello, first of all I wan't to thank you for this awesome project.

I'm getting multiple MQTT packets inside one TCP packet (as in wireshark). If I print the packet they apear, but I can only access the first one.
If I call a dir(packet) it apears multiple "mqtt" options, but the key is the same, how can I access the other ones? My sugestion is find repeated protocols and make a list.

`cap = pyshark.FileCapture(arquivo,display_filter="mqtt.msg")

for pacote in cap:
    try:
        msg = {}
                #dir(pacote)   --> here return multiple mqtt parameters for the packet
        msg['mensagem'] = pacote.mqtt.msg
.....................
` 

Thanks.

**Comment by hmchaitra** [comment]
I am also facing the same issue please anyone do suggest a solution if any1 knows.

**Comment by mj138** [comment]
The get_multiple_layers() method in the Packet class should do what you require. E.g.,
```
cap = pyshark.FileCapture(filename, display_filter='mqtt')
for packet in cap:
    mqtt_layers = packet.get_multiple_layers('mqtt')
    for mqtt in mqtt_layers:
        do_stuff(mqtt)
```

**Comment by hmchaitra** [comment]
thank you..
