### ISSUE TITLE
display_filter option not working in pyshark.LiveCapture() routine

### ISSUE THREAD

**Issue by pjrobert** [KimiNewt/pyshark#143]
I am not having any success, getting the 'display_filter' option working in the PyShark  LiveCapture() routine.  I am using PyShark ver:0.3.6.1 with Python ver:3.5.1

Eg.

  import pyshark
  capture = pyshark.LiveCapture( interface="Embedded3", display_filter="ntp" )  #<-Doesn't work
  capture.sniff(packet_count=10)

  print( capture[0] )
  print( capture[0].ntp )
  print( capture[0].ntp.reftime )

**Comment by KimiNewt** [comment]
Not sure what the issue was, but display filter definitely work
