### ISSUE TITLE
FileCapture lost the first packet when parsing pcap file if only_summaries is True

### ISSUE THREAD

**Issue by dog-2** [KimiNewt/pyshark#148]
I've captured some dns packets through wireshark and saved as pcap, and i  want to parse it with pyshark.FileCapture。

And i need to set **_only_summaries_** to both False and True to get both packet details and summary info. When set to False, it works well, however when True got some bugs, the first packet was lost.

This was test on both osx and ubuntu and got the same result.

I've debugged into the source code and got a solution, however i didn't get clear about why the buffer reading and PSML parsing goes wrong:

Just delete or comment the source code in **_line 177_** of pyshark/capture/capture.py, which in _packets_from_tshark_sync() function and the code is:

``` python
data = b''
```

what's more, i've got another issue, which have been discussed in #88 but cannot work well.

**Comment by Qlzr** [comment]
You can try to change the value of the variable SUMMARIES_BATCH_SIZE from 64 to 8 in line 42 of 
 pyshark/capture/capture.py

**Comment by fkerem** [comment]
SUMMARIES_BATCH_SIZE = 4 (and 8) didn't work for me on MacOS.
SUMMARIES_BATCH_SIZE = 5 seems to work for now.

**Comment by fkerem** [comment]
> SUMMARIES_BATCH_SIZE = 4 (and 8) didn't work for me on MacOS.
> SUMMARIES_BATCH_SIZE = 5 seems to work for now.

This configuration is not valid for the newest version, that's why I use version `0.4.3`.
