### ISSUE TITLE
pychark can't show time ?

### ISSUE THREAD

**Issue by yashengsun** [KimiNewt/pyshark#150]
do you tell me that pychark can decode timestamp?
waiting online...

**Comment by dog-2** [comment]
as the example given in the doc:

```python
for packet in capture.sniff_continuously(packet_count=5):
    print 'Just arrived:', packet
```

u can get the timestamp as follows:

>>> packet.sniff_time
datetime.datetime(2016, 8, 24, 22, 35, 25, 977190)
>>> packet.sniff_timestamp
'1472049325.977190000'

**Comment by al1998petridis** [comment]
How can we find delta time (time between packets) ?
