### ISSUE TITLE
How to switch off promiscuous mode?

### ISSUE THREAD

**Issue by hranmuthu** [KimiNewt/pyshark#152]
pyshark.LiveCapture(interface='eth0') will always put the given interface into promiscuous mode. Is there a way to disable promiscuous mode ?

Thanks,
Harshana

**Comment by hranmuthu** [comment]
Can someone answer this please ?

**Comment by dog-2** [comment]
_tshark_ seems to capture in promiscuous mode as default, and _-p_ param can be specified to turn it off.

pyshark source code shows that it doesn't specify _-p_ parameter, so i think pyshark works in promiscuous mode:

*  in [pyshark/src/pyshark/capture/capture.py class Caputre](https://github.com/KimiNewt/pyshark/blob/master/src/pyshark/capture/capture.py)
 -f -c -o -w -d -l -n -T may be spcecified.

* in in [pyshark/src/pyshark/capture/live_capture.py class LiveCapture](https://github.com/KimiNewt/pyshark/blob/master/src/pyshark/capture/live_capture.py)
 -i -f  may be specified.

and LiveCapture is subclass of Capture, and -p is absence in both of them.

**Comment by hranmuthu** [comment]
Thanks. I'll try this today

**Comment by ajmeese7** [comment]
Has there been a new way implemented to manage this? I am still unable to launch a `LiveCapture` not in promiscuous mode, I get the following error:

```shell
    dumpcap_process = await asyncio.create_subprocess_exec(*dumpcap_params, stdout=write,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 818, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/bin/dumpcap'
```
