### ISSUE TITLE
Pyshark unable to parse sip header fields appeared multiple time

### ISSUE THREAD

**Issue by chirag226** [KimiNewt/pyshark#154]
Want to parse header field which appeared multiple time in SIP message. Pyshark always return the first instance of the header. How can i access the subsequent instance.

History-Info: sips:9000@x.x.x.x;index=1
History-Info: sips:9000@abc.com;index=1.1

using pyshark, i am able to get the below result. 

> > > print cap[0].sip.history_info
> > > sips:9000@x.x.x.x;index=1
> > > How can i access the second instance. Same issue happened with SIP/ SDP header where two multiple connection ip not getting retrieved by Pyshark

**Comment by dgudtsov** [comment]
Hi, i faced with the same issue and found solution. To access fields that are appeared multiple times, try this example:
sdp_media_attr = frame.sip.get_field("sdp_media_attr")
print sdp_media_attr.fields

then you can access each element via index, using: 
sdp_media_attr.fields[1]
