### ISSUE TITLE
tshark crashes when output_file assigned to file.

### ISSUE THREAD

**Issue by aloof-groundhog** [KimiNewt/pyshark#156]
Hello,

I apologize if this is a simple issue with my code, but I am wondering what could be causing this issue I'm having.

When I try assigning output_file, which is a parameter in live_capture.py, python says that tshark seems to have crashed.  Here is the function I have tried using:

```
def log(_interface):
    log_file = 'PyShark' + datetime.strftime(datetime.now(), '%Y%m%d%s')  + '.pcap' #or whatever file name
    capture = pyshark.LiveCapture(interface=_interface, only_summaries= True, output_file = log_file)
    for p in capture.sniff_continuously():
        print(str(p)) `
```

This results in the following:

Traceback

 (most recent call last):
  File "sniff.py", line 46, in <module>
    main()
  File "sniff.py", line 16, in main
    log(next(args))
  File "sniff.py", line 40, in log
    for p in capture.sniff_continuously():
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 183, in _packets_from_tshark_sync
    self._cleanup_subprocess(tshark_process)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 329, in _cleanup_subprocess
    raise TSharkCrashException('TShark seems to have crashed (retcode: %d). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.' % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <bound method Capture.__del__ of <LiveCapture (0 packets)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 337, in **del**
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 334, in close
    self._cleanup_subprocess(process)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 329, in _cleanup_subprocess
    raise TSharkCrashException('TShark seems to have crashed (retcode: %d). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.' % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

**Comment by KimiNewt** [comment]
I can't reproduce it and it seems to work for me.
Can you try rerunning it after using capture.set_debug() , like the exception says?
Try using all interfaces / a different interface name, see if it works without using an output file.

**Comment by Eviathor** [comment]
I believe the issue is because of memory problems.. Pyshark isn't very memory friendly from my experience. Have you considered using pcapdotnet to write some makeshift parser and porting it to the python code / write the whole thing in C#?
