### ISSUE TITLE
pyshark deal Certificate of ssl

### ISSUE THREAD

**Issue by sharpsec** [KimiNewt/pyshark#157]
hello,
      when pyshark deal with Certificate,i want to  extract issuer or subject,they all use the "x509sat_utf8string" which Can not lead to extract all of them,only one,i need your help,thank you

**Comment by rippledj** [comment]
This worked for me:

data = pyshark.FileCapture(args['pcap_path'])
    for pkt in data:
        if "SSL" in pkt:
            if hasattr(pkt['SSL'], 'x509sat_utf8string'):
                print(bytes.fromhex(pkt['SSL'].x509af_rdnsequence.raw_value))
