### ISSUE TITLE
Catch second Data of MIME_MULTIPART Ubuntu - Python

### ISSUE THREAD

**Issue by cristianpoleyJS** [KimiNewt/pyshark#158]
I want to catch username and password when one user connect to HTTP web. I want to catch the second Data with:

> packet['MIME_MULTIPART'].get_field_value("Data")

This always give me the first field Data (attach next photo). How do I get the second field Data? I also tried it with "get_field_by_showname".

![capturadepantallade2016-11-0413-55-56](https://cloud.githubusercontent.com/assets/15108191/20006462/f17c5dee-a297-11e6-8616-85c5994d8605.jpg)

Thanks so much!

**Comment by llutze2s** [comment]
If you still have to problem check out my ticket (https://github.com/KimiNewt/pyshark/issues/561).
