### ISSUE TITLE
consider new release (git tag)

### ISSUE THREAD

**Issue by anthraxx** [KimiNewt/pyshark#159]
Hey,
cool project :) 
I wanted to ask if it would be possible to get a new git tag aka release?
The last one is from 2015 and there are some nice patches/fixes etc :smile_cat:

**Comment by KimiNewt** [comment]
Sure, why not.

**Comment by anthraxx** [comment]
@KimiNewt 
cool thx :smiley: 
Hope you may get more time in the future as this project is great! We could need some love for #117 as trollius is dead :yum:
