### ISSUE TITLE
Pretty Formatting in Pyshark Print vs Query

### ISSUE THREAD

**Issue by Finnicus** [KimiNewt/pyshark#167]
Hi,

I am relatively new to using Pyshark, and is wondering if anyone can advise on this.

For example: I am looking at the results/text messages from **print pkt** vs **print.pkt.tcp.flags**

How do I get a value similar to how the print pkt is displaying vs the raw packets?

_**From print**_
Layer TCP:
	Expert Info (Warn/Sequence): Connection reset (RST)
	TCP Flags: *********R**
	Window size value: 0
	Connection reset (RST)
	Severity level: Warn
	Flags: 0x004 (RST)

_**From attributes**_
0x00000004

I would like to show RST when I print, versus the raw data instead. 
Appreciate the help.

**Comment by KimiNewt** [comment]
Hi,

In Wireshark (internally, anyway), the property as it is displayed in the panel is called **showname**.

In pyshark, you can access the value via: `pkt.tcp.flags.showname_value` and `pkt.tcp.flags.showname_key` to get the name. The whole line can be seen with `pkt.tcp.flags.showname`.

Similarly you can access the field with `pkt.tcp.flags.int_value` to get the actual number.
