### ISSUE TITLE
WPAN layer will be skipped

### ISSUE THREAD

**Issue by jobrud** [KimiNewt/pyshark#175]
Hi Guys,

I want to use pyshark for post processing of wpan (802.14.5) frames.  I added a sample capture to debug it. If you open this sample with Wireshark/Tshark it is providing you the wpan layer. Unfortunately pyshark is skipping this layer. See below the snipped:
```
cap[0].layers
[<6LOWPAN Layer>, <IPV6 Layer>, <UDP Layer>, <DATA Layer>]
```
It would be great if someone can help/fix this issue ! I really like this tool...

Thanks, 
jobrud

[capture.zip](https://github.com/KimiNewt/pyshark/files/777384/capture.zip)

**Comment by jobrud** [comment]
No one an idea ? Let me know when you need further information or support ...

**Comment by JuhPuur** [comment]
I see a wpan layer. No obvious ideas what's causing your problem.

**Comment by JuhPuur** [comment]
Wireshark shows wpan layer, Pyshark loads your file fine and also shows wpan layer. I'd diagnose it as either your tshark being wrong somehow or you've done something strange.

**Comment by jobrud** [comment]
Thanks a lot ! It was really a problem of my Tshark version. I tested it with version  2.2.4 and 2.2.3 and it is working !
