### ISSUE TITLE
Packet counting using pyshark

### ISSUE THREAD

**Issue by ivcstudent** [KimiNewt/pyshark#180]
Hello.
I was trying to create a simple packet counter using pyshark. It should be able to count and display the number of packets on the network at every 1 second interval. I tried the following code:

l = 0
cap = pyshark.LiveCapture(interface = 'eth0')
while True:
	cap.sniff(timeout = 1)
	print((len(cap) - l))
	l = len(cap)

However, this program seems to be very slow and cannot give proper output for low time intervals (1 s).
Please suggest modifications or other efficient methods to achieve the objective of counting and displaying the number of packets. I apologize if the problem seems trivial but as I am a beginner, any help would be appreciated.
Thanks.

**Comment by KimiNewt** [comment]
You can try using a callback function instead, like so:
```python
def my_callback(pkt):
    # do whatever
cap.apply_on_packets(my_callback)
```

You can also try creating your capture with ```LiveCapture(use_json=True)``` which should be faster. Note that it requires WS>2.2.0
