### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by afaucon** [KimiNewt/pyshark#182]
On Windows,
When I execute: `pip install pyshark`
I have the error: `Unable to find vcvarsall.bat`

According to Google, stackoverflow,... it seems that i have to install Microsoft Visual C++.
But I am not familiar with Microsoft products. It is not clear at all which microsoft product I have to install.
Does Microsoft Visual C++ (needed to install pyshark) come with visual studio community IDE that can be found here: [https://www.visualstudio.com](url) ?

 
`Collecting pyshark
  Downloading pyshark-0.3.6.3.tar.gz
Collecting lxml (from pyshark)
  Downloading lxml-3.7.3-cp35-cp35m-win32.whl (2.8MB)
    100% |################################| 2.8MB 263kB/s
Collecting py (from pyshark)
  Downloading py-1.4.32-py2.py3-none-any.whl (82kB)
    100% |################################| 92kB 2.6MB/s
Collecting trollius==1.0.4 (from pyshark)
  Downloading trollius-1.0.4.tar.gz (259kB)
    100% |################################| 266kB 1.6MB/s
Collecting logbook (from pyshark)
  Downloading Logbook-1.0.0-cp35-cp35m-win32.whl (89kB)
    100% |################################| 92kB 1.6MB/s
Installing collected packages: lxml, py, trollius, logbook, pyshark
  Running setup.py install for trollius ... error
    Complete output from command c:\myprogs\python\python3.5.1-32bits\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\toto\\AppData\\Local\\Temp\\pip-build-qsb2r4yt\\trollius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\toto\AppData\Local\Temp\pip-m_4eghy6-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\trollius
    copying trollius\base_events.py -> build\lib.win32-3.5\trollius
    copying trollius\base_subprocess.py -> build\lib.win32-3.5\trollius
    copying trollius\compat.py -> build\lib.win32-3.5\trollius
    copying trollius\constants.py -> build\lib.win32-3.5\trollius
    copying trollius\coroutines.py -> build\lib.win32-3.5\trollius
    copying trollius\events.py -> build\lib.win32-3.5\trollius
    copying trollius\executor.py -> build\lib.win32-3.5\trollius
    copying trollius\futures.py -> build\lib.win32-3.5\trollius
    copying trollius\locks.py -> build\lib.win32-3.5\trollius
    copying trollius\log.py -> build\lib.win32-3.5\trollius
    copying trollius\proactor_events.py -> build\lib.win32-3.5\trollius
    copying trollius\protocols.py -> build\lib.win32-3.5\trollius
    copying trollius\py27_weakrefset.py -> build\lib.win32-3.5\trollius
    copying trollius\py33_exceptions.py -> build\lib.win32-3.5\trollius
    copying trollius\py33_winapi.py -> build\lib.win32-3.5\trollius
    copying trollius\py3_ssl.py -> build\lib.win32-3.5\trollius
    copying trollius\queues.py -> build\lib.win32-3.5\trollius
    copying trollius\selectors.py -> build\lib.win32-3.5\trollius
    copying trollius\selector_events.py -> build\lib.win32-3.5\trollius
    copying trollius\streams.py -> build\lib.win32-3.5\trollius
    copying trollius\subprocess.py -> build\lib.win32-3.5\trollius
    copying trollius\tasks.py -> build\lib.win32-3.5\trollius
    copying trollius\test_support.py -> build\lib.win32-3.5\trollius
    copying trollius\test_utils.py -> build\lib.win32-3.5\trollius
    copying trollius\time_monotonic.py -> build\lib.win32-3.5\trollius
    copying trollius\transports.py -> build\lib.win32-3.5\trollius
    copying trollius\unix_events.py -> build\lib.win32-3.5\trollius
    copying trollius\windows_events.py -> build\lib.win32-3.5\trollius
    copying trollius\windows_utils.py -> build\lib.win32-3.5\trollius
    copying trollius\__init__.py -> build\lib.win32-3.5\trollius
    running build_ext
    building 'trollius._overlapped' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "c:\myprogs\python\python3.5.1-32bits\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\toto\\AppData\\Local\\Temp\\pip-build-qsb2r4yt\\trollius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\toto\AppData\Local\Temp\pip-m_4eghy6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\toto\AppData\Local\Temp\pip-build-qsb2r4yt\trollius\`

**Comment by KimiNewt** [comment]
This is an issue with trollius' installation, not pyshark. You can try installing prebuilt trollius from: http://www.lfd.uci.edu/~gohlke/pythonlibs/
