### ISSUE TITLE
FileCapture: Too many open files

### ISSUE THREAD

**Issue by Lfengjie** [KimiNewt/pyshark#186]
Hello:
        I use pyshark to parse more than 1,000 pcap files， I used the class named FileCapture, but it shows that too many open files. I used method named close(), but no use.

**Comment by kondonky** [comment]
Exactly.
I mentioned that problem in issue [#168](https://github.com/KimiNewt/pyshark/issues/168).
Please see my comment.

**Comment by sikam** [comment]
Same problem here:
```
capture1 = pyshark.FileCapture(file1_path_name, tshark_path=PathToTshark)
print(capture1[0])
capture1.close()

capture2 = pyshark.FileCapture(file2_path_name, tshark_path=PathToTshark)
print(capture2[0])
capture2.close()
```
Encountered this issue with pyshark 0.3.7.9 on Python 3.6.2 on Win7 64bit
As soon as you exit Python you'll get the error messages...

Are there any plans on fixing this issue?
