### ISSUE TITLE
tshark crashes when reading from a live interface 

### ISSUE THREAD

**Issue by florianmopin** [KimiNewt/pyshark#189]
Hi,

I'm trying to read from a live interface. I'm on Mac OSX 10.11.6 
This is my code

```
capture = pyshark.LiveCapture(interface='en0')
capture.sniff(timeout=50)
print(capture)
```

When I execute the file I got this error:

   

> capture.sniff(timeout=50)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 124, in load_packets
>     self.apply_on_packets(keep_packet, timeout=timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 239, in apply_on_packets
>     return self.eventloop.run_until_complete(coro)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/base_events.py", line 300, in run_until_complete
>     return future.result()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/futures.py", line 287, in result
>     raise self._exception
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/tasks.py", line 255, in _step
>     result = next(coro)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/tasks.py", line 424, in wait_for
>     raise Return(fut.result())
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/futures.py", line 287, in result
>     raise self._exception
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trollius/tasks.py", line 255, in _step
>     result = next(coro)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 257, in packets_from_tshark
>     self._cleanup_subprocess(tshark_process)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 387, in _cleanup_subprocess
>     raise TSharkCrashException('TShark seems to have crashed (retcode: %d). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.' % process.returncode)
> pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
> Exception ignored in: <bound method Capture.__del__ of <LiveCapture (0 packets)>>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 394, in __del__
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 391, in close
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyshark/capture/capture.py", line 387, in _cleanup_subprocess
> pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

When I put capture.set_debug() I have this 
<LiveCapture (0 packets)>

Do you have any idea? Thanks for the answers!

**Comment by sharkwheels** [comment]
I'm having this issue as well. Can you run "tshark -c 100 -i en0" on the command line w/out using sudo?

**Comment by KimiNewt** [comment]
You have to run set_debug() before the sniffing. Also, check that you have permissions to capture and use tshark on the user you're running this from.

**Comment by Danaozhong** [comment]
Facing the latest problem with latest master and Wireshark 2.6.5 8x64) on Windows 7.

Exception ignored in: <bound method Capture.__del__ of <LiveCapture (0 packets)>
>
Traceback (most recent call last):
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\site-packages\pyshark-0.4.2.2
-py3.5.egg\pyshark\capture\capture.py", line 415, in __del__
    self.close()
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\site-packages\pyshark-0.4.2.2
-py3.5.egg\pyshark\capture\capture.py", line 406, in close
    self.eventloop.run_until_complete(self._close_async())
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\asyncio\base_events.py", line
 387, in run_until_complete
    return future.result()
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\asyncio\futures.py", line 274
, in result
    raise self._exception
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\asyncio\tasks.py", line 239,
in _step
    result = coro.send(None)
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\site-packages\pyshark-0.4.2.2
-py3.5.egg\pyshark\capture\capture.py", line 410, in _close_async
    await self._cleanup_subprocess(process)
  File "C:\TOOL\Common\Python3\Python352_32bit\lib\site-packages\pyshark-0.4.2.2
-py3.5.egg\pyshark\capture\capture.py", line 403, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retc
ode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating
 tshark.
