### ISSUE TITLE
NameError: global name 'Gen' is not defined

### ISSUE THREAD

**Issue by hoyeunglee** [KimiNewt/pyshark#199]
```
cap = pyshark.FileCapture(r'C:\Users\martlee2\Downloads\dhcp.pcap')
cap[0].show()
cap[0].summary()
responsepkt = sr1(cap[0])
```

can pyshark use with scapy?
i use pyshark to read captured packet 
and then send packet with scapy

**Comment by KimiNewt** [comment]
Pyshark packets are different objects from scapy packets. This will not and can not work.
