### ISSUE TITLE
install error in window subsystem ubuntu

### ISSUE THREAD

**Issue by hoyeunglee** [KimiNewt/pyshark#200]
Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitI8Vgw9.c -o tmp/xmlXPathInitI8Vgw9.o

/tmp/xmlXPathInitI8Vgw9.c:1:26: fatal error: libxml/xpath.h: No such file or directory

 #include "libxml/xpath.h"

                          ^

compilation terminated.

*********************************************************************************

Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?

*********************************************************************************

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1TvIN2-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /home/martin/.pip/pip.log
martin@hello-R5M4D:/mnt/c/Users/hello$

**Comment by KimiNewt** [comment]
This is an issue with installing lxml, not pyshark. You can ask there or try installing it via an exe.
