### ISSUE TITLE
How to write a pcap file with PyShark?

### ISSUE THREAD

**Issue by mluethi** [KimiNewt/pyshark#203]
I have a captured pcap file which I want to filter for a certain http host. 
Because I not only want the http packets I search first for the http streams and save their stream numbers. 
In a second step I filter the pcap file for these found stream numbers.

Here is what I do: 

```
import pyshark 
INFILE = './xy_2017-03-30.pcapng'

def get_http_streams(host):
    pcap = pyshark.FileCapture(INFILE, only_summaries=False, display_filter=f'http.host contains "{host}"')
    streams = set()
    for p in pcap:
        stream_nr = int(p.tcp.stream)
        streams.add(stream_nr)
    print()
    print(f'Found {len(streams)} "{host}" streams.')
    return streams

s = get_http_streams('google') 
pcap = pyshark.FileCapture(INFILE)

pkt_list = [] 
print('Filtering...')
for i, p in enumerate(pcap):
    try:
        stream_nr = int(p.tcp.stream)
    except AttributeError:
        stream_nr = -1
    if stream_nr in s:
        pkt_list.append(p)

# -----------------------------------------------------------------------------
# How to write a pcap file now? pyshark.WriteFile(pkt_list, 'result.pcap') ?!
# -----------------------------------------------------------------------------

print('END')
```

Now I have a list with the filtered packets. 
How would I write them out now to a new pcap file?
I cannot find a way to write a pcap file...

Thanks for any help!

**Comment by KimiNewt** [comment]
Short answer: You can't.
Long answer: Pyshark is a packet parsing only package, being a wrapper of tshark. The new JSON capability also allows storing the raw data of the packets which means you can access the raw data and rewrite that to a cap file, however the writing itself is currently outside of pyshark's scope and so you'll need to use something else like Construct or scapy to write the packets.
