### ISSUE TITLE
Problem with the performance LiveCapture.

### ISSUE THREAD

**Issue by achaychenko** [KimiNewt/pyshark#209]
Tshark dumps per 1 minute 11 files of 200 MB each (*.pcapng)
1 file - 30216 lines in pcapng and 534158 lines after FileCapture - only_summaries=True
System - 32 cores etc..

If I use - 
`cap = pyshark.LiveCapture(interface='eno2', only_summaries=True)
    for packet in cap.sniff_continuously():`

for interception the stream. After that output starts to delay print packets. I've tryed to use buffer for accumulation - 100 000 packets - for writing - It doesn't work.
Any ideas?

**Comment by KimiNewt** [comment]
There can be a bunch of problems and solutions, but first try using `json_mode=True` in your LiveCapture constructor (and remove `only_summaries`)

**Comment by achaychenko** [comment]
> and remove only_summaries
But I have to split and write history of summaries only.

**Comment by ZackAlfakir** [comment]
I am also having this problem, but I'm already using use_json=True and I'm not using only_summaries.

This seems to be related to #137, #112 

It seems that not only is pyshark slower at processing the information, but it gets worse over time.

What are your recommendations for the highest optimization without using only_summaries? I can submit a PR if it needs to be done.

**Comment by robgom** [comment]
Would it be possible to offer an interface of capturing to file only (without using stdout at all) (file_only=True|False)?
Would it help in this case?
From what I looked in the code it wouldn't be that easy (but shouldn't be that hard, either).

Regards,
Robert

**Comment by ZackAlfakir** [comment]
@robgom Do you mean just using python to capture packets and store them to a file. It seems like calling tshark would have the same effect at that point.

**Comment by achaychenko** [comment]
resolved for me

**Comment by robgom** [comment]
Yes, I mean just using python to capture packets and store them to a file.
Calling tshark would have the same effect, but I would like to use the Python abstraction instead of manually crafting command line arguments for subprocess call (what I do now currently).
Should I report such a request elsewhere?

Regards,
Robert

**Comment by ZackAlfakir** [comment]
scapy has a function similar, but it seems like if that is all you are going for, then might as well do it yourself. Should only be a couple lines with the either `os.system` or `subprocess`

**Comment by robgom** [comment]
Thank you for the feedback.

Please consider this:

    dumpstatus = subprocess.call('%s -i %s -a duration:3 -P -w "%s"'%(dumpcap_exe_path,SniffInterfacePath,FilePath), shell=False)

and this:

LiveCapture(interface=SniffInterfacePath, output_file=FilePath, file_only=True).load_packets(3)

The latter gives me an interface I'm after, the former is not pleasant to work with.
And that's even without specifying filters or additional parameters...

I'm aware of scapy capabilities, I use it as well, but sometimes I'd like to stick to single solution (scapy is utilized when packets are sent, sometimes I just want to read them).

Does it sound reasonable?
I don't want to hijack this issue, I stop here, unless you think it'd be beneficial to request separately.

Regards,
Robert

**Comment by ZackAlfakir** [comment]
@robgom Just as a heads up, the dev for this repo hasn't been active since November 2017.

**Comment by KimiNewt** [comment]
@robgom This is reasonable and actually not too difficult, as @ZackAlfakir said I'm not actively working on this project. Please create a separate issue and maybe someone will add a PR. Maybe it will even be me (no promises).
