### ISSUE TITLE
BOOTP Fields Are Not Displayed Correctly

### ISSUE THREAD

**Issue by sitler** [KimiNewt/pyshark#211]
Hello,

In tshark, if I run "-T fields -e bootp.option.request_list_item" on a DHCP request packet, it returns something like "1,3,6,15,31,33,43,44,46,47,121,249,252".  However, if I attempt to get this data from PyShark (with use_json=False), it only returns the first result of "1".  The same thing happens if I attempt to retrieve bootp.option.type.  I believe this has something to do with the fact that there are several bootp.option.request_list_items (see Issue #196).

In Issue #196, you suggested that a user having a similar problem attempt to use JSON rather than the default XML .  When I set use_json=True, I am then able to retrieve bootp.option.type successfully.  However, bootp.option.request_list_item is not an available field.  Several other bootp fields (such as option_requested_ip_address, option_hostname, fqdn_name, option_vendor_class) are also not available in JSON, but they are in XML.  

Ideally, I'd like to get bootp.option.request_list_item and bootp.option.type to work with the default setting of XML.  If this is not possible, the next best option would be to get bootp.option.request_list_item and the other fields to return correctly in JSON.

Any help or direction with this issue would be greatly appreciated.

Thank you,

Mike

**Comment by KimiNewt** [comment]
You have two options.
If using XML, to retrieve all option types:
```python
# To get all field types
pkt.bootp.option_type.all_fields

# To get all request items
pkt.bootp.option_request_list_item.all_fields
```
Note that those results will return a LayerField type object. You can access the value in various ways, so see which one is best for you. The available fields of LayerField for accessing the value are:
'base16_value',
 'binary_value',
 'get_default_value',
 'hex_value',
 'int_value',
 'raw_value',
 'showname',
 'showname_key',
 'showname_value'

If using JSON:
```python
# This will retrieve the type numbers.
pkt.bootp.type
# This will retrieve the type data, in the same order as the numbers above
pkt.bootp.type_tree
# For easier access you can do:
type_dict = dict(zip(pkt.boot.type, pkt.bootp.type_tree))
```
From the type dict or directly from the tree you can get the request_list_item.

The advantage of using JSON is that it's faster.

A more detailed explanation: The difference in the structure of XML and JSON packets is that XML fields are all "flat" on the original layer and you must use `.all_fields` if there are multiple ones. In JSON, as you can see, a type can return lists and fields may be inside other fields.

I believe the JSON method is better, but I did not want to change the XML one do it will remain backwards compatible.

Please close this issue if the explanation was satisfactory.

Dor.

**Comment by sitler** [comment]
Thank you very much for providing a clear explanation.  I followed your recommendation regarding using "all_fields" with XML and this resolved the issue I was experiencing with bootp.option_request_list_item.  However, I'm still experiencing an issue while attempting to access the values of bootp.option_type.  

**Bootp.option_request_list_item**

For bootp.option_request_list_item, the "raw_data" looks like this: 01, 03, 06, 0f, 1f, 21, 2b, 2c, 2e, 2f, 79, f9, fc. 

When I use the "base16_value" option listed above, it returns "1, 3, 6, 15, 31, 33, 43, 44, 46, 47, 121, 249, 252."  This is just like tshark.  It works great.

**Bootp.option_type**

For bootp.option_type, the "raw data" looks like this: "350103, 3d0701005056942a90, 3204ac136f34, 0c135365637572697479576f726b73746174696f6e, 51340000005365637572697479576f726b73746174696f6e2e474f5645524e4d454e542e4c4548494748434f554e54592e4c4f43414c, 3c084d53465420352e30, 370d0103060f1f212b2c2e2f79f9fc, ff."  

When I use the "base16_value" option listed above, it returns "3473667, 1125756073474574789264, 54995648212788, 17648350266652913180312951134365619458865717931886, 3517960058681478067637528575869745062617475902027850586858291176044042244619558381394624036943259891956477093538858250509482148172, 283495134799259508223536, 285840078708205499667111120941480444, 255."  This is not like tshark and what I'm trying to resolve.

If I use the "showname" option listed above, it returns "(53) DHCP Message Type (Request), Option: (61) Client identifier, Option: (50) Requested IP Address, Option: (12) Host Name, Option: (81) Client Fully Qualified Domain Name, Option: (60) Vendor class identifier, Option: (55) Parameter Request List, Option: (255) End."

Is there a way to retrieve the values 53, 61, 50, 12, 81, 60, 55, 0 from bootp.option_type like you can in tshark?  Again, any help or direction with resolving this issue would be greatly appreciated.

Thanks again,

Mike

**Comment by KimiNewt** [comment]
Specifically for option_type you can it by using:
```options = pkt.bootp.option_type.all_fields
options[0].get_default_value()
```

Will get you what you want (it takes the .show field for the value -- which is the "nice" representation by Wireshark of the value). I realise it is a bit troublesome to find out how to retrieve each value but we're at the whim of tshark. I think JSON is more consistent which is why I'm slowly migrating to that as a more solid option.

At any rate, if you have further question, feel free to ask me directly by email, on the package gitter, on stackoverflow or twitter. Issues are usually for actual issues with the package rather than general questions.

**Comment by sitler** [comment]
Will do.  Thanks again for the assistance, @KimiNewt.
