### ISSUE TITLE
list of streams from a PCAP

### ISSUE THREAD

**Issue by Srivathsan-Srinivas** [KimiNewt/pyshark#212]
Hi,
   Is there a neat way to list out all the streams from a pcap? if so, can anyone give me a short example?

The below code lists out all the pkts. Is there anything equivalent for streams?

```
cap = pyshark.FileCapture(self._pcap, keep_packets=False, display_filter='http')
for pkt in cap:
      print pkt
```

And, what does this mean:

```
In [17]: for pkt in cap:
    ...:     print pkt.tcp.stream
    ...:
0
0
1
1
```
Does it mean that the first two pkts belong to stream-0 and the next two belong to stream-1? I checked the packet themselves and the src/dst IP/ports are the same for all the 4 pkts in there..(except the src and dst are switched..) alternately. By definition of stream, I presume that I must see only one stream (that has 4 pkts going back and forth).

Can anyone help please? I want to extract all the unique streams in pcap - and subsequently look into all the packets of each stream. Any ideas?

Thanks!

**Comment by strizhechenko** [comment]
I recently had a struggle with splitting big PCAP's by tcp-streams for following analyze in python. Maybe this lua splitter will help you implement something similar with pyshark :) https://github.com/strizhechenko/tshark-tcp-stream-splitter
