### ISSUE TITLE
PipeCapture implementation

### ISSUE THREAD

**Issue by Radu-Raicea** [KimiNewt/pyshark#215]
Are there plans to implement the PipeCapture class in order to use file-like objects? I am downloading the capture file contents through a HTTP request and it is a waste of memory/execution time to write the capture file in the secondary memory and read it back into PyShark.

I could work on an implementation if needed, but would need some pointers. @KimiNewt

**Comment by ZackAlfakir** [comment]
I am also in need of a PipeCapture class. There seems to be something in the `master` branch, however, it does not appear when using the version installed with `pip` @KimiNewt is it included in that release or will I have to update from source?

**Comment by Radu-Raicea** [comment]
@KimiNewt Any update for this?

**Comment by ZackAlfakir** [comment]
@Radu-Raicea I was able to use FileCapture on a pipe created with `mkfifo`. It's not perfect, but it will work as a temporary workaround.
