### ISSUE TITLE
pyshark 3.7.9 does not work in windows 10

### ISSUE THREAD

**Issue by tim-keithy** [KimiNewt/pyshark#218]
Successfully install the pyshark in windows 10.

Tried to LiveCapture but no packet is captured for any interfaces.

Also tried both python 3.5  and python 2.7.  Any help please ? Thanks

-------------------
>>> import pyshark
>>> pyshark.tshark.tshark.get_tshark_interfaces()
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import pyshark
>>> pyshark.tshark.tshark.get_tshark_interfaces()
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
>>>
>>> cap = pyshark.LiveCapture(interface='1')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>> cap = pyshark.LiveCapture(interface='11')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>>

---- PYTHON 2.7

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import pyshark
>>>
>>> pyshark.tshark.tshark.get_tshark_interfaces()
[u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12']

>>> cap = pyshark.LiveCapture(interface='1')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>

>>> cap = pyshark.LiveCapture(interface=u'1')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>

>>> cap = pyshark.LiveCapture(interface=u'2')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>> cap = pyshark.LiveCapture(interface='2')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>> cap = pyshark.LiveCapture(interface='3')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>> cap = pyshark.LiveCapture(interface='4')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>>
>>> cap = pyshark.LiveCapture(interface='5')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>
>>> cap = pyshark.LiveCapture(interface=u'4')
>>> cap.sniff(timeout=2)
>>> cap
<LiveCapture (0 packets)>

**Comment by KimiNewt** [comment]
Try a file capture or actually getting one of the packets in the sniff (i.e. cap[0])

**Comment by kjkalliojarvi** [comment]
I have the same issue. In Windows 10

- with pyshark 0.3.7.9 LiveCapture does not work on any interface (it just does not capture any packets). FileCapture works.
- With pyshark 0.3.6.2 LiveCapture works like a charm.

I've been using pyshark for awhile, and ran into this problem when I updated pyshark.

**Comment by wenqiangwang** [comment]
Same issue with 0.3.7.11.

**Comment by kubark42** [comment]
Same problem here. Can't get it to work on `0.3.7.11`.

@wenqiangwang can you provide a working code example? I'm not sure how to "manually run '-i 1 -i 2 -i3'".

**Comment by SofiaArancibia** [comment]
Hi! The actual solution for the problem is roll back to pyshark 0.3.6.2? I'm getting the same issue..
