### ISSUE TITLE
Reads pcapng, filters, and writes to new pcapng file 

### ISSUE THREAD

**Issue by tim-keithy** [KimiNewt/pyshark#219]
I would like to read the previous captured .pcap, and search/ filter, then save the result to new file.pcapng?

Any help? the syntax - Thanks

cap = pyshark.FileCapture('/tmp/test.pcap')

for loop to filter:
  dst.port == 443 and src.port == 23456 
  or src.port == 443 and dst.port == 23456

save all the packets that matched filter condition to a file '/tmp/results_443.pcapng'

**Comment by KimiNewt** [comment]
Hi, this was unavailable, but I just added a feature to make that possible, so you'll have to pull from the repository.
The syntax will be:

```
cap  = pyshark.FileCapture("/tmp/test.pcap", output_file="/tmp/output.pcap")

# Or else iterate through all the packets. You can also do cap.apply_on_packets(lambda pkt: None)
cap.load_packets()
```

**Comment by stadelmannj** [comment]
Hi, 
Can you explain in more Details how I Can write out the result of an Iteration (for Loop) ? 
for example, from a file opened in cap, i want to write out all packets containig a given string in SIP.From Header
my current, working Loop looks the following:
``
