### ISSUE TITLE
Does pyshark support / include 802.11 dissestor ?

### ISSUE THREAD

**Issue by tim-keithy** [KimiNewt/pyshark#220]
Does pyshark include 802.11 decoder ?  if yes, where can I learn the filter command/syntax?

For example in wireshark/tshark:
(wlan.ht.capabilities.short40 == 1) && (wlan.ssid == "My Network")

**Comment by KimiNewt** [comment]
Filters are the same as in wireshark and can be provided in the `display_filter` flag. You can then access the fields as described in the documentation.

Note that issues are for actual issues with the package rather than general questions, there's stackoverflow and the like for that.
