### ISSUE TITLE
Additional tshark options

### ISSUE THREAD

**Issue by TechplexEngineer** [KimiNewt/pyshark#223]
I'd like to pass the -s flag to tshark to limit the length of the packet being processed by pyshark. Some of my packets are large HTTP payloads and it really backs up the pyshark tool.

Is there a reason not to pass the [-s flag](https://www.wireshark.org/docs/man-pages/tshark.html#s-capture-snaplen) to limit the capture length?

**Comment by jtown84** [comment]
I definitely agree with this.  There are quite a few tshark options that are unavailable.  I am looking to try to do a -C <configuration profile> to limit 99% of dissectors and improve ingest speed.  Just seems to be a limitation.

I'm having some issues identifying where the tshark command is built at.
