### ISSUE TITLE
Getting 0 packets when using pyshark.LiveCapture

### ISSUE THREAD

**Issue by cswarnan** [KimiNewt/pyshark#227]
Hi,

I am trying to capture network packets with below script

import pyshark
capture = pyshark.LiveCapture(interface='Local Area Connection')
capture.sniff(timeout=10)

I am getting <LiveCapture (0 packets)>

I am running Windows 7 machine with all admin rights and pyshark 0.3.7.9. Please help.

**Comment by foynd** [comment]
I had the same issue, a temporary fix that I found was to just revert the version from 0.3.7.9 to 0.3.6.2

**Comment by poetL** [comment]
I had the same issue, but when I try again that is ok
