### ISSUE TITLE
LiveCapture in not working

### ISSUE THREAD

**Issue by adityasriv22** [KimiNewt/pyshark#231]
Traceback (most recent call last):
  File "p.py", line 52, in <module>
    capture.sniff(timeout=50)
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 124, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 243, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/local/lib/python2.7/dist-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
pyshark.tshark.tshark.TSharkNotFoundException: TShark not found. Try adding its location to the configuration file. Search these paths: ['C:\\Program Files\\Wireshark\\tshark.exe', '/home/aditya/bin/dumpcap', '/home/aditya/.local/bin/dumpcap', '/usr/local/sbin/dumpcap', '/usr/local/bin/dumpcap', '/usr/sbin/dumpcap', '/usr/bin/dumpcap', '/sbin/dumpcap', '/bin/dumpcap', '/usr/games/dumpcap', '/usr/local/games/dumpcap', '/snap/bin/dumpcap']

Please resolve or provide solution

**Comment by adityasriv22** [comment]
Its solved

**Comment by moatazyassin** [comment]
how you solve it ?

**Comment by HansDaigle** [comment]
Simple, install wireshark :)

**Comment by ayedaemon** [comment]
i installed wireshark for windows(but not in default folder; also i have mentioned its path in system variables).
It's working perfectly from cmd but with pyshark i get TsharkNotFoundError

**Comment by poligenius** [comment]
how did you solved it? I'm loosing my mind

**Comment by ayedaemon** [comment]
Primary issue was with the path that was used by python interpreter. Later I tried in ot linux and it worked without any issue.

If you have no specific requirements to work on windows environment, then I'll suggest to go with a virtual machine or a docker container (prefered way). That's the workaround I used to play with this library.
