### ISSUE TITLE
Unable to use len(cap) or next_packet() function

### ISSUE THREAD

**Issue by ohmtrivedi** [KimiNewt/pyshark#236]
This will be a very lame question. But can you explain to me how to use the len(cap) function?

`pcap = pyshark.FileCapture('14.pcap', only_summaries=True)`

The pcap file is pretty huge (7.5 GB uncompressed), and I would like to know the number of packets. len(pcap) returns me 0.

Also, if I set keep_packets = False, and then ran print(pcap.next_packet()). I get the following error:

File "C:/Users/Ohm/Desktop/Project/readPCAP.py", line 9, in 
print(pcap.next_packet())
File "C:\Users\Ohm\Anaconda3\lib\site-packages\pyshark\capture\capture.py", line 93, in next_packet
raise StopIteration()
StopIteration

**Comment by stfl** [comment]
I had the same problem today.. you have to load the packets first
`cap.load_packets()`
