### ISSUE TITLE
Pyshark not parsing the cflow layer for netflow packets properly.

### ISSUE THREAD

**Issue by harashee** [KimiNewt/pyshark#237]
Below is the pretty print for layer CFLOW. You could see it has 3 pdu. It should be aligned under three sections. But here 1st pdu shows up properly but other 2 pdu are jumbled together and displayed as duplicate values. I have made bold on few of the duplicates.

Pyshark version : pyshark (0.3.6.1)
Running platform: Ubuntu 14.04

**Layer CFLOW:**
        pdu 1/3
        Count: 3
        SysUptime: -2222.2072041296 seconds
        Timestamp: Nov 22, 2017 11:00:32.237881015 UTC
        Version: 5
        SrcPort: 49702
        IP ToS: 0x00
        StartTime: 484630.974000000 seconds
        Duration: 0.000000000 seconds
        Packets: 2
        CurrentNSecs: 237881015
        NextHop: 198.250.63.93
        DstPort: 9901
        CurrentSecs: 1511348432
        FlowSequence: 47
        EndTime: 484630.974000000 seconds
        Protocol: Unknown (253)
        DstAS: 57692
        SrcAddr: 25.0.2.196
        EngineId: 1
        Padding: 00
        InputInt: 23679
        DstMask: 127 (prefix: 25.0.2.98/127)
        ..00 0000 0000 0001 = SampleRate: 1
        SrcAS: 12392
        00.. .... .... .... = SamplingMode: No sampling mode configured (0)
        SrcMask: 92 (prefix: 25.0.2.192/92)
        Octets: 248
        OutputInt: 0
        DstAddr: 25.0.2.99
        TCP Flags: 0x02
        EngineType: VIP/Linecard (1)
        **pdu 2/3
        pdu 3/3**
        SrcPort: 49736
        SrcPort: 49728
        IP ToS: 0x00
        IP ToS: 0x00
        StartTime: 484630.974000000 seconds
        StartTime: 484630.974000000 seconds
        Duration: 0.000000000 seconds
        Duration: 0.000000000 seconds
        Packets: 17
        Packets: 1
        **NextHop: 0.0.0.0
        NextHop: 0.0.0.0**
        DstPort: 9901
        DstPort: 9901
        EndTime: 484630.974000000 seconds
        EndTime: 484630.974000000 seconds
        **Protocol: Unknown (253)
        Protocol: Unknown (253)**
        DstAS: 0
        DstAS: 0
        SrcAddr: 25.0.2.196
        SrcAddr: 25.0.2.196
        Padding: 0000
        Padding: 00
        Padding: 0000
        Padding: 00
        Padding: 0000
        InputInt: 0
        InputInt: 0
        DstMask: 0 (prefix: 25.0.2.99/32)
        DstMask: 0 (prefix: 25.0.2.99/32)
        SrcAS: 0
        SrcAS: 0
        SrcMask: 0 (prefix: 25.0.2.196/32)
        SrcMask: 0 (prefix: 25.0.2.196/32)
        Octets: 2108
        Octets: 124
        OutputInt: 0
        OutputInt: 0
        DstAddr: 25.0.2.99
        DstAddr: 25.0.2.99
        TCP Flags: 0x02
        TCP Flags: 0x02

However, in wireshark I could see 3 pdu are properly aligned under different section.

**Comment by harashee** [comment]
I am facing the same issue. What @srinivasmiskin meant is in CFLOW layer, we get multiple sets of flows. However when we try to parse it using pyshark. That hierarchy is lost. If you see the below pretty_print of cflow layer. There are two flows - Flow 1 and Flow 2 with each having different set of DstAddr and SrcAddr. But here it got two set of values without any hierarchy to traverse properly.

Layer CFLOW:
FlowSet 1 [id=1024] (2 flows)
FlowSet Id: (Data) (1024)
CurrentSecs: 1523013382
FlowSequence: 260
Count: 2
SysUptime: 707.374000000 seconds
Timestamp: Apr 6, 2018 11:16:22.000000000 UTC
Version: 9
Template Frame: 1
DstAddr: 25.0.2.253 (value overwritten)
SrcAddr: 25.0.2.73 (value overwritten)
FlowSet Length: 20
SourceId: 0
Flow 1
Flow 2
DstAddr: 25.0.2.73
SrcAddr: 25.0.2.253

Please find the attached pcap file where you could see clearly two flows Flow 1 and Flow 2 properly segregated if you open in Wireshark. Please let me know if it is still not clear

I have raised similar issue #237 . I hit this issue in 2.7 python. Similar to #183 

[2flow-1.zip](https://github.com/KimiNewt/pyshark/files/1886063/2flow-1.zip)

**Comment by hagaisela** [comment]
I found a workaround. apparently you can access other session data by using the all fields array:
session_pkt.cflow.srcaddr.all_fields[session_idx].get_default_value()

**Comment by tyler-8** [comment]
> I found a workaround. apparently you can access other session data by using the all fields array:
> session_pkt.cflow.srcaddr.all_fields[session_idx].get_default_value()

Using that approach seems to work fine to get all the needed data. I think this issue can be closed.

I've created a simple script here to showcase how you can link all the flow data fields together

https://gist.github.com/tyler-8/bcdfe6ab86120ac7710597da7de1d51a
