### ISSUE TITLE
tcp.payload AttributeError

### ISSUE THREAD

**Issue by poxyran** [KimiNewt/pyshark#239]
Hi!, I've just installed Pyshark in a Windows 10 x64 and a Raspi3, both via pip3 but I'm having some inconsistencies. Both seem to be the same version (0.3.7.11). On Windows, I can access the payload attribute from a tcp object but if I try the same in the PI, I get an AttributeError. 

`In [13]: p.transport_layer
Out[13]: 'TCP'

In [14]: p
Out[14]: <TCP/VSSMONITORING Packet>

In [15]: p.transport_layer
Out[15]: 'TCP'

In [16]: p.tcp
Out[16]: <TCP Layer>

In [17]: p.tcp.payload
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-740b38941bc0> in <module>()
----> 1 p.tcp.payload

/usr/local/lib/python3.5/dist-packages/pyshark/packet/layer.py in __getattr__(self, item)
     34         val = self.get_field(item)
     35         if val is None:
---> 36             raise AttributeError()
     37         if self.raw_mode:
     38             return val.raw_value

AttributeError:
`

On Windows, the attribute exists:

`In [13]: packet
Out[13]: <TCP/VSSMONITORING Packet>

In [14]: packet.tcp
Out[14]: <TCP Layer>

In [15]: packet.tcp.payload
Out[15]: '01:00:1c:63:b5:26:a2:38:e6:6c:e8:36:ee:9a:2d:ef:c8:86:a0:13:12:db:2a:ba:cd:98:7a:6f:47:0c:15'
`

In both cases, the packet is the same. Btw, I'm using a FileCapture object.

Any clue on what could be happening?

**Comment by DD152** [comment]
Hi!
I face similar issue when i want to use `dns.qry.name`.So, did find a way to solve this problem or replace pyshark?
Forgive my stupidity.
thanks!

**Comment by DD152** [comment]
> Hi!
> I face similar issue when i want to use `dns.qry.name`.So, did find a way to solve this problem or replace pyshark?
> Forgive my stupidity.
> thanks!

[solution](https://github.com/KimiNewt/pyshark/issues/469)
