### ISSUE TITLE
UnicodeDecodeError when I try to get interfaces

### ISSUE THREAD

**Issue by taoxinyi** [KimiNewt/pyshark#240]
>>> import pyshark
>>> pyshark.tshark.tshark.get_tshark_interfaces()
['C:\\Program Files\\Wireshark\\tshark.exe', '-D']
The NPF driver isn't running.  You may have trouble capturing or
listing interfaces.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python36\lib\site-packages\pyshark\tshark\tshark.py", line 129, in get_tshark_interfaces
    tshark_interfaces = check_output(parameters).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 43: ordinal not in range(128)

Is this because my OS is Chinese? Because of this error I can't sniff.

**Comment by snakeyc** [comment]
open _**packet\fields.py**_, find function _**LayerFieldsContainer.\_\_new\_\_**_, then modify as followed,
`obj = str.__new__(cls, value, *args, **kwargs)` ==>
`obj = str.__new__(cls, value.encode(sys.getfilesystemencoding()), *args, **kwargs)`

**Comment by Dave1704** [comment]
I have the same problem with a German Windows 10. Also applying the changes suggested by @snakeyc 
the program fails with the following error:

`global name 'sys' is not defined`
