### ISSUE TITLE
Capture filter for GSMMAP

### ISSUE THREAD

**Issue by techwizardg** [KimiNewt/pyshark#241]
What should the capture filter for GSMMAP packets?

**Comment by techwizardg** [comment]
What should the capture filter be for GSM MAP Packets when using pyshark?

**Comment by AlbertWigmore** [comment]
Problem is probably fixed by now but just for completeness so the issue can be closed.

To filter out GSM MAP packets you can specify the following display filter

```python
import pyshark
cap = pyshark.LiveCapture(interfaces='eth0', display_filter='gsm_map')
```
