### ISSUE TITLE
continue live capture automatically when interface is restarted

### ISSUE THREAD

**Issue by moham96** [KimiNewt/pyshark#242]
Hi,
when I'm running live capture and then the interface is turned of and on again(restarted from the os or the cable is removed and inserted again) the live capture does not continue and i have to restart the script so how can I make the live capture continue when interface is available again ( or at least it should throw an exception when it can't capture anymore so i can run the code in a while true loop)

**Comment by mtis88** [comment]
Did you find solution for this?

**Comment by moham96** [comment]
@mtis88 Well I moved to use scapy instead of pyshark, but anyway I used a mechanism that can help you, for me I used this on an openwrt router which has a process manager that dispatches event when interface is up or down see [hotplug](https://openwrt.org/docs/guide-user/base-system/hotplug_lede) So I capture the event and when the event is indicating the interface is down it kills the scapy(pyshark in your case) and when the event indicates the interface is up it runs the script again. there exist similar solution for most distros, on a distro that uses NetworkManager google the "network manager dispatcher", on a system that uses ifupdown tools to manage network there are [post-up and post-down commands to be used in the /etc/network/interfaces](https://manpages.debian.org/jessie/ifupdown/interfaces.5.en.html)

**Comment by mtis88** [comment]
That's interesting because I am moving from scapy to pyshark! I am using CentOS so the NetworkManager-dispatcher is a good suggestion - thanks.
