### ISSUE TITLE
<LiveCapture (0 packets)> when sniffing with pyshark in Windows 10

### ISSUE THREAD

**Issue by SofiaArancibia** [KimiNewt/pyshark#244]
I'm using pyshark 0.3.6.2 in a windows 10 64 bits machine (also python 2.7, 64 bits), and no results at all..

The script I'm using is:

` cap = pyshark.LiveCapture(interface = '935D8187-5D39-4976-9340-67B5CC745E80') `
` cap.sniff(timeout=50)`

where 935D8187-5D39-4976-9340-67B5CC745E80 is the name of my Wi-Fi interface

  
Also, sometimes, I get the error `UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 40: ordinal not in range(128)` and don't know why...

**Comment by Gurgel69** [comment]
@SofiaArancibia Did you find a solution?
