### ISSUE TITLE
Can't run .exe with pyshark imported

### ISSUE THREAD

**Issue by Meshi28** [KimiNewt/pyshark#245]
Hi,

I've been using pyshark to build a program that parses a .pcap file and then returns certain information. The script itself all works fine and when running from IDLE it does as it's supposed to. However now I want to freeze the code into an .exe so I can distrubute it to a few workstations who don't have Python installed. 

I'm using pyinstaller to create the .exe (works with my other projects) which puts it all together, however when running it I get the below. 

Traceback (most recent call last):
  File "Networking.py", line 41, in <module>
    udp1 = udp()
  File "Networking.py", line 17, in udp
    for pkts in cap:
  File "site-packages\pyshark\capture\capture.py", line 208, in _packets_from_tshark_sync
  File "site-packages\trollius\base_events.py", line 300, in run_until_complete
  File "site-packages\trollius\futures.py", line 287, in result
  File "site-packages\trollius\tasks.py", line 255, in _step
  File "site-packages\pyshark\capture\capture.py", line 372, in _get_tshark_process
  File "site-packages\pyshark\capture\capture.py", line 355, in _get_tshark_path
  File "site-packages\pyshark\tshark\tshark.py", line 69, in get_process_path
  File "site-packages\pyshark\config.py", line 8, in get_config
  File "site-packages\py\_vendored_packages\apipkg.py", line 148, in __makeattr
  File "site-packages\py\_vendored_packages\apipkg.py", line 69, in importobj
ModuleNotFoundError: No module named 'py._vendored_packages.iniconfig'
[7384] Failed to execute script Networking

Seems to not be seeing the .py files in site-packages\py\ and wonder if anyone's run into this problem before or can advise what I might be able to do to resolve it. I've imported specific .py files from the 'py' directory and this will get me further but it will then ask for another module in a subfolder of 'py' e.g. '._path.local'

I've tested just using a one function code to read a capture with only pyshark imported and get the same issue. I've reinstalled all of Python 32 bit with the modules, tried earlier versions of pyshark. Main machine is Windows 10 however I've also tried from a WIndows 7 machine and a fresh WIndows 7 VM. 

Thanks for any suggestions,

**Comment by Meshi28** [comment]
Hi, yes I managed to work around it but it wasn't clean. I had to add the below into my script

`from py import _std
from py import __metainfo
from py import _apipkg
from py import _builtin
from py import _error
from py import _iniconfig
from py import _xmlgen
from py import test
from py import __pycache__
from py import _code
from py import _io
from py import _log
from py import _path
from py import _process
from py import _path
from py import _vendored_packages`

And then also in my .spec file

`             datas=[ ( 'C:/Program Files (x86)/Python36-32/Lib/site-packages/pyshark/config.ini', '.' )],
             hiddenimports=['py._path.local', 'py._vendored_packages.iniconfig', 'pyshark.config'],`


I don't think this is the best solution but it worked and I found no other way around it, hope it helps you.

**Comment by amon-pad** [comment]
First of all, thank you for such a fast reply. Second, yes, it's kind of ugly, but it works, so thank you again.

**Comment by Avishay116** [comment]
Thanks @Meshi28  I tried your solution and it didn't work at first.
My update is -
1. I didn't have to  add the "from py import..." lines to my script.
2. I got this error 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aaaa\\AppData\\Local\\Temp\\_MEI170842\\pyshark\\config.ini'`

To make this work I had to change the spec line, from 
`datas=[ ( 'C:/Program Files (x86)/Python36-32/Lib/site-packages/pyshark/config.ini', '.' )]`
to
`datas=[ ( 'C:/Program Files (x86)/Python36-32/Lib/site-packages/pyshark/config.ini', '.\pyshark' )]`

Thanks again (:

**Comment by dmmc12** [comment]
I came across the above two errors as-well using Ubuntu 18.04, where I attempted to create an executable file of the app I wrote with pyinstaller.

If anyone else comes across this issue on **Ubuntu**, thanks to the above people, I was able to get it working with the following:

Name: pyshark
Version: 0.4.2.2

>pyinstaller name_of_script.py

Once the build is complete, you need to customize the .spec file that is created with the below.

datas=[('/home/username/.local/lib/python3.6/site-packages/pyshark/config.ini', './pyshark')],
hiddenimports=['py._path.local', 'py._vendored_packages.iniconfig', 'pyshark.config']

Then run the pyinstaller again but on the .spec file instead.

>pyinstaller name_of_spec.spec

**Comment by mdfaizali390** [comment]
Both the above solutions  are not working for me. I am building on windows 7. Getting this error:

ModuleNotFoundError: No module named 'py._path.local'

Please help. Need to resolve this badly !!!!

**Comment by mdfaizali390** [comment]
For future googlers if you encounter this error. These are the steps to solve this issue (not at all clean but works)

First add these imports in your source code:

`from py import _std
from py import __metainfo
from py import _builtin
from py import _error
from py import _xmlgen
from py import _code
from py import _io
from py import _log
from py import _path
from py import _process
from py import _path
from py import _vendored_packages`

Then edit the spec file and add 
`hiddenimports=['py._path.local','py._vendored_packages.iniconfig','pyshark.config']`

copy config.ini (will be inside pyshark directory) to dist/<project-name>/pyshark/config.ini

**Comment by SaiMun92** [comment]
it dosen't work!!! Please help oh young one

**Comment by SaiMun92** [comment]
I love you

**Comment by Forward-Ky** [comment]
I love you too

**Comment by RHQ-Rusty** [comment]
I'm still unable to get this working; could I get some further explanations as to why this is incapable of freezing into a binary executable by itself? Still no .exe for me! I've tried the workarounds as listed above and none seem to yield any satisfactory results.
@Meshi28 @mdfaizali390 @dmmc12 @Avishay116

**Comment by zzzpeifeng** [comment]
I face to same situation~

**Comment by zzzpeifeng** [comment]
I 've been use pyshark + pyqt5 create a program to parse cap file, but when I use pyinstaller build, the pyqt5 windows is normal, but when call apply_on_packets , it will occur error ,

code:

```
    def read_file(self):
        package_obj = pyshark.FileCapture(self.file_path)
        package_obj.apply_on_packets(self.analyse)
```

output:

```
QLayout: Attempting to add QLayout "" to MainWindows "", which already has a layout
Traceback (most recent call last):
  File "gui\main.py", line 65, in on_click_parse_cap_file
  File "utils\data_handle.py", line 50, in get_result_data
  File "utils\data_handle.py", line 47, in read_file
  File "pyshark\capture\capture.py", line 267, in apply_on_packets
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "pyshark\capture\capture.py", line 276, in packets_from_tshark
  File "pyshark\capture\capture.py", line 388, in _get_tshark_process
  File "pyshark\capture\capture.py", line 364, in _get_tshark_path
  File "pyshark\tshark\tshark.py", line 29, in get_process_path
  File "pyshark\config.py", line 11, in get_config
  File "py\_vendored_packages\apipkg.py", line 148, in __makeattr
  File "py\_vendored_packages\apipkg.py", line 69, in importobj
ModuleNotFoundError: No module named 'py._vendored_packages.iniconfig'
```



and I try fbs build too, the program can run normal when "fbs run" , but when I use "fbs freeze" packaging, it will occur same issue~



I have try above method， but isn't work  ：(
[https://github.com/KimiNewt/pyshark/issues/245](url)

Help~

**Comment by guchengxi1994** [comment]
hiddenimports=['pyshark','py._path.local','py._vendored_packages.iniconfig', 'pyshark.config']   works

**Comment by nkhzrd** [comment]
https://github.com/nkhzrd/PyShark-Exe-Build-Guide 
full guide for exe

**Comment by LpCodes** [comment]
Have submitted hook for the same on pyinstaller should work with next rel without settings
