### ISSUE TITLE
about dns package, parse result not contain all fields

### ISSUE THREAD

**Issue by sdl9i2** [KimiNewt/pyshark#246]
tshark  output  dns layer :
{'Answers': {'version.bind: type TXT, class CH': {'dns.resp.class': '0x00000003',
   'dns.resp.len': '32',
   'dns.resp.name': 'version.bind',
   'dns.resp.ttl': '0',
   'dns.resp.type': '16',
   'dns.txt': '9.6.2-P2-RedHat-9.6.2-5.P2.fc12',
   'dns.txt.length': '31'}},
 'Authoritative nameservers': {'version.bind: type NS, class CH, ns version.bind': {'dns.ns': 'version.bind',
   'dns.resp.class': '0x00000003',
   'dns.resp.len': '2',
   'dns.resp.name': 'version.bind',
   'dns.resp.ttl': '0',
   'dns.resp.type': '2'}},
 'Queries': {'version.bind: type TXT, class CH': {'dns.count.labels': '2',
   'dns.qry.class': '0x00000003',
   'dns.qry.name': 'version.bind',
   'dns.qry.name.len': '12',
   'dns.qry.type': '16'}},
 'dns.count.add_rr': '0',
 'dns.count.answers': '1',
 'dns.count.auth_rr': '1',
 'dns.count.queries': '1',
 'dns.flags': '0x00008500',
 'dns.flags_tree': {'dns.flags.authenticated': '0',
  'dns.flags.authoritative': '1',
  'dns.flags.checkdisable': '0',
  'dns.flags.opcode': '0',
  'dns.flags.rcode': '0',
  'dns.flags.recavail': '0',
  'dns.flags.recdesired': '1',
  'dns.flags.response': '1',
  'dns.flags.truncated': '0',
  'dns.flags.z': '0'},
 'dns.id': '0x00000006'}

pyshak parse result not contain all fields ,like :Answers, Queries,  Authoritative nameservers

**Comment by KimiNewt** [comment]
If you use the `use_json=True`, you'll get the same structure as a tshark JSON. Otherwise, you'll get the same structure as a tshark PDML (XML), so you can check that to figure out where you can get your values.

**Comment by niu-b-long** [comment]
why JsonLayer.field_names filter some fields, cause func pretty_print not print all fields? I think this my questions, thanks.
