### ISSUE TITLE
First Packet is Discarded 

### ISSUE THREAD

**Issue by KartikKillawala** [KimiNewt/pyshark#250]
I am new to pyshark and was working on one trace file where I observed that when the param only_summaries is set to True, it discards the first packet and stores only the second packet onwards. How can we get access to the first packet then?

**Comment by laixintao** [comment]
@KartikKillawala Same issue here. When set`only_summaries=True` will lost first packet.

I am trying to fix this. @KimiNewt Did you still maintain this repo?

**Comment by bishop527** [comment]
I do NOT have only_summaries=True and I'm also losing the first packet.

**Comment by bishop527** [comment]
discovered that if I use only_summaries=False (prior I didn't use only_summaries at all), i do not loose the first packet.

**Comment by laixintao** [comment]
I fix this by https://github.com/KimiNewt/pyshark/pull/255 , you can refer.

**Comment by bishop527** [comment]
#255 fails the checks for python 3.6, which is what I'm using.
Regardless, I don't think a fix is needed. All you need to do is add only_summaries=False to LiveCapture
