### ISSUE TITLE
How is the Python3 status now?

### ISSUE THREAD

**Issue by laixintao** [KimiNewt/pyshark#251]
Hi, @KimiNewt , thanks for your work!

I work on Python3. I have forked your repo and wanted to merge python3 branch into master. but looks like there are few conflicts here: https://github.com/laixintao/pyshark/pull/1/files

Should I use Python3 branch or master?

**Comment by KimiNewt** [comment]
The normal master can and does run on python3 (I use python3 myself).

The branch simply makes the code simpler and drops support for python2. The reason I didn't merge it is that sadly, the majority of the users still use python2. When python2 usage drops further I will merge it. Thank you for the update of the branch, I can use it when I do finally merge it.

**Comment by laixintao** [comment]
Hi, thanks!

I want to do more works on python3.5+(like fix this https://github.com/KimiNewt/pyshark/issues/250), and use it via `pip install`, so is that of for you if I maintain a fork of python3 and upload that fork to pypi (https://pypi.org/project/py3shark/) ?

I kept author and license of course.

![image](https://user-images.githubusercontent.com/9675939/36796050-9101fcb2-1cdf-11e8-86b3-bc4aa69a2d51.png)
