### ISSUE TITLE
LiveCapture seems to buffer captured packets

### ISSUE THREAD

**Issue by bishop527** [KimiNewt/pyshark#254]
When using LiveCapture it appears that the packets are buffered before being processed and I'm trying to determine if there's a way to change the size of the buffer. 
Here's my code
cap = pyshark.LiveCapture(interface='eth0', display_filter=FILTER)
packet_iterator = cap.sniff__continously
count = 0
for packet in packet_iterator():
    count += 1
    print(count)

pyshark should capture a new packet every 10 seconds. But what I'm seeing is my counter incrementing in bursts of about 22. Meaning approximately every 3 minutes after starting I'll see 1 through 22. In another 3 minutes, 23 through 44, etc.

I tried overriding the DEFAULT_BATCH_SIZE parameter but that crashed tshark.

Any suggestions?

**Comment by wsw70** [comment]
I have the same issue. I was wondering if this is not related to tshark trying to resolve the name (just a wild guess)

**Comment by bishop527** [comment]
bump

**Comment by ZackAlfakir** [comment]
This is a feature of libpcap and not with pyshark. Libpcap will buffer a certain amount of packets in order to increase speed and reduce drop rate.

**Comment by mtis88** [comment]
I have seen this exact behaviour - exactly 23 packets must be received before the callback is invoked. I was using CentOS 7 with wireshark-1.10.14-14 from the main repo. I then tried wireshark 2.6.2 (from [here](https://www.1310nm.net/coherentlight/2018/07/19/wireshark-2-6-2-available-repository-centos-7/) and it fixed the issue. The same version of libpcap was used with both.
