### ISSUE TITLE
pyshark -> scapy interface using raw data and #188

### ISSUE THREAD

**Issue by ZackAlfakir** [KimiNewt/pyshark#257]
Are you aware of any method of converting a pyshark packet into a scapy packet? I have software built around pyshark but I need some of scapy's features. 

I looked into #188 and put that on a fork, but I was hoping to find a way to get the binary out. It instead seems to just have a \<LAYER>_RAW duplicated in each packet:

```
In [22]: p.layers
Out[22]:
[<RADIOTAP Layer>,
 <WLAN_RADIO Layer>,
 <WLAN Layer>,
 <RADIOTAP_RAW Layer>,
 <WLAN_MGT_RAW Layer>,
 <WLAN_MGT Layer>,
 <FRAME_RAW Layer>,
 <WLAN_RAW Layer>]
```

I need some way of getting the bytes so I can dump them into the scapy constructor. I am willing to work on this PR if advice is given.

**Comment by KimiNewt** [comment]
You can use `packet.get_raw_packet()` and feed that into scapy. Note that it will be super inefficient.

**Comment by TheBigFudge** [comment]
> You can use `packet.get_raw_packet()` and feed that into scapy. Note that it will be super inefficient.
is there a possibility to use the packet.get_raw_packet() without the use of json. I need to pass the Pyshark Paket to the scapy constructor. Or are there any other options to do this?

**Comment by TheBigFudge** [comment]
> You can use `packet.get_raw_packet()` and feed that into scapy. Note that it will be super inefficient.

is there a possibility to use the packet.get_raw_packet() without the use of json. I need to pass the Pyshark Paket to the scapy constructor. Or are there any other options to do this?
