### ISSUE TITLE
Pyshark stops Pycharm debugger from working

### ISSUE THREAD

**Issue by RichParker734** [KimiNewt/pyshark#263]
I am on a Windows 10 machine, using Python 2.7.11 (32Bit), PyShark, and Pycharm as an IDE.  If I include pyshark, place a breakpoint and run the program in the debugger, it will break on the breakpoint.  but try to step after that, it never returns.  This only happens with PyShark for me.

ex: 
import pyshark
a = 1
print a

set breakpoint on a=1, debug program.  It stops at a=1.  Press 'step' and it never returns.  Remove the import pyshark, and it works as expected.   Also if I use pdb instead, it steps fine even with the include, so looks like something in the import is stalling the PyCharm debugger.

**Comment by zwilcox** [comment]
I know it's not a solution, but the debugger in Eclipses's PyDev works just fine.

**Comment by RichParker734** [comment]
It is at least another option, Thanks!

**Comment by KimiNewt** [comment]
Works for me. Can you retry on the latest version?

**Comment by RichParker734** [comment]
I am having difficulty with this.  I am running python 2.7.11 with pyshark version 0.3.7.11 (Win 10) on one computer and the other was python 2.7.13 that did not have pyshark installed (also Win10).  
On the machine without pyshark installed i uninstalled pycharm
Installed latest pycharm community edition (2018.1.4) 
cd'ed to c:\\python27\Scripts
pip install pyshark
[pyshark installed]
open command prompt
python
import pyshark
error:
  "Your version of Python is unsupported. Pyshark requires Python >= 3.5 & Wireshark >= 2.2.0.  Please upgrade or use pyshark-legacy, or pyshark version 0.3.8"

So something changed between 0.3.7.11 that causes pip to install a non working pyshark version ?

I can't update to python 3.5 for a number of reasons, so how do I get it to install 0.3.8 properly?

Thanks!
RichP

**Comment by RichParker734** [comment]
Ok I tried it with pyshark 0.3.8 and Pycharm Community Edition 2018.1.4 and still stalls while stepping (same program above, breaking on the first line then step over)
