### ISSUE TITLE
DATA layer

### ISSUE THREAD

**Issue by fazega** [KimiNewt/pyshark#264]
Why does the DATA layer have a special treatment in layer.py ?
If I do a tshark capture with -V I can see all raw data of the packets. Why can't pyshark get this data ?

**Comment by ZackAlfakir** [comment]
In the Capture constructor, set `include_raw=True`

**Comment by heyang9** [comment]
The data in application layer cannot be displayed completely, how can I solve this problem..

**Comment by fazega** [comment]
I ended up using this code :
```python
                if('DATA' in packet and not 'SSL' in packet):
                    if("tcp.reassembled.data" in packet.data._all_fields):
                        raw = packet.data._all_fields["tcp.reassembled.data"].replace(":", "")
                    if("data.text" in packet.data._all_fields):
                        raw = packet.data._all_fields["data.text"]`

**Comment by KimiNewt** [comment]
Try using the new `packet.get_raw_packet()` method.

**Comment by jiamo** [comment]
But after use `        include_raw=True, use_json=True`
we don't have `packet.dns` anymore. How can we have both `dns or other thing` and `get_raw_packet() with data`

**Comment by jiamo** [comment]
after use `        include_raw=True, use_json=True`. The data layer such `packet.dns` don't have field such like `a`
