### ISSUE TITLE
help with pyshark raw data

### ISSUE THREAD

**Issue by shindoga** [KimiNewt/pyshark#274]
i understood that pyshark can get u raw (binary/hex dump) data about packets.
1. how can i get raw data for each layer in packet?. (for HTTP and highest_layer i can print but it doesn't actually give the data)
2. what other python sniffing packet analyzing tools can i use for getting this raw data for each layer in the packet? (scapy is not working very good)

**Comment by shindoga** [comment]
i understand it has something to do with raw mode or maybe get_raw_value
but i haven't managed to get an actual code that works or maybe a good documentation

**Comment by ZackAlfakir** [comment]
include_raw=True in the capture constructor. As shown here: https://github.com/KimiNewt/pyshark/pull/258
