### ISSUE TITLE
How to use multiple FileCapture Object?

### ISSUE THREAD

**Issue by Peter654q** [KimiNewt/pyshark#277]
cap = pyshark.FileCapture('test.pcapng', display_filter = 'tcp')
    cap2 = pyshark.FileCapture('test2.pcapng', display_filter = 'udp')
    print len([packet for packet in cap])
    print len([packet for packet in cap2])

I'm trying to use the above code, but I found that if I use the other FileCapture object (like cap2)
the previous one (cap) can not work.
Can someone help me to solve this problem?

**Comment by ZackAlfakir** [comment]
Try modifying your code to:

```
print len(cap)
print len(cap2)
```

Might be just too much memory usage with you holding 4 pcaps (2 are duplicated when you make the list via list comprehension).

**Comment by Peter654q** [comment]
Thanks for your reply!
I will keep trying.
