### ISSUE TITLE
pyshark using 'use_json=Ture, include_raw=True' option can't loop over a whole pcap file

### ISSUE THREAD

**Issue by JackLiar** [KimiNewt/pyshark#283]
I use 'a' because just this single file have this problem.(Haven't found other pcap files to have the same problem)

[test.zip](https://github.com/KimiNewt/pyshark/files/2243977/test.zip)  (it's an open source pcap file, no personal information)

the code I used are quite simple (just to show the scenario):

```python
import pyshark

fname = 'youtube2.pcap'
pkts = pyshark.FileCapture(fname)
print(pkts.get_parameters())
count = 0
for p in pkts:
    count += 1
print(count)

pkts = pyshark.FileCapture(fname, use_json=True, include_raw=True)
print(pkts.get_parameters())
count = 0
for p in pkts:
    count += 1
print(count)
```

the upper block of the loop gives a count of 12738, which is exactly the amount of pkts in the pcap file

while the lower block of the loop gives a count of 2095, apparently not the correct answer

I  found this problem on this environment:
> macOS 10.13.6
> 
> python 3.6.5
> 
> pyshark v0.38
> 
> TShark (Wireshark) 2.6.2 (v2.6.2-0-g1b3cedbc)

and test it on a environment like this:
> Ubuntu 16.04 LTS
> 
> python 3.6.5
> 
> pyshark v0.38
> 
> TShark (Wireshark) 2.2.6

and both env have this issue.

I also tested another 3 pacp files, and they are fine.

The same problem also happens on **apply_on_packets** method too.

So can anyone give a hint about where the problem may really lie on?

**Comment by ZackAlfakir** [comment]
So considering that it only happens on some pcap files, we need to know the differences between them. Are they all `.pcap` or are some of them `.pcapng`?

Do any of them have malformed packets?

**Comment by JackWzh** [comment]
@ZackAlfakir no matter .pcap or .pcapng this issue happens

I tried just using tshark using the same parameters, nothing wrong happened.

I guess maybe it's something wrong in the pyshark processing code, for example the coroutine processing the stream?

I don't have experience with malformed packets, so I don't know whether there are some malformed pkts in the .pcap file, sry......

**Comment by rezo1134** [comment]
I wonder if it has to do with the use_json =True part. The docs say that it doesn’t show full data... I wonder if that means it cuts out data. Also, have you found that iterating through those objects in order to count takes a long time? What I learned recently is you can call list(pkts) and it makes iterations go a bit faster, and allows for you to accurately call len(pkts)

**Comment by KimiNewt** [comment]
@rezo1134 it shouldn't cut out data. If you call `list(pkts)`, the capture file loads all the packets to memory. This will indeed cause iterations to go faster but may consume lots of RAM.

**Comment by KimiNewt** [comment]
As for the issue, this appears to be a problem with tshark. Running: `tshark -r youtube2.pcap -T json -x` produces 2095 packets like `pyshark`.
On Wireshark 3.0.1 it also prints out the error: `ERROR:C:\buildbot\wireshark\wireshark-3.0-64\windows-2016-x64\build\epan\print.c:1716:get_field_data: code should not be reached`.

I suggest you open this issue on the wireshark repo.

**Comment by DCMMC** [comment]
Same issue with tshark 2.6.10@ubuntu 18.04.
On tshark 3.2.5 build by myself, this bug disappeared.
It's useful that presenting some warns to users when using old tshark version.
