### ISSUE TITLE
Using apply_on_packets I can't seem to kill the process

### ISSUE THREAD

**Issue by CordThomas** [KimiNewt/pyshark#285]
A naive question, not understanding how to kill callback processes.  I have a simple script that i started as a cron request one time to have it unattended.  In it, I used apply_on_packets with a callback function to the LiveCapture method.  How do i kill this?  Every time i try to kill the process it spawns another.

In general, what would be the best way to run LiveCapture as a daemon to continuously capture packets for data traversing my LAN?   This is my script:  https://github.com/CordThomas/carrier_hvac/blob/master/hvac_data_collection.py

**Comment by tdwoods** [comment]
I'm having the same issue. I have tried `raise SystemExit` and `raise pyshark.StopCapture()` within my packetHandler and catching it in main without success.

**Comment by tdwoods** [comment]
![screen shot 2018-08-07 at 12 36 33 pm](https://user-images.githubusercontent.com/23199494/43789714-9b727dca-9a3e-11e8-9faf-198c338fd448.png)

If you're trying to stop the function once the timeout period has ended, import concurrent.futures and then add a try and except block to catch the TimeoutError then just call sys.exit() (or your code that you want to execute at stop time).

**Comment by mtis88** [comment]
I am calling capture.close(), which causes a RuntimeException with the
error “event loop already running”, but it is the desired effect, dumpcap
and tshark are closed cleanly.

I was actually going to raise an issue to ask if this method was safe to
use as I haven’t seen it mentioned anywhere?

**Comment by CordThomas** [comment]
mtis88 -

I think i am missing something.   I started my python script and it crashed
at some point (well, July 15 to be exact).

I now have several dumpcap and tshark processes running along with my .py
script.  Every time i try to kill the processes, new ones spawn.

I tried creating a new script thinking this is what you were suggesting but
it just threw an error.

import pyshark
import configparser, os
config = configparser.ConfigParser()
config.read(os.path.expanduser('~/params.py'))

capture = pyshark.LiveCapture(interface = 'br0',
               bpf_filter = config['HVAC']['bpf_filter'],
               display_filter = config['HVAC']['display_filter'])

capture.close()

error:

Exception ignored in: <bound method BaseEventLoop.__del__ of
<_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 510, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 65, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 146, in
remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a
callable object

**Comment by mtis88** [comment]
Where is your apply_on_packets?

**Comment by CordThomas** [comment]
Okay, so I needed that as well.  I had thought i would just use the close()
on the capture instance.   Thanks - will try tonight.

**Comment by CordThomas** [comment]
I guess I really don't understand this.  I am trying to kill an existing script.  The script i have recovers even after system restart.

I tried adding the apply_on_packets to my kill script

**Comment by irfancnk** [comment]
Is there any solution on this? Project is dead?
