### ISSUE TITLE
Want to filter probe requests to only telephones

### ISSUE THREAD

**Issue by tdwoods** [KimiNewt/pyshark#286]
I'm looking for a way to distinguish the probe requests of mobile phones from the rest of the probe requests gathered by pyshark. In my packet handler I want to add some code to distinguish the packets but I am finding it difficult to locate a packet field that can help me. 

I know I could do it by vendor/OUI but I would still get laptops or computers. Is there any way to solely get mobile phones?

**Comment by KimiNewt** [comment]
This isn't really a pyshark problem, just a general networking question.

As a personal advice, I would suggest looking at Vendors that only make mobile phones, HTTP User-Agents and DHCP Vendor Class.

You can ask further questions on stackexchange or similar websites.
