### ISSUE TITLE
Duplicate field names in packet layer

### ISSUE THREAD

**Issue by AlbertWigmore** [KimiNewt/pyshark#287]
Currently if there is a duplicate field name within a layer in the packet only one shows up within the layer object.

This problem occured when looking at something like GSM SMS where tshark reassembles the message fragments together in the last fragment. 

```xml
<field name="gsm_sms.sms_text" showname="SMS text: message 1" size="" pos="" show="" value=""/>
<field name="gsm_sms.sms_text" showname="SMS text: message 2" size="" pos="" show="" value=""/>
<field name="gsm_sms.sms_text" showname="SMS text: message 3" size="" pos="" show="" value=""/>
```
(I'm unable to share the actual XML I have in full so I've just written out the bit where the problem arises following the same structure but removing data)

I have managed to solve it by specifying tshark not to reassemble GSM_SMS packets using the argument: 
```python
pyshark.FileCapture(
    'file.pcap',
    override_prefs={'gsm_sms.reassemble': 'false'},
)
```
Is it worth changing the behaviour of the code to deal with issues like this or leave it up to the user to specify extra arguments to get around it. Not sure whether there are any cases where this can happen where extra arguments wont solve the issue.

**Comment by KimiNewt** [comment]
There is a way to go around it. In JSON mode it will just return a list, in XML mode the field has a `all_fields` member that returns all the fields with the same name, or `alternative_fields` which returns all the fields with that name besides that field. 

I'm pretty sure this will work in your case. I think that the way it works in JSON-mode is better, but I didn't want to break compatibility. 

Please reopen if this doesn't solve your problem.

**Comment by eswarthammana** [comment]
Hi @KimiNewt thanks for wonder full support.  I am facing duplicate field names issue.

`>>> for p in cap:
	if p.highest_layer == 'DATA':
		print(p.data.field_names)

	
['data', 'data', 'len']
['data', 'data', 'len']
['data', 'data', 'len']
['data', 'data', 'len']
['data', 'data', 'len']`

![Wireshark screen shot](https://user-images.githubusercontent.com/23114153/66469009-b3960400-eaa4-11e9-823f-0fe10ee94828.png)

I used frozenset to avoid the issue temporarily
