### ISSUE TITLE
(Very minor) typo in capture.py, affecting debug message

### ISSUE THREAD

**Issue by Geoff99** [KimiNewt/pyshark#289]
Hi @KimiNewt 

First, many thanks for this project.  I'm still in the early stages of learning how to use it, but mightily impressed by what I've seen so far.

I believe there is a minor typo in the current line 375 of capture.py.

It currently reads
```
self._log.debug('%s subprocess created', process_name)
```

I think it should be
```
self._log.debug('%s subprocess created' % process_name)
```

**Comment by KimiNewt** [comment]
First off, thank you for your kind words.

The log issue is because of a difference between the standard logging interface and logbook's. I think this would be a good time to remove logbook as we don't really use many of its features. I'll fix it soon.
