### ISSUE TITLE
KeyError: 'Packet of index 0 does not exist in capture'

### ISSUE THREAD

**Issue by leonisawesome** [KimiNewt/pyshark#292]
Latest Mac OS (10.13.6)
Latest Anaconda (4.5.11) with all patches installed 

Packet captures open in wireshark and scapy no problem.  They come from a security researcher.  I have tested 2 files now.

Here is the snippet below

import pyshark
cap = pyshark.FileCapture("test.pcap")
<FileCapture test.pcap>
print (cap[0])

KeyError: 'Packet of index 0 does not exist in capture'

len(cap)
0

Appears the files are not being read in properly

**Comment by leonisawesome** [comment]
This is apparently a bug in how the library interacts with jupyter.  Here are two screenshots of the exact same code.

http://prntscr.com/kp9gfa that is jupyter.

http://prntscr.com/kp9gjz here is pycharm

**Comment by ravirajshankar** [comment]
Hi, 

I am facing exactly same issue with wireshark version 2.6.2 on oracle linux 8. One interesting point is that with same wireshark version 2.6.2 over windows 10 I am able to read all the packet.  Can you please me to resolve this issue on Oracle 8 ?
~ Ravi

**Comment by Keno0** [comment]
Hi,

Is it fixed? I still have this problem. 

Regards,
Keno0
