### ISSUE TITLE
Suggestion / Query : LiveCapture and (avoiding) the delay while the dumpcap input buffer fills

### ISSUE THREAD

**Issue by Geoff99** [KimiNewt/pyshark#296]
### LiveCapture and (avoiding) the delay while the dumpcap input buffer fills

Hi @KimiNewt ,

I am learning lots by reading through the source code of this impressive project,
though I still have a way to go before I really understand it (and `asyncio`) properly.
Many thanks indeed for all your work on it ! 

This is a question about the design of LiveCapture / suggestion for an improvement (see the proposed `LiveCaptureNow` subclass of `LiveCapture` listed below), 
which might help with issues #278 and #254.  Not urgent (for me, as I have an
approach that seems to work) so feel free to ignore, and close this issue if 
there are other priorities that require your attention.

### Background

I am using pyshark to listen to an IoT sensor, which transmits small (only 98 bytes of payload)
TCP messages infrequently (every 5 minutes).  I use a bpf_filter setting to 
restrict attention to only the IoT sensor's transmissions (ie I filter out other 
network traffic as soon as possible). 

`LiveCapture` uses two subprocesses,

* `dumpcap` extracts relevant transmissions and then sends them, via a pipe to 
* `tshark`.

As explained in #278, `dumpcap` waits until its input buffer is full, before 
flushing the consolidated traffic to `tshark'.  

In my application, that results in a wait of about an hour and a half while 
traffic accumulates in the `dumpcap` input buffer - at which point I receive 
upwards of 20 sensor readings in a few seconds - before another wait of an hour 
and a half for my next batch of data.

(Aside, it took me a while before I realised what was happening, 
initially I thought I was failing to capture any packets at all).

In practice, I would rather see individual IoT sensor messages every 5 
minutes, as they are sent.

I have "solved" my problem by creating a subclass of `LiveCapture`, 
which I have called `LiveCaptureNow`.  It works by eliminating the `dumpcap` process,
and using only `tshark` (internally `tshark` appears to run its own `dumpcap` 
subprocess, but `tshark` seems able to instruct its `dumpcap` subprocess to operate 
in unbuffered mode.)  See below for the code.

### The design question about LiveCapture

Is there some underlying reason that I am missing that makes it advisable to 
separate the `dumpcap` and `tshark` steps the way that pyshark currently does?
For example, is my scenario (small infrequent packets on a 
relatively quiet network) atypical, and what works for me may be horribly 
inefficient in other settings? Or something else entirely (perhaps related to 
`asyncio` which I am still working to understand) ?

### The suggested improvement

Perhaps (an improved) version of `LiveCaptureNow`, with suitable warnings (based 
on the answer to the question above) might be added to pyshark for use in 
scenarios like the mine?

### live_capture_now.py

```
from pyshark.capture.live_capture import LiveCapture

import asyncio

class LiveCaptureNow(LiveCapture):
    """
    Live capture on a network interface using only tshark, not dumpcap.
    
    So as to avoid the (long) delays while the dumpcap input buffer fills when 
    listening for small infrequent packets on a quiet network.
    """ 

    # Just default to LiveCapture.__init__

    def get_parameters(self, packet_count=None):
        """
        Returns the special tshark parameters to be used according to the configuration of this class.
        """

        # Use super(LiveCapture ...) NOT super(LiveCaptureNow ...), because that would use dumpcap,
        # which is what I am trying to avoid!
        params = super(LiveCapture, self).get_parameters(packet_count=packet_count)

        # Don't report packet counts, use pcap format
        params += ["-q", "-P"]
        if self.bpf_filter:
            params += ['-f', self.bpf_filter]
        if self.monitor_mode:
            params += ['-I']
        for interface in self.interfaces:
            params += ['-i', interface]
        # Send view of decoded output to STDOUT even if -w option is capturing raw pcap output as well
        params += ['-V']
        return params

    async def _get_tshark_process(self, packet_count=None, stdin=None):
        tshark = await super(LiveCapture, self)._get_tshark_process(packet_count=packet_count, stdin=stdin)
        return tshark
```
### My setup

In case it is relevant:

I am using a Raspberry Pi model 3B, with Raspbian stretch as the operating system.

I am using `pyshark 0.4.1`, downloaded using pip3.
and
`tshark 2.2.6`, downloaded via apt-get

**Comment by mtis88** [comment]
1. I too have observed the behaviour you describe in that there is lag before the packets are visible in pyshark (#254). This was fixed for me by using a more recent version of tshark.

2. The reason that LiveCapture spawns it's own dumpcap process, the output from which is piped to tshark, is that if you let tshark manage it's own dumpcap process the output is written to a file in /tmp, which is then read by tshark. This file will grow forever.

**Comment by Geoff99** [comment]
### Compiling wireshark from source, for and on a Raspberry Pi

As pointed out in #254, when using `LiveCapture`, the best way of avoiding a delay while the `dumpcap` sub-process buffer fills, is to upgrade to a more recent version of `wireshark` (and `tshark`, `dumpcap` and so forth).

However the link given in #254 is to a CentOS 7 repository, which as far as I could find, only contained binaries for intel type processors, not the armV7 CPU which I understand the Raspberry Pi uses.  My searches to find precompiled binaries for version 2.6 of `wireshark` for armV7 processor elsewhere were unsuccessful, so with some trepidation, I set about trying to compile `wireshark` 2.6.4 from source, on the Raspberry Pi.

It was quite a time consuming process (the complete build took quite a number of hours, during which the Raspberry Pi became **completely** unresponsive), but in the end it succeeded.  There were a few trips and traps along the way (for a novice like me anyway), so I've written a (rather verbose) tutorial-to-myself in case anyone else needs to follow this route.

[Compiling wireshark 2.6.4 from source on a Raspberry Pi](https://gist.github.com/Geoff99/fd7d1e68134cdca5742fa54821f79212)

I've written all this up before I forget any of the details.  My next step will be to confirm that this updated version of `tshark` actually does resolve the `LiveCapture` delay issue for me.  (I expect it will, but safest to check).  After which I'll update this issue again.

**Comment by Geoff99** [comment]
#### LiveCapture delay avoided by using more up to date version (2.6.4) of tshark

Just a final note to record that, as advised by @mtis88 (thanks), installing a more up to date version of `tshark`  onto my Raspberry Pi **did** indeed remove the long delay (in my case ~1.5 hours!) that I used to experience before any output appeared from `LiveCapture`.  The previous version of `tshark`, (with the delay problem) available (as at mid Sept 2018) from the apt archives for the Raspberry Pi was 2.2.6.
