### ISSUE TITLE
OSX: RuntimeWarning: coroutine 'wait_for' was never awaited

### ISSUE THREAD

**Issue by ErikvdVen** [KimiNewt/pyshark#297]
Alright, I keep getting this error on OSX High Sierra. Anyone who knows what might cause this? Executing the script using `sudo` does not work. And I am able to run tshark without the sudo command so that should not be an issue as well I suppose. I also started xcode to check if I needed to submit any agreement or something. The issue:

```
/usr/local/lib/python3.7/site-packages/pyshark-0.4.1-py3.7.egg/pyshark/capture/capture.py:230: RuntimeWarning: coroutine 'wait_for' was never awaited
  self.eventloop.run_until_complete(self._cleanup_subprocess(tshark_process))
/usr/local/lib/python3.7/site-packages/pyshark-0.4.1-py3.7.egg/pyshark/capture/capture.py:230: RuntimeWarning: coroutine 'Process.wait' was never awaited
  self.eventloop.run_until_complete(self._cleanup_subprocess(tshark_process))
```

My code:

```
#!/usr/bin/env python3

import pyshark

def capture(iface, tout):
	cap = pyshark.LiveCapture(interface=iface);
	cap.set_debug()
	cap.sniff(timeout=10)

	for packet in cap.sniff_continuously(packet_count=5):
		print('Just arrived:', packet)


capture('en7', 50)
```

**Comment by Geoff99** [comment]
Not really sure if this will help or not, but anyway, just in case it does.

The error message appears to me to be related to the finalisation process, once the `cap.sniff_continuously` has found 5 packets.

I experienced a similar (but not identical) problem, which I eventually resolved by adding

`cap.close()` outside the end of the `for packet … ` loop, 

**and** by adding 

`sys.exit(0)` at the very end of my code.  

I found this by a combination of trial and (lots of) error, plus a bit of reading of the source code for `Capture` and `LiveCapture` to see what methods the classes had.  I don't know why it *works*, not why both steps are necessary (hence it may or may not be relevant to your issue), but just maybe it will help you.
