### ISSUE TITLE
RuntimeError: Event loop is closed on capture sniff

### ISSUE THREAD

**Issue by PatchOnKnee** [KimiNewt/pyshark#302]
Getting a asyncio error on a capture, it doesnt kill the script but it throws a big warning:

Paste bin: [https://pastebin.com/7sXEYcbz](https://pastebin.com/7sXEYcbz)

The code to reproduce:

`import pyshark

def test():
    print('start collecting')
    capture = pyshark.LiveCapture(interface="Wi-Fi", only_summaries=True)
    capture.sniff(packet_count=5)

while(True):
    test()`

It doesnt happen immediately but eventually it will. Any thoughts? Basically I'm trying to continuously read the packets going in/out and perform some analysis on them. Any alternatives would be greatly appreciated if this is the wrong way to go about this and is causing the error

**Comment by phe-sto** [comment]
The same happens randomly on my system (Windows 7, Pyshark Version: 0.4.2.3).

**Comment by irfancnk** [comment]
+
I got the same error after ending a LiveCapture by raising `pyshark.capture.capture.StopCapture()` then restarting it again. It does not happen everytime but eventually it may happen again. Must look into this please. 
`RuntimeError: Event loop is closed`
My Versions Are : 
pyshark == 0.4.2.9
Windows 10
Python 3.7
