### ISSUE TITLE
Output live capture to file damaged

### ISSUE THREAD

**Issue by blaier23** [KimiNewt/pyshark#317]
running the following:
capture = pyshark.LiveCapture(interface=None, output_file='E:\\test.cap')
capture.sniff(timeout=5)
print(len(capture))

result varies, could be either of the following:
- the output file is empty
- python(3.6) crash but the file contains all packets
- the file is missing some of the last packets "The capture file appears to have been cut short in the middle of a packet."

Running windows 10, wireshark 2.6
any ideas what I am missing out?
thanks

**Comment by avashi-siv** [comment]
Same issue with tshark 2.6.5, pyshark 4.2.2, on Fedora 29

**Comment by storyinvisible** [comment]
I am experience the same problem as well Below is my code . the output shows that the file is damanged 
```
import pyshark

from threading import Thread, Event

import os

class Sniffer(Thread):
	def  __init__(self, host, interface=None):
		super().__init__()

		self.daemon = True

		self.socket = None

		self._stop_event= Event()
		self.livecapture= None
	def stop(self):
		self._stop_event.set()

	def stopped(self):
		return self._stop_event.isSet()
   
	def run(self):
		print("running")
		self.livecapture = pyshark.LiveCapture(interface='lo',
			output_file= "file2.pcap", 
			bpf_filter='tcp port 4433')
		self.livecapture.sniff(timeout=20)

	def print_packet(self,packet):
		for i in packet:
			print(i)
sniff= Sniffer(4433)
sniff.start()


for i in range(100):
    print(i)
    os.system("wget -qO- https://localhost:4433 --no-check-certificate /dev/null")
sniff.join()
sniff.stop()
exit()
`
```

**Comment by xqrt** [comment]
Hi,

I have the same problem. Any suggestions?

TShark (Wireshark) 2.6.9 (v2.6.9rc0-12-g35589e6f)
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"


Thanks,
G

**Comment by ddebon2004** [comment]
Had the same problem on Ubuntu. I installed pcapfix with:
sudo apt install pcapfix

Then in python I used the following code:
import os
cmd = 'sudo pcapfix /tmp/trace -o /tmp/trace.pcapng'
os.system(cmd)
cmd = 'sudo mv /tmp/trace.pcapng /tmp/trace'
os.system(cmd)

This practically repairs the trace file.

**Comment by trombadore** [comment]
Also experiencing this with tshark 3.4.7 and macOS 11.5.1
