### ISSUE TITLE
LiveCapture interface -- check if input is valid 

### ISSUE THREAD

**Issue by avashi-siv** [KimiNewt/pyshark#318]
```
if interface is None:
            self.interfaces = get_tshark_interfaces(tshark_path)
        elif isinstance(interface, basestring):
            self.interfaces = [interface]
        else:
self.interfaces = interface
```

From this snippet in LiveCapture.  Would it be possible to check if the input "interface" is in the list of "get_tshark_interfaces".  TShark crashes after a long while and with no relevant errors in the event of an invalid input.

**Comment by aiskuld** [comment]
To add to this, and error would be nice that lists the possible solutions, basically the output from tshark -D.

Unless I missed something, there isn't much insight to the possible values for interface. 

For example, My tshark -D output on a windows machine:
```
tshark.exe -D
1. \Device\NPF_{XX-XX-XX-XX-XX-XX} (NIC3)
2. \Device\NPF_{XX-XX-XX-XX-XX-XX} (Local Area Connection* 8)
3. \Device\NPF_{XX-XX-XX-XX-XX-XX} (Local Area Connection* 6)
4. \Device\NPF_{XX-XX-XX-XX-XX-XX} (Local Area Connection* 7)
5. \Device\NPF_Loopback (Adapter for loopback traffic capture)
6. \Device\NPF_{XX-XX-XX-XX-XX-XX} (NIC1)
7. \Device\NPF_{XX-XX-XX-XX-XX-XX} (NIC2)
```

To my understand, I can use any of `[1, 2, 3, 4, 5, 6, 7`], and these are what's returned from `get_tshark_interfaces().` But I also can use any from `["NIC3", "Local Area Connection* 8", "Local Area Connection* 6", "Local Area Connection* 7", "Adapter for loopback traffic capture", "NIC1", "NIC2"]` or `["\\Device\\NPF_{XX-XX-XX-XX-XX-XX}", "\\Device\\NPF_{XX-XX-XX-XX-XX-XX}", "\\Device\\NPF_{XX-XX-XX-XX-XX-XX}", "\\Device\\NPF_{XX-XX-XX-XX-XX-XX}", "\\Device\\NPF_Loopback", "\\Device\\NPF_{XX-XX-XX-XX-XX-XX}", "\\Device\\NPF_{XX-XX-XX-XX-XX-XX}"]`

```
def get_tshark_interfaces(tshark_path=None):
    ...
    return [re.split('\.\s|\s\(|\)', line)[:-1] for line in tshark_interfaces.splitlines()]
    #or
    return [[line.split(". ")[0],
             line.split(". ")[1].split(" (")[0],
             line.split(". ")[1].split(" (")[1].split(")")[0]] for line in tshark_interfaces.splitlines()]
```
```
[['1', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'NIC3'],
 ['2', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'Local Area Connection* 8'],
 ['3', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'Local Area Connection* 6'],
 ['4', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'Local Area Connection* 7'],
 ['5', '\\Device\\NPF_Loopback', 'Adapter for loopback traffic capture'],
 ['6', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'NIC1'],
 ['7', '\\Device\\NPF_{XX-XX-XX-XX-XX-XX}', 'NIC2']]
```

This is obviously clunky, so it might just make more sense to be able to print the output of tshark -D if this is the only solution. Or `get_available_interfaces()` function on a Live_Capture object that would return all the possible values for interface and internally use list of ids.
