### ISSUE TITLE
file capture functionality 

### ISSUE THREAD

**Issue by coi-oz** [KimiNewt/pyshark#32]
Hi,

I have a huge pcap file and was trying to parse it with pyshark. I tried to load a last packet in pcap and found that python used all free memory on my laptop. 
I tried multiple options with lazzy/keep_packets but always the same result.  Is this a normal behaviour?  Is it possible that pyshark will only keep the last packet in memory? 

param lazy = True
param keep_packets = True

Thanks

**Comment by ohmtrivedi** [comment]
This will be a very lame question. But can you explain to me how to use the len(cap) function? 

`pcap = pyshark.FileCapture('14.pcap', only_summaries=True)`

The pcap file is pretty huge (7.5 GB uncompressed), and I would like to know the number of packets. len(pcap) returns me 0.
