### ISSUE TITLE
pyshark for capturing USB packets

### ISSUE THREAD

**Issue by mckay144** [KimiNewt/pyshark#320]
Trying to use pyShark for capturing USB packets. 
tshark -D lists my interfaces, and the one I want to monitor is USBPcap1; HOWEVER, dumpcap -i USBPcap1 fails to open the interface. Therefore, pyshark.LiveCapture() cannot capture any packets.  I am using Windows 10, pyshark 0.4.2.2.  Is there a solution for this?  Thank you in advance!

**Comment by Qyriad** [comment]
I'm having the same issue.
`tshark -i USBPcap1` works just fine, but `pyshark.LiveCapture(interface='USBPcap1')` tries to invoke `dumpcap -i USBPcap1`, which fails:
```
2019-10-10 22:39:05,191 - LiveCapture - DEBUG - Creating Dumpcap subprocess with parameters: C:/Program Files/Wireshark/dumpcap.exe -q -i \\.\USBPcap1 -w -
2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Dumpcap subprocess created
2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Creating TShark subprocess with parameters: C:/Program Files/Wireshark/tshark.exe -l -n -T pdml -r -
2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Executable: C:/Program Files/Wireshark/tshark.exe
2019-10-10 22:39:05,217 - LiveCapture - DEBUG - TShark subprocess created
2019-10-10 22:39:05,217 - LiveCapture - DEBUG - Starting to go through packets
Capturing on '\\.\USBPcap1'
dumpcap: The capture session could not be initiated on interface '\\.\USBPcap1' (Error opening adapter: The system cannot find the device specified.  (20)).
Please check to make sure you have sufficient permissions, and that you have the proper interface or pipe specified
```

**Comment by Qyriad** [comment]
I'm not super knowledgeable on the internals here, but it seems to me that tshark will drive whatever process it needs to, including dumpcap and USBPcap.
Is there any need for pyshark to explicitly invoke dumpcap at all?

**Comment by h3tz** [comment]
I am having the same issue here. As soon an usb adapter will be used and correctly listed using tshark -d pyshark is not able to capture it.

**Comment by h3tz** [comment]
> I'm having the same issue, specifically on Windows, and not on Linux.
> `tshark -i USBPcap1` works just fine, but `pyshark.LiveCapture(interface='USBPcap1')` tries to invoke `dumpcap -i USBPcap1`, which fails:
> 
> ```
> 2019-10-10 22:39:05,191 - LiveCapture - DEBUG - Creating Dumpcap subprocess with parameters: C:/Program Files/Wireshark/dumpcap.exe -q -i \\.\USBPcap1 -w -
> 2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Dumpcap subprocess created
> 2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Creating TShark subprocess with parameters: C:/Program Files/Wireshark/tshark.exe -l -n -T pdml -r -
> 2019-10-10 22:39:05,207 - LiveCapture - DEBUG - Executable: C:/Program Files/Wireshark/tshark.exe
> 2019-10-10 22:39:05,217 - LiveCapture - DEBUG - TShark subprocess created
> 2019-10-10 22:39:05,217 - LiveCapture - DEBUG - Starting to go through packets
> Capturing on '\\.\USBPcap1'
> dumpcap: The capture session could not be initiated on interface '\\.\USBPcap1' (Error opening adapter: The system cannot find the device specified.  (20)).
> Please check to make sure you have sufficient permissions, and that you have the proper interface or pipe specified
> ```

Having the same issue here. tshark -i works fine. Windows 10. Any solution?

**Comment by Bluee1Bird** [comment]
hi there, I have run into the same problem and cannot find the solution in this issue even though it is closed. What ended up working?

**Comment by satomavia** [comment]
I had a same problem and solved that using tshark.exe which is bundled to wireshark. I called this by using subprocess. 
Following is the program where you get the result text in packet. It needs administrator's mode and I started IDLE in admin mode.

import subprocess
packet = subprocess.getoutput("tshark.exe -i USBPcap1 -x -c 100")
