### ISSUE TITLE
Getting field offset within packet doesn't work if use_json is set True

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [KimiNewt/pyshark#321]
## Description:
It is possible to get the offset of some field (e.g. source IP address) within the packet. However, this doesn't work if `use_json` is set `True`.

## Steps to reproduce:

- Try to print source IP offset when `use_json` is `False`:

```
packets = pyshark.FileCapture(input_file=pcap_file_path, use_json=False)
print(packets[0].ip.src.pos) # Prints the offset of source IP

```

- Try to print source IP offset when `use_json` is `True`:

```
packets = pyshark.FileCapture(input_file=pcap_file_path, use_json=True)
print(packets[0].ip.src.pos) # Prints 'None'!

```

**Comment by KimiNewt** [comment]
This information simply does not exist in the tshark json output, so there isn't much that can be done about it..
