### ISSUE TITLE
How to dissect mms packet?

### ISSUE THREAD

**Issue by HuangZhenyang** [KimiNewt/pyshark#324]
Hi! I need to dissect MMS packets. In tshark,  I can set the profile and use "-C tshark-mms" to dissect MMS packets. What should I do to make pyshark have the ability of dissecting mms packets?
Thanks!

**Comment by KimiNewt** [comment]
I added a `custom_parameters` parameter to capture objects. Try to input `{"-C": "tshark-mms"}` and see if it helps. Reopen if it doesn't
