### ISSUE TITLE
With only_summaries=True and if the capture contains single packet it fails to result in packet count as 1

### ISSUE THREAD

**Issue by sathishsms** [KimiNewt/pyshark#327]
tshark.exe -l -n -T psml -Y ip.src==155.165.27.132 -r DSCP_CNS_TC01.pcap
results in 1 packet
<?xml version="1.0" encoding="utf-8"?>
<psml version="0" creator="wireshark/3.0.0">
<structure>
<section>No.</section>
<section>Time</section>
<section>Source</section>
<section>Destination</section>
<section>Protocol</section>
<section>Length</section>
<section>Info</section>
</structure>

<packet>
<section>1</section>
<section>0.000000</section>
<section>155.165.27.132</section>
<section>155.165.27.150</section>
<section>TCP</section>
<section>74</section>
<section>58782 \xe2\x86\x92 443 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=3443746288 TSecr=0 WS=512</section>
</packet>

</psml>

but cap = pyshark.FileCapture(pcap_file, keep_packets=False, display_filter=filter, only_summaries=False) results in 0 count

**Comment by dramasamy** [comment]
Prabu, neenga ingeyum vanthuteengala ?? :D
