### ISSUE TITLE
disable multiple protocols

### ISSUE THREAD

**Issue by mikewalshchicago** [KimiNewt/pyshark#335]
is it possible to disable multiple protocols, either with the disable_protocol param or is there a way to point pyshark to the disabled_protos file?

disable_protocol works fine if i only have one protocol to disable, for example 'disable_protocol="RTCP"', however if i want to also disable MP2T for example, adding "RTCP.MP2T", adding 'disabled_protocol' kwarg more than once, or trying to make disabled_protocol= a list object all fail in their own respective ways.  
Happy to post sample code, but I think the request is pretty direct and how to test would also be pretty straightforward.  Thanks in advance!

**Comment by PAk-CatchFire** [comment]
Did you find the solution to this?
Regards
