### ISSUE TITLE
raw epoch_timestamp when using json?

### ISSUE THREAD

**Issue by mikewalshchicago** [KimiNewt/pyshark#336]
when using LiveCapture, if i have 'include_raw=True and use_json=True", the return value that i get from sniff_timestamp is a string value of a datetime object, for example:

May 14, 2019 21:26:54.187276000 CDT

the value is immutable, that is to say i can not convert the datetime object to a timestamp.  when using xml (use_json=False), i can convert sniff_time from a datetime object into a float with nanosecond precision with the following:

timestamp = str( "%.9f" % packet.sniff_time.timestamp())

but, with use_json false, that forces me to also set include_raw to false,

so this puts me in a catch-22, because in order to get the raw packet data, i have to sacrifice the 'raw' arrival time of the packet

I'm hopeful there is a resolution however, because whether or not have use_json=True, the frame.info includes an Epoch Time field like so:

2019-05-14 21:39:44.827:1557887984.827702761 DEBUG    (ThreadPoolExecutor-0_39)  Layer FRAME:
        Encapsulation type: Ethernet (1)
        Arrival Time: May 14, 2019 21:39:36.191221000 CDT
        Time shift for this packet: 0.000000000 seconds
        Epoch Time: 1557887976.191221000 seconds

curiously, it's shown as microseconds even though after I convert sniff_time as shown above it reports in nanosecond granularity.

If someone could suggest how i can get a UNIX timestamp with the use_json param set to True, I'd very much appreciate it.

**Comment by mikewalshchicago** [comment]
i put some exception handling in and this output should shed some light on the issue:
                logger.debug(packet.sniff_timestamp()))
or
                logger.debug(str(packet.sniff_timestamp()))
will produce:
                 'str' object is not callable

or

will produce:
                 could not convert string to float: 'May 14, 2019 22:18:17' 

my vitals:

TShark (Wireshark) 3.1.0 (v3.1.0rc0-691-gad72d548)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, without libnl, with
GLib 2.56.1, with zlib 1.2.7, without SMI, without c-ares, without Lua, without
GnuTLS, with Gcrypt 1.5.3, without Kerberos, without MaxMind DB resolver,
without nghttp2, without brotli, without LZ4, without Snappy, without libxml2.

Running on Linux 3.10.0-957.12.1.el7.x86_64, with Intel(R) Xeon(R) CPU E5-2650
v4 @ 2.20GHz (with SSE4.2), with 64145 MB of physical memory, with locale
en_US.UTF-8, with libpcap version 1.8.1, with Gcrypt 1.5.3, with zlib 1.2.7,
binary plugins supported (0 loaded).

Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-36).

pyshark version: 0.4.2.3. installed via pip

python version 3.6

**Comment by mikewalshchicago** [comment]
I was able to get what I need with one simple change to the tshark_json.py file:

    return Packet(layers=layers, frame_info=JsonLayer('frame', frame_dict),
                  number=int(frame_dict.get('frame.number', 0)),
                  length=int(frame_dict['frame.len']),
#                  sniff_time=frame_dict['frame.time'],
                  sniff_time=frame_dict['frame.time_epoch'],

when using frame.time_epoch, the return value changes to the following:

            print(p.sniff_time)
returns
>>  2019-05-16 10:48:45.740395

and 
            print( "%.9f" % p.sniff_time.timestamp())
returns
>>  1558021725.740395069


Since you can convert epoch to any datetime format you'd like with strftime, i personally feel that epoch is more useful, but i'm obviously biased.  perhaps a parameter can be added so users can choose between time and epoch.

**Comment by KimiNewt** [comment]
You could add a PR that adds those two time options into the packet or frame options in JSON, it sounds like a good idea.
