### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by mikewalshchicago** [KimiNewt/pyshark#337]
I see a few closed issues where users have asked if it is possible to parse a capture, and then write the filtered or packets of interest to another output file.  I'm currently using dpkt's Writer object to do this; pcapy has a similar 'dumper' object.  

from the closed comments, it's clear that writing a pcap output is 'out of scope' for this project, but I will contest that the purpose of pyshark is to parse input and return a subset of the network messages as a result.  Why stop at stdout?

FWIW: dpkt.Writer would be just fine, except because of the timestamp with use_json being a string, I can't apply the timestamp to the capture created by dpkt.  So, this issue is loosely related to #336

**Comment by gaardiolor** [comment]
I'm missing this also. I've got some workarounds though:

> except because of the timestamp with use_json being a string

You can use `float(pkt.frame_info.time_epoch)`

I'm iterating over packets with scapy `PcapReader()` and pyshark `FileCapture()` .
`for self.counter, (scapy_pkt, pyshark_pkt) in enumerate(zip(scapy_pcapreader, pyshark_filecapture)):`

If a packet matches my pyshark filter, I'm writing `scapy_pkt` to a new file using scapy `PcapWriter` .

**Comment by mikewalshchicago** [comment]
I managed a workaround by modifying the code published at the link below:

https://github.com/martinxyz/config/blob/master/code/PcapFile.py

Although the capture is working, it seems to be many minutes behind, although i do not see any evidence of queueing (memory consumption).  Thanks for your suggestion; I may try it out if i can determine that the class from the link above is responsible for the delay.

**Comment by KimiNewt** [comment]
You're more than wlecome to make a PR for simple writing of packets, so long as it's in a separate file and doesn't require scapy/dpkt (as it's a big overhead). If we don't want to write the whole pcap writing code again (though it's not much), we can include a smaller package but have it as an optional requirement (i.e. inline-import)

**Comment by tanzeelrana** [comment]
did someone get this going ? I don't understand how I can get the `frame.time_epoch`

**Comment by tanzeelrana** [comment]
never mind I got that info `cap.frame_info` also found the field names `cap.frame_info.field_names`
