### ISSUE TITLE
Extract vendor out of received pyshark package

### ISSUE THREAD

**Issue by ErikPy** [KimiNewt/pyshark#342]
Hello,
I hope anyone can help me...

Currently I receive packets by using pyshark.
I can extract a lot of information like: src IP, dst IP, protocoll, portnumber, ...
Now I want to extract the vendor of the src and dst adress. By using tshark or Wireshark its no problem, but I dont know how to extract the vendor out of the received pyshark-package.

Using: "myReceivedPacket.eth._all_fields["eth.src_resolved"]" gives me as a result only the MAC-Adress of the src-adress but not the vendor name like in tshark or Wireshark...

Have anyone an idea, how to extract the vendor-name? Is it possible at all?

Thanks in advance!

regards

Erik

**Comment by kcexn** [comment]
This has to do with the default way that the tshark process is instantiated using the '-n' flag. You can overwrite the behaviour for your specific requirements by adding in custom parameters for address resolution using the -N flag.

For example if you are opening pcap or pcapng file using FileCapture you might want to try something like:

`cap = FileCapture('/path/to/file.pcapng', use_json = True, custom_parameters={'-N': 'm'})`

-N adds address resolution, the value m gives you MAC address resolution. This will overwrite the default behaviour for mac addresses.
