### ISSUE TITLE
not all data available in packet attribute 

### ISSUE THREAD

**Issue by saddawe2424** [KimiNewt/pyshark#346]
hi,
i am working on some gsm work in python using pyshrak and i face alot issues if anyone have solution kindly help me.
1st issue some attribute names have dot in name than when i call attribute its take both separate after dot it's hard for me to work with this problem.
2nd big issue is not all data i will get in attributes like in packet 2 tmsi i will get only  i check field_names its and all attributes only not have attribute for all tmsi but if i print packet layer directly than its show whole packet with its all tmsi how i will able to get all data in packet layer ..

in this image i show a gsm packet layer using "print packet.layername" and its will output all data in this layer and i am fine it's showing all data as you see 2 tmsi and other alot info
![image](https://user-images.githubusercontent.com/35268406/59314057-fd283b00-8ccc-11e9-8934-b6be005fadd5.png)
in this 2nd pic i show a gsm packet layer all fields using same packet and using "print packet.layername._all_fields" as you able to see only 1 tmsi and alot data missing why this happen and how can i able to get all those data
![image](https://user-images.githubusercontent.com/35268406/59314025-cf42f680-8ccc-11e9-9067-6b7e8b1ad06e.png)

kindly give me solution..

**Comment by kcexn** [comment]
First off. You need to do a much better job at hiding your IMSI's. You have a clearly visible IMSI. And right next to the MCC and MNC even though you've covered up the text translations the identifiers are clearly visible.

Secondly. Have you tried looking at the tshark output? does it have all the attributes you need? If it does you can take try using the json output. The XML parsing unfortunately doesn't always give you the packet structure you expect, I've encountered this with some other telco specific packets as well.

```python
import pyshark as ps
cap = ps.FileCapture(<example pcap.pcap>, use_json = True)
```

**Comment by decastromonteiro** [comment]
Were you able to fix that using json? I have the same issue using diameter where I can only access the first occurance of a given AVP. I tried json approach, but got nothing. Maybe I'm missing something.

**Comment by mattLLVW** [comment]
The data you're looking for is probably in a `packet.layers.<YOURLAYER>.duplicate_layers`.

**Comment by sfikouris** [comment]
Hello guys, if you still facing this error you should try to get the IMSI with "e212_imsi" instead of "e212.imsi".
