### ISSUE TITLE
pyshark.FileCapture not reading all packets

### ISSUE THREAD

**Issue by SBarradas** [KimiNewt/pyshark#354]
When I read the file with summaries_only=True I get 182618 packets. When I read it normally without the summary option, it only returns 23014 packets and gives me this error on the debug. 

[2019-07-17 15:15:44.929107] DEBUG: FileCapture: Executable: C:/Program Files/Wireshark/tshark.exe
[2019-07-17 15:15:44.955037] DEBUG: FileCapture: TShark subprocess created
**
ERROR:C:\buildbot\wireshark\wireshark-3.0-64\windows-2016-x64\build\epan\print.c:1716:get_field_data: code should not be reached
[2019-07-17 15:15:55.905837] DEBUG: FileCapture: EOF reached (sync)

I'm using python 3.7.3
pyshark 0.4.2.3

**Comment by kcexn** [comment]
if you run tshark on the command line and just display summaries does it give you the right number of packets?

i.e. in a unix environment try, in windows you'll want to count how many times '<packet>' is output 
to the console.

```bash
tshark -r $PCAP_FILE -T psml | grep -c '<packet>'
```

**Comment by fight-think** [comment]
I also meet this problem, I use the default parameters of FileCapture and It cannot parse all the packages but only part. So how do you fix this problem @SBarradas

**Comment by fight-think** [comment]
> When I read the file with summaries_only=True I get 182618 packets. When I read it normally without the summary option, it only returns 23014 packets and gives me this error on the debug.
> 
> [2019-07-17 15:15:44.929107] DEBUG: FileCapture: Executable: C:/Program Files/Wireshark/tshark.exe
> [2019-07-17 15:15:44.955037] DEBUG: FileCapture: TShark subprocess created
> **
> ERROR:C:\buildbot\wireshark\wireshark-3.0-64\windows-2016-x64\build\epan\print.c:1716:get_field_data: code should not be reached
> [2019-07-17 15:15:55.905837] DEBUG: FileCapture: EOF reached (sync)
> 
> I'm using python 3.7.3
> pyshark 0.4.2.3

how do you fix this problem?

**Comment by tarinnn** [comment]
Facing the same issue with pyshark version 0.4.5
