### ISSUE TITLE
Any code example to show how to use lua script by pyshark?

### ISSUE THREAD

**Issue by IAMABOY** [KimiNewt/pyshark#356]
tshark usage:
tshark -X lua_script:http.lua  -r http.pcap -q

how to use the command in pyshark?

**Comment by IAMABOY** [comment]
the example is:
param = { '-X': 'lua_script:http.lua'}
cap = pyshark.FileCapture(input_file=http.pcap', custom_parameters=param)
cap.load_packets()

but if param is a dict,if I want to pass more param ,just like command

 tshark -X lua_script:http.lua -X lua_script1:data-text-lines -r http.pcap -q

cause value  lua_script:http.lua and value lua_script1:data-text-lines have the same key -X,
so how can I pass more key/value by using -X,can anyone fix this?

**Comment by IAMABOY** [comment]
I got it by reading source code.
we can use list in this case ,for example:

param = [ '-X', lua_script:http.lua','-X', 'lua_script1:data-text-lines']
cap = pyshark.FileCapture(input_file=http.pcap', custom_parameters=param)
cap.load_packets()

**Comment by KimiNewt** [comment]
Looks like you solved it yourself. Grand..
