### ISSUE TITLE
Very slow parsing

### ISSUE THREAD

**Issue by jakhetia** [KimiNewt/pyshark#357]
Hi,

I am trying to parse a pcap file containing aroung 145,000 packets, if I parse the whole file it takes several minutes. For 5000 packets, it takes around ~40 seconds, so I thought of implementing multithreading in my script but I found out that I am able to starts multiple threads but the performance is not improved, only one thread is being executed at once.
Can anyone suggest way to improve performance by adding parallelism or anything ?

Thanks in advance. I need it urgently.

**Comment by KimiNewt** [comment]
Have you tried using `json_mode=True` in the Capture object

**Comment by meaditisharma** [comment]
there is no such mode i.e json_mode=True  in Capture object. do you mean by use_json=True?

**Comment by SiMet** [comment]
@KimiNewt using `use_json=True` shall increase or decrease parsing time.

We also found that Parsing file takes lots of time.

**Comment by SiMet** [comment]
@jakhetia probably my anwer will not be urgent :D but we found that you could speed processing when use use_json=True, custom_parameters={"-j": ... } where value of '-j' is protocols which you need in your pcap processing.

For more you could read for example here: https://www.wireshark.org/docs/man-pages/tshark.html

This trick speed up our processing twice.


using include_raw=False is also faster then with include_raw=True. However, include_raw gives you access to more details.
