### ISSUE TITLE
Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by montereyray73** [KimiNewt/pyshark#360]
Hi,
I am running Python 3.7.3 and have installed the latest pyshark.  I have tried to perform basic operations such as:

import pyshark
cap = pyshark.FileCapture('all.pcap')

for pkt in cap:
      print(cap)
RuntimeError: Cannot run the event loop while another loop is running

cap[0]
RuntimeError: Cannot run the event loop while another loop is running

'IP' in cap
RuntimeError: Cannot run the event loop while another loop is running

I have performed installs on Linux, Mac and Windows 10 and get the same error.  Am I missing something here?  I have not been able to much information about this error.   I'm wondering if I failed to install something additional.

Thanks

**Comment by KimiNewt** [comment]
It seems like you're running it under a different eventloop. Are you perhaps running inside of `jupyter`?

The way to circumvent this is to use the async functions, such as:

```
def print_pkt(pkt):
    print(pkt)
await cap.packets_from_tshark(print_pkt)
```

**Comment by eswarthammana** [comment]
I too face the same issue when using Jupyter and/or Google colab. But after switching to python IDLE its working fine.
Temporarily can try IDLE

**Comment by KimiNewt** [comment]
As written above, `jupyter` now runs all code inside an eventloop so you can use the synchronous pyshark methods. You have to use the async methods such as the one above. They will be simplified in the future to enable things like packet iteration.

**Comment by eswarthammana** [comment]
Thanks for the input @KimiNewt. Is the issue raised in Jupyter community?

**Comment by hothienlac** [comment]
> Thanks for the input @KimiNewt. Is the issue raised in Jupyter community?

Yes, I did find solution for it in a Vyshali Enukonda blog, you can add these two lines

import nest_asyncio
nest_asyncio.apply()

into Python\Python38\Lib\site-packages\tornado\__init__.py in tornado package and restart the kernel. It does work for me.

ref: https://medium.com/@vyshali.enukonda/how-to-get-around-runtimeerror-this-event-loop-is-already-running-3f26f67e762e

**Comment by farisalasmary** [comment]
I added the two lines above and it worked!!

For future developers who may face the same issue, you can find the path of `tornado` library as follows:
1. open the python interpreter 
2. type
```
import tornado
print(tornado)
```
and you will get the path to the package

**Comment by kusumy** [comment]
Doesn't worked for me ..

**Comment by clandestinenetworks** [comment]
ww... why would you not just use tcpdump??????????

**Comment by vbrozik** [comment]
> `nest_asyncio.apply()`

For me it was enough to run the code just in the notebook. I did not need to modify the installed package.

> `with pyshark.FileCapture( <FILE_NAME>.pcap) as filtered_cap:`

This did not resolve the problem for me.
