### ISSUE TITLE
Add option to parse tshark output only

### ISSUE THREAD

**Issue by davereikher** [KimiNewt/pyshark#362]
I think it would be a useful feature to be able to pass just the tshark output to the pyshark parser.

 I'll give an example - there was a bug in one of the wireshark dissectors, which I patched and re-compiled tshark. Due to compatibility issues I created a docker image which runs this modified tshark and outputs the regular tshark output to stdout. I wrapped it all in a bash script to 'emulate' an executable and passed this bash script through the `tshark_path` parameter to `FileCapture`. However, due to permission-related issues (docker must run using sudo and so on) this doesn't work. Even if it did, running docker each time is also rather slow, so it would be better to have a container running as a service that contains this patched tshark and just returns the stdout every time a capture file is submitted to it. Currently, as far as I know, pyshark doesn't have an API to which I can pass just the stdout of tshark.

**Comment by KimiNewt** [comment]
This sounds like a good idea. I'll try adding in a future release (and you're free to add it in a PR)

**Comment by davereikher** [comment]
Thanks, I will be happy to add a PR with this enhancement.
