### ISSUE TITLE
Issue with accessing radius protocol pacp which contains av-pair

### ISSUE THREAD

**Issue by pankajsheoran** [KimiNewt/pyshark#364]
In wireshark we can have a filter like radius.Cisco_AVPair == "nas-update=true" similar is not possible in pyshark

If we use below code it can only print first occurance of Cisco_AVPair

`
import pyshark
cap = pyshark.FileCapture("nas-update.pcap")
for pkt in cap:
 print (pkt['radius'].cisco_avpair)
`

**Comment by decastromonteiro** [comment]
> In wireshark we can have a filter like radius.Cisco_AVPair == "nas-update=true" similar is not possible in pyshark
> 
> If we use below code it can only print first occurance of Cisco_AVPair
> 
> `import pyshark cap = pyshark.FileCapture("nas-update.pcap") for pkt in cap: print (pkt['radius'].cisco_avpair)`

I have the same issue while using diameter dissector. When I print the packet, I notice all AVPs are in the message, but when I try to access them, I can only access the first occurance of such AVP.

Any fixes for that?

**Comment by decastromonteiro** [comment]
I have the same issue while using diameter dissector. When I print the packet, I notice all AVPs are in the message, but when I try to access them, I can only access the first occurance of such AVP.
