### ISSUE TITLE
Unable to get ftp request_command field if 'use_json == True'

### ISSUE THREAD

**Issue by ReasonJinMing** [KimiNewt/pyshark#365]
![图片](https://user-images.githubusercontent.com/32294196/63493681-ae79f700-c4ee-11e9-81d0-4c19e2b6e855.png)
json contains the infomation, but pyshark cannot extract it

**Comment by KimiNewt** [comment]
Can you attach a sample capture? I think that if you're using the latest version it ought to be accessible (check your `pkt.field_names`)

**Comment by reasonjinming** [comment]
> Can you attach a sample capture? I think that if you're using the latest version it ought to be accessible (check your `pkt.field_names`)


[1.1.7.107-34826 -- 1.2.174.140-21 FTP.pcap.zip](https://github.com/KimiNewt/pyshark/files/3567514/1.1.7.107-34826.--.1.2.174.140-21.FTP.pcap.zip)
I‘m sorry for replying too late. I will give a more detailed description.
For the sample pcap file, if opening with use_json mode, the result is like following.
file:///home/xujinming/%E6%A1%8C%E9%9D%A2/json.png
However, if opening with pdml mode, the result is like following.
file:///home/xujinming/%E6%A1%8C%E9%9D%A2/pdml.png
Clearly, there are differences between the two mode.

**Comment by reasonjinming** [comment]
> Can you attach a sample capture? I think that if you're using the latest version it ought to be accessible (check your `pkt.field_names`)

[1.1.7.107-34826 -- 1.2.174.140-21 FTP.pcap.zip](https://github.com/KimiNewt/pyshark/files/3567538/1.1.7.107-34826.--.1.2.174.140-21.FTP.pcap.zip)
I‘m sorry for replying too late. I will give a more detailed description.
For the sample pcap file, if opening with use_json mode, the result is like following.
![json](https://user-images.githubusercontent.com/32294196/64140571-6f756b00-ce37-11e9-826d-c2e3f93a8306.png)
However, if opening with pdml mode, the result is like following.
![pdml](https://user-images.githubusercontent.com/32294196/64140585-7b612d00-ce37-11e9-9f21-dc54772108a4.png)
Clearly, there are differences between the two mode.
