### ISSUE TITLE
KeyboardInterrupt not exiting cleanly and causes TSharkCrashException

### ISSUE THREAD

**Issue by mfaizmzaki** [KimiNewt/pyshark#367]
I am facing a problem where issuing a keyboard interrupt does not stop the program cleanly. It caused the TSharkCrashException. This issue happened when using sniff_continuously() method. I have tried raising StopCapture() exception but to no avail. The following is a sample code that caused the error:

    def capture():
            cp = ps.LiveCapture()
        
            try:
                print(f'Capturing ID:  {os.getpid()}')
                for packet in cp.sniff_continuously():
                    pass
            
            except KeyboardInterrupt:
                print('Capture done')

![pyshark_crash](https://user-images.githubusercontent.com/9010487/63752577-114f0200-c8e4-11e9-957d-26ace200a42d.PNG)

How should I tackle this issue?

**Comment by KimiNewt** [comment]
I'm not experiencing this. Can you specify your pyshark version, python version and OS?

**Comment by mb-robo** [comment]
I have a similar problem for pyshark 0.4.3, Python 3.8.5 and Ubuntu 20. 04.
