### ISSUE TITLE
is there a simple/common way to access all the layers in that packet capture

### ISSUE THREAD

**Issue by eswarthammana** [KimiNewt/pyshark#371]
Hi Team,

Thanks for pyshark. Currently i am analysing packet data using pyshark. 
i used an example below,
for pkt in pcap:
      pkt['frame_info'] #not working

for pkt in pcap:
      pkt.frame_info #working

by using first approach i decided to access all the field data in the layers with out bothering about the layers in the device type(should work for ipv4 or ipv6 irrespective of layers)

through the first approach able to get 4 or 5 layers but i am missing few layers to access through KeyError.
The missing one were able to access through the 2nd approach only.

Cloud you please suggest any common way to get field data of the layers with out re writing code if any new layers comes in to the device, which currently i am facing a problem.

Thanks for your time.

**Comment by KimiNewt** [comment]
I'm not sure I understand. In general you can see all layers using `pkt.layers`, you can access them via `pkt.ip` or `pkt["IP"]` or `pkt[4]` (the fifth layer). 
You can check of their existence with `"IP" in pkt`.
