### ISSUE TITLE
Reading packet capture using only_summaries=True is excluding the packet 1 related data

### ISSUE THREAD

**Issue by eswarthammana** [KimiNewt/pyshark#377]
Hi Team,
Pyshark is really help full for network data analysis.
while reading the packets using pyshark, only_summaries=True... Where packet 1 is missing.

![code snip](https://user-images.githubusercontent.com/23114153/66480900-3d51cb80-eabd-11e9-8c20-240aab2183ea.png)

Please provide a solution.

**Comment by eswarthammana** [comment]
As Suggested in #148 
(You can try to change the value of the variable SUMMARIES_BATCH_SIZE from 64 to 8 in line 42 of
pyshark/capture/capture.py)

This fix worked but is there any impact on other process. Could you please explain what exactly happens when we change from 64 to 8

**Comment by OhadHirsh** [comment]
Changing the value of the variable SUMMARIES_BATCH_SIZE from 64 to 8 didnt work on Linux.

**Comment by FYPYTHON** [comment]
SUMMARIES_BATCH_SIZE = 4  on Linux ok.

**Comment by fkerem** [comment]
SUMMARIES_BATCH_SIZE = 4 didn't work for me on MacOS.
SUMMARIES_BATCH_SIZE = 5 seems to work for now.
