### ISSUE TITLE
SSH Remote Capture

### ISSUE THREAD

**Issue by Dimbreath** [KimiNewt/pyshark#387]
On Wireshark I have the ability to do remote capture over SSH (It must be toggled when installing Wireshark and using PCAP Remote). Is it possible to achieve the same with pyshark?

**Comment by dolbi13** [comment]
yes it's possible and plz follow this 2 links for more information ^^ 

https://github.com/rpcapd-linux/rpcapd-linux

https://github.com/KimiNewt/pyshark/blob/master/src/pyshark/capture/remote_capture.py
