### ISSUE TITLE
DATA decoding: Exception in callback _ProactorReadPipeTransport._loop_reading

### ISSUE THREAD

**Issue by h3tz** [KimiNewt/pyshark#392]
Open the attached file to reproduce
[outfile.zip](https://github.com/KimiNewt/pyshark/files/4126975/outfile.zip)

```
capture = pyshark.FileCapture('C:/tmp/outfile.pcap')
print (capture[0])
```

**Comment by h3tz** [comment]
it is not pyshark related

**Comment by most-of-a-shark** [comment]
I am new to parsing pcap files in Python and got this same exception. Do you mind mentioning how you managed to resolve this issue ?
