### ISSUE TITLE
Stop a LiveCapture / timeout doesn't work

### ISSUE THREAD

**Issue by TheBigFudge** [KimiNewt/pyshark#397]
Hello,

is there a possibility to stop a LiveCapture after a certain runtime? The timeout parameter of the sniff() function does not work.  The process simply continues

or are there other functions to start or stop a LiveCapture manually, for example after the interface, filters etc. has been defined?

```
def Packet_Process(self, pkt):
        """Directive for each received packet."""
        print(pkt)

capture = pyshark.LiveCapture(interface='lo')
capture.apply_on_packets(self.Packet_Process)
capture.sniff(timeout=10)
```

**Comment by lxGuardianxl** [comment]
Hey,

Looking through the code @ (src/pyshark/capture.py)

>         Runs through all packets and calls the given callback (a function) with each one as it is read.
>         If the capture is infinite (i.e. a live capture), it will run forever, otherwise it will complete after all
>         packets have been read.
>         Example usage:
>         def print_callback(pkt):
>             print(pkt)
>         capture.apply_on_packets(print_callback)
>         If a timeout is given, raises a Timeout error if not complete before the timeout (in seconds)

apply_on_packets does have a timeout parameter. Once this timeout is hit - it causes an exception
`concurrent.futures._base.TimeoutError`

This makes the capture.sniff() in your example redundant, you can then continue your expected procedures after.

For example: 
(This requires importing concurrent, though there may be another alias within threading / asyncio, etc.)
```
def Packet_Process(self, pkt):
        """Directive for each received packet."""
        print(pkt)

capture = pyshark.LiveCapture(interface='lo')
try:
        capture.apply_on_packets(self.Packet_Process,timeout=10)
except concurrent.futures._base.TimeoutError as e:
        print("Timeout has been reached. Continue")
```

Let me know if this helps your issue, if you need any further help, I'd be happy to advise!
