### ISSUE TITLE
Statistics output supported?

### ISSUE THREAD

**Issue by Jgerardopine** [KimiNewt/pyshark#412]
Hi,

 I have been trying to find out if the following tshark filters exist or cna be reproduced with pyshark:

`tshark -q -z io,phs -r test.pcap` --> Returns all the protocols within the pcap file as a tree
`tshark -q -z endpoints,ip -r test.pcap` --> Returns all IPs within the pcap
 
I have managed to get some data but I would like to know if there is funciton that provides the statistics as shown in tshak, The reason is the time it takes to get that data with tshark (around 1sec in a 2MB file), while trying to build it through the different funcitons in tshark (such as layers, only_summary, etc) takes way more time.

Is this supported or planned ot be supported? Can you guide on the funcitons I should be using to create such output?

**Comment by coco-pa** [comment]
I also hope pyshark can have statistics-related functions.

**Comment by razaborg** [comment]
I see the issue has been closed. However I cannot see anything about it in the doc
Is there any way to process those statistics automatically with pyshark ?

**Comment by jasonhillva** [comment]
Was this ever fixed?  On a side not is there a site with full documentation?
