### ISSUE TITLE
Add support to access frame info / profishark data

### ISSUE THREAD

**Issue by patVog** [KimiNewt/pyshark#413]
Hello,

I just stumbled over pyshark which seems quite the right thing for my use case.
I have to do a lot of capture analysis where often a profishark device is used to capture packets. Since the device has two interfaces the packets can be distinguished by the "Interface id" field in the frame data. It would be perfect if frame information could be as easy accessible as the other data fields as well. So far I am parsing the frame_info manually which is not really nice.

I also tried interface_captured but this just shows none.

If you could guide me in a direction how this should be implemented I would give this a try myself.

Thanks
Patrick

**Comment by etlweather** [comment]
This was closed but `captured_interface` returns `None` all the time.

**Comment by etlweather** [comment]
The interface can be gotten however with this:

`packet.frame_info.interface_name`
