### ISSUE TITLE
Add option to read from stdin

### ISSUE THREAD

**Issue by ahgit1** [KimiNewt/pyshark#418]
I've modified file_capture.py to allow reading from stdin (from mergecap) - could this be incorporated into the current build. I added the following line at line 43 and indented the next 4 lines 
Thanks

 if not self.input_filename == '-': # added line
            if not isinstance(input_file, str):
                self.input_filename = input_file.name
            if not os.path.exists(self.input_filename):
                raise FileNotFoundError(
                    "[Errno 2] No such file or directory: "
                    + str(self.input_filename)
                    )
self.keep_packets = keep_packets
self._packet_generator = self._packets_from_tshark_sync()

**Comment by Liopjk** [comment]
I've just made a PR to implement this.

**Comment by Liopjk** [comment]
This functionality exists as pyshark.capture.pipe_capture.PipeCapture.
