### ISSUE TITLE
Multiple TLS records in the same packet are counted as a single layer

### ISSUE THREAD

**Issue by nikirill** [KimiNewt/pyshark#419]
In tshark-recorded traces, some packets appear to have several TLS records inside but pyshark can see only a single TLS layer in these packets. As a result, accessing `packet.tls.record_length` or `packet.tls.record_content_type` will show only those of the first record, while `packet.tls.app_data` will show the app data of the first record + the headers of the next records in the packet + the app data of the next records.

Here is an example of a packet:
```
Layer TLS:
	TLSv1.3 Record Layer: Application Data Protocol: http-over-tls
	Opaque Type: Application Data (23)
	Version: TLS 1.2 (0x0303)
	Length: 283
	Encrypted Application Data: 165bad9f5332e477157508ba6df802592c36f68303fc67b0\xe2\x80\xa6
	TLSv1.3 Record Layer: Application Data Protocol: http-over-tls
	Opaque Type: Application Data (23)
	Version: TLS 1.2 (0x0303)
	Length: 218
	Encrypted Application Data: 4a0abddd87cd12fe4ab388a8bc058c925d21032aae6c2c22\xe2\x80\xa6
```
Running `packet.layers` gives `[<ETH Layer>, <IP Layer>, <TCP Layer>, <TLS Layer>]` and `packet.tls.record_length` gives 283. So `packet.get_multiple_layers("TLS")` does not help.

To reproduce, capture, for example, the loading of Google's landing search page using Selenium or manually and read the capture using pyshark. There will be _some_ packets like above. 

It is unclear to me where this problem should be handled. Is it tshark's fault for not creating multiple TLS layers? Or pyshark's fault for not parsing multiple headers correctly?

Pyshark: 0.4.2.11, tshark: 3.2.4, python: 3.8.2.
On Ubuntu 20.04.

**Comment by manvari** [comment]
pyshark lists all records in a TLS layer `tlslayer` under `tlslayer.record.all_fields`, whereas accessing `tlslayer.record` only shows the first record in the layer. This is because `tlslayer.record` is a `LayerFieldsContainer`.

Similarly with other fields such as `tls.record_length`:
```
>>> l2.record_length.all_fields
[<LayerField tls.record.length: 537>, <LayerField tls.record.length: 69>]
>>> type(l2.record)
<class 'pyshark.packet.fields.LayerFieldsContainer'>
```

This could be explained in the docs, will try to send in a PR.

**Comment by kidultff** [comment]
> For some reason i am having problems working with multiple TLS records. There are times that pyshark does not seem to be able to detect them.
> 
> Here is an example that uses two captures from two different TLS handshakes:
> 
> * "two-tls-records.pcapng": First messages of the TLS handshake. The server sends the Server Certificate and the Server Hello Done records in the same TLS packet.
> * "three-tls-records.pcapng": First messages of the TLS handshake. The server sends the Server Hello, Server Certificate and Server Hello done records, all, in the same TLS packet.
> 
> Here is the code used for the example:
> 
> ```python
> #!/usr/bin/env python3
> import pyshark
> 
> handshake_types = {'1': 'Client Hello',
>                    '2': 'Server Hello',
>                    '11': 'Server Certificate',
>                    '12': 'Server Key Exchange',
>                    '14': 'Server Hello Done'}
> 
> pcap_2_tls_records = "./two-tls-records.pcapng"
> pcap_3_tls_records = "./three-tls-records.pcapng"
> 
> def list_all_records(pcap_file):
>     capture = pyshark.FileCapture(pcap_file)
>     tls_packets =  [packet.tls for packet in capture if hasattr(packet, 'tls')]
>     handshake_with_record = [(handshake_types[packet.handshake_type], len(packet.record.all_fields))
>                              for packet in tls_packets
>                              if hasattr(packet, 'handshake') and hasattr(packet,'record')]
>     for packet, num in handshake_with_record:
>         print("Packet {} has {} TLS records".format(packet, num))
>     capture.close()
> 
> print("Pcap with Certificate + Server Hello Done:")
> list_all_records(pcap_2_tls_records)
> print("\nPcap with Server Hello + Certificate + Server Hello Done:")
> list_all_records(pcap_3_tls_records)
> ```
> 
> Output:
> 
> ```
> Pcap with Certificate + Server Hello Done:
> Packet Client Hello has 1 TLS records
> Packet Server Hello has 1 TLS records
> Packet Server Certificate has 1 TLS records    <- Not working as expected. This should have 2 TLS records: Server Certificate and Server Hello Done
> 
> Pcap with Server Hello + Certificate + Server Hello Done:
> Packet Client Hello has 1 TLS records
> Packet Server Hello has 3 TLS records    <- Working as expected
> ```
> 
> Here are the pcap files used:
> [issue-multiple-tls-records.zip](https://github.com/KimiNewt/pyshark/files/5108641/issue-multiple-tls-records.zip)
> 
> Versions of the software used:
> 
> * Pyshark 0.4.2.11
> * tshark 3.2.6
> * Python 3.8.5
> 
> I'm missing something or this is a bug?

I have the same problem, pyshark can get multiple records in one TLS record, but can't get multiple records in more than one TLS records. @KimiNewt

**Comment by MargaretZhao** [comment]
Is this issue resolved or is there any work around?

**Comment by sharrythakur** [comment]
Is this issue resolved or is there any work around?
