### ISSUE TITLE
asyncio  with pyshark

### ISSUE THREAD

**Issue by tiwns** [KimiNewt/pyshark#442]
Hello,

I am trying to run a packet sniffer using pyshark and asyncio. I do not have much experience with asyncio and have been dealing with errors while trying to implement. I have been able to get pyshark working in a thread without issue, but I am moving to asyncio because my goal is to have pyshark record network data continuously until some other event in my program is complete and then quit, then restart and record some other event. The only way I know how to get pyshark to quit is to run the thread as a daemon, and quit with sys_exit(), but this only allows for one stream of pyshark and does not allow for starting and stopping.

My code in the thread looks like this:

self.cap = pyshark.LiveCapture(interface = 'loopback', only_summaries=1, output_file = self.filename)
next(self.cap.sniff_continously()):
   
As I understand it, this is an infinite loop that really cannot be broken except ,as I mentioned, by running the thread as a daemon.

Anyway, creating an async def function and including the two lines (without self) is proving difficult

I have tried - 

cap = pyshark.LiveCapture(interface = 'loopback', only_summaries=1, output_file = filename)
task1 = asyncio.create_task(next(self.cap.sniff_continuously())):
await task1

I get a runtime error: LiveCapture._get_tshark_process' was never awaited

after putting an await on the LiveCapture line I get a Syntax error at output_file that says: cannot assign to await expression.

Please advise on a correction with asyncio or method to end the thread.

I am running pyshark version 0.4.2.11 and python version 3.8.5

Thank you!

**Comment by parz3val** [comment]
You need to put your await inside the async functions so they will be awaited. You shouldn't call await outside of async functions.
In my case, I am doing the same thing but I am using multiprocessing and keyboard module to handle the shutdown/startup, I can send in 'keypress' event and quit the program.

**Comment by tiwns** [comment]
> You need to put your await inside the async functions so they will be awaited. You shouldn't call await outside of async functions.
> In my case, I am doing the same thing but I am using multiprocessing and keyboard module to handle the shutdown/startup, I can send in 'keypress' event and quit the program.

Thank you for the reply, but I am not sure I understand. Here is my code:

async def sniffer():
    ...
    cap = pyshark.LiveCapture(interface='loopback', only_summaries=1, output_file=filename)
    next(cap.sniff_continuously())

Where should the await go?

**Comment by matan1008** [comment]
Usually I am subclassing the LiveCapture class:
```
class AsyncLiveCapture(pyshark.LiveCapture):
    async def sniff_continuously(self, packet_count=None):
        tshark_process = await self._get_tshark_process()
        psml_structure, data = await self._get_psml_struct(tshark_process.stdout)
        packets_captured = 0

        data = b''
        try:
            while True:
                try:
                    packet, data = await self._get_packet_from_stream(tshark_process.stdout, data,
                                                                      psml_structure=psml_structure,
                                                                      got_first_packet=packets_captured > 0)
                except EOFError:
                    self._log.debug('EOF reached (sync)')
                    self._eof_reached = True
                    break

                if packet:
                    packets_captured += 1
                    yield packet
                if packet_count and packets_captured >= packet_count:
                    break
        finally:
            if tshark_process in self._running_processes:
                await self._cleanup_subprocess(tshark_process)
```

And then you can just do 

```
cap = AsyncLiveCapture(interface='loopback', only_summaries=1, output_file=filename)
async for packet in cap.sniff_continuously():
    print(packet)
```

**Comment by clandestinenetworks** [comment]
yeah this really needs to be completely rewritten. There is no way to set the event loop, it just assumes that it will be the only event loop sort of the way you would expect an application to implement non-sharable resources except that its a python module, that behaves like an application that does exactly what I would use wireshark for ? I'm not sure how this is useful but ok.

**Comment by clandestinenetworks** [comment]
```
In [28]: pcap = pyshark.FileCapture("../test.pcap")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-16ab00286d99> in <module>
----> 1 pcap = pyshark.FileCapture("../hammers.pcap")

~/.local/share/virtualenvs/dosage-pXvM_igL/lib/python3.8/site-packages/pyshark/capture/file_capture.py in __init__(self, input_file, keep_packets, display_filter, only_summaries, decryption_key, encryption_type, decode_as, disable_protocol, tshark_path, override_prefs, use_json, output_file, include_raw, eventloop, custom_parameters, debug)
     33         :param custom_parameters: A dict of custom parameters to pass to tshark, i.e. {"--param": "value"}
     34         """
---> 35         super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
     36                                           decryption_key=decryption_key, encryption_type=encryption_type,
     37                                           decode_as=decode_as, disable_protocol=disable_protocol,

~/.local/share/virtualenvs/dosage-pXvM_igL/lib/python3.8/site-packages/pyshark/capture/capture.py in __init__(self, display_filter, only_summaries, eventloop, decryption_key, encryption_type, output_file, decode_as, disable_protocol, tshark_path, override_prefs, capture_filter, use_json, include_raw, custom_parameters, debug)
     79         self.eventloop = eventloop
     80         if self.eventloop is None:
---> 81             self._setup_eventloop()
     82         if encryption_type and encryption_type.lower() in self.SUPPORTED_ENCRYPTION_STANDARDS:
     83             self.encryption = (decryption_key, encryption_type.lower())

~/.local/share/virtualenvs/dosage-pXvM_igL/lib/python3.8/site-packages/pyshark/capture/capture.py in _setup_eventloop(self)
    155         else:
    156             try:
--> 157                 self.eventloop = asyncio.get_event_loop()
    158             except RuntimeError:
    159                 if threading.current_thread() != threading.main_thread():

/usr/lib64/python3.8/asyncio/events.py in get_event_loop(self)
    637 
    638         if self._local._loop is None:
--> 639             raise RuntimeError('There is no current event loop in thread %r.'
    640                                % threading.current_thread().name)
    641 

RuntimeError: There is no current event loop in thread 'MainThread'.

In [29]: 
```
this is not ideal at all but this would need to be modified to accept a loop parameter: 

```
In [29]: loop = asyncio.new_event_loop()
    ...: asyncio.set_event_loop(loop)
```
ideally you wouldn't need to do this at all but since async was kind of an afterthought in python that's more or less what you get.

**Comment by clandestinenetworks** [comment]
but yeah more or less the only reason this library would be useful, from my point of view is just so I don't have to do all of the tedious shit of struct unpacking a pcap file, offsets... which I started doing but I thought nah, since: 

`[pkt for pkt in self.pcap]`

is kinda exactly what I want that I'd go this route but it seems like all of this live capture crap is getting in the way of this otherwise horrendous task

**Comment by clandestinenetworks** [comment]
oh you know what, just noticed that eventloop parameter 
```
In [30]: pyshark.FileCapture?
Init signature:
pyshark.FileCapture(
    input_file=None,
    keep_packets=True,
    display_filter=None,
    only_summaries=False,
    decryption_key=None,
    encryption_type='wpa-pwk',
    decode_as=None,
    disable_protocol=None,
    tshark_path=None,
    override_prefs=None,
    use_json=False,
    output_file=None,
    include_raw=False,
    eventloop=None,
    custom_parameters=None,
    debug=False,
)
Docstring:      A class representing a capture read from a file.
Init docstring:
Creates a packet capture object by reading from file.

:param keep_packets: Whether to keep packets after reading them via next(). Used to conserve memory when reading
large caps (can only be used along with the "lazy" option!)
:param input_file: File path of the capture (PCAP, PCAPNG)
:param display_filter: A display (wireshark) filter to apply on the cap before reading it.
:param only_summaries: Only produce packet summaries, much faster but includes very little information.
:param decryption_key: Optional key used to encrypt and decrypt captured traffic.
:param encryption_type: Standard of encryption used in captured traffic (must be either 'WEP', 'WPA-PWD', or
'WPA-PWK'. Defaults to WPA-PWK).
:param decode_as: A dictionary of {decode_criterion_string: decode_as_protocol} that are used to tell tshark
to decode protocols in situations it wouldn't usually, for instance {'tcp.port==8888': 'http'} would make
it attempt to decode any port 8888 traffic as HTTP. See tshark documentation for details.
:param tshark_path: Path of the tshark binary
:param override_prefs: A dictionary of tshark preferences to override, {PREFERENCE_NAME: PREFERENCE_VALUE, ...}.
:param disable_protocol: Tells tshark to remove a dissector for a specific protocol.
:param use_json: Uses tshark in JSON mode (EXPERIMENTAL). It is a good deal faster than XML
but also has less information. Available from Wireshark 2.2.0.
:param output_file: A string of a file to write every read packet into (useful when filtering).
:param custom_parameters: A dict of custom parameters to pass to tshark, i.e. {"--param": "value"}
File:           ~/.local/share/virtualenvs/dosage-pXvM_igL/lib/python3.8/site-packages/pyshark/capture/file_capture.py
Type:           type
Subclasses:     

In [31]: 
```

just didn't see it in the docstring

**Comment by clandestinenetworks** [comment]
it actually is completely broken though there's no way to use this correctly in a script that has it's own event loop so the parameter does nothing so you have to run `    asyncio.create_task(Obj(pcap).run())` from __main__ which is un-awaitable.                                                                                   

there simply is no way to current loop in thread %r.

**Comment by clandestinenetworks** [comment]
no running event loop.

**Comment by clandestinenetworks** [comment]
yawwwwwn time to pick a new language

**Comment by clandestinenetworks** [comment]
coroutines more like bullshit routines

**Comment by clandestinenetworks** [comment]
this whole thing is really bad you should just re-write it dude. Just use a dict for the packet next time so you can use get() instead of bracket accessors the former doesn't throw needless exceptions if the key doesn't exist

**Comment by clandestinenetworks** [comment]
if you're trying to do something like layers you might look at how scapy does theirs instead of using a bracket accessor overload use '/'

**Comment by kyrlon** [comment]
IS there any other examples for this?
