### ISSUE TITLE
Weird sniff_timestamp format

### ISSUE THREAD

**Issue by flying-sheep** [KimiNewt/pyshark#449]
When parsing packets from XML, this field is some weird string instead of a timestamp as intended:

```py
>>> pkg.sniff_timestamp
'Nov 30, 2020 13:32:00.129866518 CET'
```

What is it? It’s not [RFC 2822](https://docs.python.org/3/library/email.utils.html) and not ISO, so how get a parsed datetime out of it?

**Comment by harrypotterlord** [comment]
Use can parsing like this: 
import datetime
sniff_time = datetime.datetime.strptime(pkg.sniff_timestamp, '%b %d, %Y %H:%M:%S.%f518 %Z')

**Comment by flying-sheep** [comment]
How was this fixed?

**Comment by KimiNewt** [comment]
`pkt.sniff_timestamp` now returns an epoch time, and `pkt.sniff_time` returns a datetime object.
