### ISSUE TITLE
Is there any problem to sniff for long periods of time?

### ISSUE THREAD

**Issue by DamyHao** [KimiNewt/pyshark#464]
I want to use pyshark to sniff packets in real time for long periods of time (1 year or more). I don't want it to create any type of file. Is it possible or it will cause problems like tshark does?

**Comment by KimiNewt** [comment]
Since this uses tshark, it will unfortunately cause memory issues when running over a very long period of time. While soemthing can be done inside, I suggest that you close and reopen the capture if you're planning on running for a year.
