### ISSUE TITLE
Get raw binary frame

### ISSUE THREAD

**Issue by zaralger** [KimiNewt/pyshark#49]
Hi ! 
I'm sorry if my question may appear simplist, I may have missed the method.
Is there a nice way to get a raw binary string "010111000" of the received frames from pyshark ? 

Thanks in advance !

**Comment by mattaereal** [comment]
Hi, how have you handled this issue? I need to export some packets to a pcap/-ng file and I can't find a way at the moment.

**Comment by MisunderstoodSalad** [comment]
Take a look at pypkt it's a python package build for that
https://github.com/MisunderstoodSalad/Pypkt

**Comment by Ahmed-Hussein-Karam** [comment]
Sure, it is possible. Have a look [here](https://stackoverflow.com/questions/54904784/how-to-convert-pyshark-packet-to-binary-value) and [here](https://stackoverflow.com/a/54905981/7280140)

**Comment by mattaereal** [comment]
This has been added a year ago and should be closed.
