### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by neilwillgettoit** [KimiNewt/pyshark#50]
building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/libxml2 -I/tmp/pip_build_root/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -L/usr/local/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so

/usr/bin/ld: cannot find -lz

collect2: error: ld returned 1 exit status

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by bbayles** [comment]
I'd guess this is a problem with your build environment and not a bug with pyshark. Check out [this thread](http://serverfault.com/a/481861/89174) to see if its recommendation solves your problem?

**Comment by neilwillgettoit** [comment]
That ended up being it. I had to force reinstall zlib on 
>$ lsb_release -a 
>Distributor ID: Ubuntu
>Description:    Ubuntu 14.04.1 LTS
>Release:        14.04
>Codename:       trusty

 with

>apt-get install --reinstall zlibc zlib1g zlib1g-dev

**Comment by bbayles** [comment]
That's good news. I suppose the issue can be closed?
