### ISSUE TITLE
Source code missing from pypi 0.4.4 release

### ISSUE THREAD

**Issue by goatgoose** [KimiNewt/pyshark#520]
Hello,

I believe your source code and setup.py files are missing from your pypi 0.4.4 release. See the following comparison between 0.4.3 and 0.4.4:

<img width="920" alt="Screen Shot 2022-01-25 at 18 35 14" src="https://user-images.githubusercontent.com/3758302/151077862-f76e18a6-cc11-40bf-b88b-ef95af0661e2.png">

**Comment by wonderwoman-dev** [comment]
Yes, this is a problem and seems quite simple to fix.

**Comment by KimiNewt** [comment]
Fixed
