### ISSUE TITLE
The pyshark output is flat and has no hierarchy

### ISSUE THREAD

**Issue by Lisixbuff** [KimiNewt/pyshark#524]
hello,when i use pyshark parsing packet, I found that using all_fields property and output like this:
"tcp": {
		"tcp.options": "02:03:05:b4:01:03:03:05:01:04:02:02",
		"tcp.options.mss": "02:02:03:b4",
		"tcp.option_kind": ["2", "1", "3", "1", "1", "4"],
		"tcp.option_len": ["4", "3", "2"],
		"tcp.options.mss_val": "1460",
		"tcp.options.nop": ["01", "01", "01"],
		"tcp.options.wscale": "03:03:08",
		"tcp.options.wscale.shift": "8"
	}
it is flat , so i do not know hierarchy output like this:
"tcp": {
              "tcp.options": "02:03:05:b4:01:03:03:05:01:04:02:02",
              "tcp.options_tree": {
                          "tcp.options.mss":  "02:02:03:b4",
                          "tcp.options.mss_tree": {
                            "tcp.option_kind": "2",
                            "tcp.option_len": "4",
                            "tcp.options.mss_val": "1460"
                          },
                          "tcp.options.nop": "01",
                          "tcp.options.nop_tree": {
                            "tcp.option_kind": "1"
                          },
}
i want get result have hierarchy.
my english is not good , can you understand what i mean?
thank you!

**Comment by KimiNewt** [comment]
I'm not exactly sure what you mean, but I reckon the new EK mode might help you. Try `use_ek=True` when constructing the Capture.
