### ISSUE TITLE
load `tshark` executable returned by `which tshark`

### ISSUE THREAD

**Issue by goretkin** [KimiNewt/pyshark#53]
On my system I have two versions of tshark. The one I get from typing `tshark` in bash is not the one that pyshark is loading because of the difference between the search order and my path environment variable order.

I don't suspect it's a common problem, but in my case it would be more intuitive to search for tshark first in the path and then in the default locations.

**Comment by bbayles** [comment]
@goretkin, could you try [my branch](https://github.com/bbayles/pyshark/tree/which-tshark)? I think this is a good idea.

**Comment by goretkin** [comment]
@bbayles thanks! `which` will return a new-line terminated path, so that needs to be stripped. Also `check_output` needs to be qualified. Then it works great!

```
@@ -36,7 +36,7 @@ def get_tshark_path():
     # `which tshark`, common paths.
     else:
         try:
-            which_tshark = check_output(['which', 'tshark']).decode('ascii')
+            which_tshark = subprocess.check_output(['which', 'tshark']).decode('ascii').strip()
         except subprocess.CalledProcessError:
             pass
         else:
```

**Comment by bbayles** [comment]
I like @baszoetekouw's method better than mine - I've replaced my method with mine, and added it to #58.

@baszoetekouw and @goretkin, I will merge these on Wednesday morning unless @KimiNewt has some objection.

Thanks!
