### ISSUE TITLE
output of `tshark -D` needs to be parsed differently

### ISSUE THREAD

**Issue by goretkin** [KimiNewt/pyshark#54]
In my version of tshark (1.12.3), the output of the command may have changed.

```
In [2]: pyshark.tshark.tshark.get_tshark_interfaces()
Out[2]: [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11']

In [3]: exit()
~/nidaq$ tshark -D
1. wlan0
2. vmnet1
3. vmnet8
4. any
5. lo (Loopback)
6. nflog
7. nfqueue
8. dbus-system
9. dbus-session
10. usbmon1
11. usbmon2
```

**Comment by bbayles** [comment]
I think the discussion in #57 took care of this. I've added tests for the function in #58. I'll close this issue once the latter is merged.

**Comment by bbayles** [comment]
Closing this, since #58 adds a [docstring](https://github.com/KimiNewt/pyshark/blob/d7c5e89d2225f133c82007deff4c20af2a27d8d6/src/pyshark/tshark/tshark.py#L67) to explain the usage of `get_tshark_interfaces`.
