### ISSUE TITLE
RuntimeError : Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by mathieu91540** [KimiNewt/pyshark#542]
I got this message after trying like your test in the README file.

Here is my code : 
`import pyshark

cap = pyshark.FileCapture(r"C:\Users\cache\Desktop\vlp16capture.pcap")
cap

print(cap[0])`

**Comment by KimiNewt** [comment]
It's likely you are running it in jupyter or something else that runs on an eventloop. Unfortunately since pyshark uses asyncio it's not possible to run it inside jupyter at the moment.
