### ISSUE TITLE
Feature Request: CHANGELOG File

### ISSUE THREAD

**Issue by markgras** [KimiNewt/pyshark#549]
This is a repeat of issue #396, which was closed due to old age but never addressed.

## Problem
It appears as though the only place to find release notes is https://github.com/KimiNewt/pyshark/releases. However, this doesn't contain full notes for releases. The latest 5 releases, for example, only state that the package version number was bumped. Changes can be discovered by treading through commits, but this is time consuming and may be difficult for Python/Git beginners.

## Proposed Solution
Add a new `CHANGELOG.md` file in the package's top-level directory that for each release contains:
- version number
- date
- what is new, changed, fixed, a known issue, etc. (I find that [Firefox](https://www.mozilla.org/en-US/firefox/101.0/releasenotes/) release notes are a good example)

**Comment by KimiNewt** [comment]
I elected to update the release notes in the releases page instead, and will keep updating it there: https://github.com/KimiNewt/pyshark/releases/tag/v0.4.6
Going over past releases and updating them is a bit much, so I did it only for the latest one.

I don't see a reason to duplicate it with a changelog in the repo itself, unless to link to the github releases page.

**Comment by markgras** [comment]
I do not know how I missed those notes for the latest release; I just saw the 5 blank entries before that. I agree with your take on avoiding duplication. I appreciate you compiling release notes for the latest release. Thank you!
