### ISSUE TITLE
capture stderr and exit code from tshark

### ISSUE THREAD

**Issue by goretkin** [KimiNewt/pyshark#55]
I don't know where to incorporate it, but I think the tshark process' stderr should be logged and possibly displayed in the event that tshark exits with a failure. Currently, the default is to be completely silent if the interface isn't accessible (because of permissions or non-existance), for example.

EDIT I just found this discussion https://github.com/KimiNewt/pyshark/issues/26

**Comment by KimiNewt** [comment]
An exception will now be raised when trying to read from tshark if it has crashed, even it didn't appear to crash initially.
I also added a set_debug() method to Capture so these sort of problems can be debugged.

We may want to change the redirection of stderr to /dev/null to our own pipe, to avoid the user having to run his method twice, if I can think of a nice to do that that will be added as well.
