### ISSUE TITLE
Interface 'wlan' does not exist in LiveCapture

### ISSUE THREAD

**Issue by miaotony** [KimiNewt/pyshark#568]
**Describe the bug**

When calling `LiveCapture` and pass parameter `interface='wlan'`, the pyshark will throw an `UnknownInterfaceException` and then exit.

```
2022-07-08 23:41:31,466 - LiveCapture - DEBUG - Creating Dumpcap subprocess with parameters: D:/Program Files/Wireshark/dumpcap.exe -q -i wlan -w -
2022-07-08 23:41:31,472 - LiveCapture - DEBUG - Dumpcap subprocess (pid 11900) created
Traceback (most recent call last):
  File "1.py", line 289, in <module>
    cap.apply_on_packets(tshark_callback)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 245, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "D:\Programs\Anaconda\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 254, in packets_from_tshark
    tshark_process = await self._get_tshark_process(packet_count=packet_count)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\live_capture.py", line 105, in _get_tshark_process
    tshark = await super(LiveCapture, self)._get_tshark_process(packet_count=packet_count, stdin=read)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 313, in _get_tshark_process
    self._verify_capture_parameters()
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\live_capture.py", line 76, in _verify_capture_parameters
    f"Interface '{each_interface}' does not exist, unable to initiate capture.")
pyshark.capture.live_capture.UnknownInterfaceException: Interface 'wlan' does not exist, unable to initiate capture.
```

**To Reproduce**

```python
import pyshark

cap = pyshark.LiveCapture(interface='wlan')
cap.set_debug()
cap.apply_on_packets(tshark_callback)   # tshark_callback is a callback function
```

**Expected behavior**

Capture packages from specific interface with its name.

**Versions (please complete the following information):**
- OS: Windows 10
- pyshark version: v0.4.6+ 80faffc7879fc49b2ef9a2aa9a3cd461247a1094 from GitHub
- tshark version: TShark (Wireshark) 3.6.6 (v3.6.6-0-g7d96674e2a30)

**Comment by KimiNewt** [comment]
Can you run `ipconfig`? Is that the full name of your interface?

**Comment by miaotony** [comment]
Let me talk about something I have found...

From the diff and traceback info we can see that `_verify_capture_parameters` is called before calling tshark.

![图片](https://user-images.githubusercontent.com/41962043/178032431-27867a65-9972-481d-a22d-74cfa99af273.png)

https://github.com/KimiNewt/pyshark/compare/v0.4.6...master#diff-858d2dcc99c3206bdaea8e222cda53a7a8aad134c80d5ec0998d2e917dd29ff3R57-R77

![图片](https://user-images.githubusercontent.com/41962043/178032348-565db22e-d259-4ea0-9f5a-921d9d2f75fb.png)

https://github.com/KimiNewt/pyshark/compare/v0.4.6...master#diff-9db5fbd6d77d806b1e066fc1cbd5d98ac2e667256a0de128c297b00ce41f6021R313

And `_all_interfaces` is from `get_tshark_interfaces`, which calls `tshark -D` to get the possible interfaces.

![图片](https://user-images.githubusercontent.com/41962043/178032896-49ac3b62-d326-4a04-8e67-f988b87b5659.png)

The results like below. `line.split(" ")[1]` returns info like `\Device\NPF_{XXXXXXXXXXXXXXXXXXXX}`, which is suitable for dumpcap.

![图片](https://user-images.githubusercontent.com/41962043/178033056-91480a8c-4a0d-4446-b529-23e5aa75f0b7.png)

However, when a user provides his own interface from input, just like `wlan`, using this function as check will directly raise `UnknownInterfaceException`, since `wlan` is not in the list of `\Device\NPF_{XXXXXXXXXXXXXXXXXXXX}`. That's why this bug happens.

**Comment by miaotony** [comment]
> Can you run `ipconfig`? Is that the full name of your interface?

In v0.4.6 this bug doesn't happen.

**Comment by KimiNewt** [comment]
I wonder if it's sufficient to take the alias of the interface (as shown in parenthesis) or simply skip this check and let tshark crash. I think the latter is not as nice for the user but it's safer.

**Comment by KimiNewt** [comment]
Fixed in master by also looking at the aliases of interfaces
