### ISSUE TITLE
lost packet

### ISSUE THREAD

**Issue by omides248** [KimiNewt/pyshark#580]
Hello I am capturing on RTP packets, but in Python code, I lose packets with a big difference, if I do not have this problem in the command line and directly with tshark and tcpdump. Have I made a mistake in the Python code?

Python 3.6.9
TShark (Wireshark) 3.6.5 (Git v3.6.5 packaged as 3.6.5-1~ubuntu18.04.0+wiresharkdevstable)
pyshark==0.4.3

------------------------------

**Command line:**
`tshark -a duration:10 -f "port 100" -i enp1s0`

**Output:**
```
47932 packets captured
```

------------------------------

**Command line:**
`tcpdump -G 10 -i enp1s0 port 100 -vv -W 1 -w /home/adminz/test.pcap`

**Output:**
```
47227 packets captured
47496 packets received by filter
```
----------------------------

**test.py**
```
import pyshark

c = pyshark.LiveCapture(interface="enp1s0", bpf_filter="port 100")
c.sniff(timeout=10)
print(c)
```

Output:
```
<LiveCapture (7687 packets)>
```

**Comment by p00f** [comment]
Hey, why did you close this issue? Did you find a fix?
