### ISSUE TITLE
Getting error when using on windows with python 2.7

### ISSUE THREAD

**Issue by adnan2911** [KimiNewt/pyshark#60]
Hi, 

Thanks for making this tool 

Actually i dont have choice and I need to use it on windows. But i am getting this error. Can you please help what I am doing wrong ? Also i beginner 

![image](https://cloud.githubusercontent.com/assets/10854296/6220257/ea977518-b5f9-11e4-80cb-6aa1945bcede.png)

**Comment by bbayles** [comment]
`logbook` is now required by the `pyshark.capture.capture` (previously it was only required for tests).

The `setup.py` script should have installed it automatically, but you can try to install it from the command line: `C:\python27\python.exe -m pip install logbook`.

If you don't have pip installed, see [here](https://pip.pypa.io/en/latest/installing.html).

**Comment by adnan2911** [comment]
Hi, 

I installed logbook as you suggested.. Then it was giving error 'No trollius found'.. I was also able to install it. But now it shows 'no module named py'.. I did some research on internet but wasnt able to figure it out. Can you please help 

![imporerror](https://cloud.githubusercontent.com/assets/10854296/6233190/dd82e644-b696-11e4-9c10-4f8fc7652780.png)

**Comment by goretkin** [comment]
It looks like the `py` module is used for parsing the .ini file. You should just need to install the `py` module.

https://pypi.python.org/pypi/py

**Comment by adnan2911** [comment]
hi.. 
thanks !.. i finally got it working on windows.. 

I still have one query if you can kindly help me

I am running following basic code


----------------------------
import pyshark
capture = pyshark.LiveCapture(interface='2',bpf_filter ='sctp')


for packet in capture.sniff_continuously(packet_count=None):
        print 'Just arrived:', packet.s1ap.ENB_UE_S1AP_ID
----------------------------        

Now the above code gives error.. i think its because s1ap.ENB_UE_S1AP_ID field is not present in every packet... Is there anyway i can include condition in the code that it shows this field value only if it is present otherwise ignore ? 

Thanks

**Comment by goretkin** [comment]
http://stackoverflow.com/questions/610883/how-to-know-if-an-object-has-an-attribute-in-python

**Comment by adnan2911** [comment]
Hi, 

that post helped !

hasattr didnt work for me

![image](https://cloud.githubusercontent.com/assets/10854296/6237938/aa8a3eec-b6bc-11e4-90f8-8a582c4d9cd5.png)

but try and except worked

![image](https://cloud.githubusercontent.com/assets/10854296/6237948/c3bee0e8-b6bc-11e4-9170-8be7f32caf0d.png)

did i do anything wrong with hasattr ?

**Comment by goretkin** [comment]
These are general python programming questions, so you should probably be asking in another forum.

But the problem is that `s1ap` is an attribute of `packet`, and `m_TMSI` is an attribute of `s1ap`. You are thinking that there is a single attribute called `s1ap.m_TMSI`. An attribute in python cannot contain `. `, otherwise it would be ambiguous what `a.b.c` means.

**Comment by Nomii5007** [comment]
@adnan2911 how did you install pyshark and resolve your issue? I am having same error i installed logbook then try to install pyshark using this command `pip install pyshark`  it is giving `error command cl,exe failed no such directory and file`

**Comment by znittzel** [comment]
Hello!

Does someone knows how to get the Encrypted Application Data from the SSL-layer?

Here's an example when I caught a package containing encrypted data I want to extract. 
Layer SSL:
	Encrypted Application Data: 11e936c8e47b26dfa4f808afa013b669c991deda0bb65851...
	Length: 64
	Version: TLS 1.2 (0x0303)
	TLSv1.2 Record Layer: Application Data Protocol: spdy
	Content Type: Application Data (23)

Thank you for your help!
