### ISSUE TITLE
pyshark requirement py - vulnerability flagged

### ISSUE THREAD

**Issue by shel1kest0learn** [KimiNewt/pyshark#610]
**Describe the bug**
Ran pip-audit, output indicated:
Found 1 known vulnerability in 1 package
Name Version ID Fix Versions
---- ------- ------------------- ------------
py   1.11.0  GHSA-w596-4wvx-j9j6

**To Reproduce**

**Expected behavior**

**Versions (please complete the following information):**
 - OS: Android 
 - pyshark version: 0.5.3
 - python 3.11

**Example pcap / packet**

**Comment by pianofab** [comment]
See  [this clever hack let me kill py (intermediate) anthony explains #493](https://youtu.be/aZS3_-y6vsg)

**Comment by pianofab** [comment]
It looks like merging https://github.com/KimiNewt/pyshark/pull/575 will fix this issue as a side effect

**Comment by ddelnano** [comment]
@KimiNewt are there any plans to create a new pypi release soon? I'm interested in pulling in the change mentioned above to avoid the vulnerability.

**Comment by KimiNewt** [comment]
Yes. I'll do so soon (and ill add some contributers too because as you can see I don't have much time for the project at the moment)
