### ISSUE TITLE
missing release tags / files

### ISSUE THREAD

**Issue by anthraxx** [KimiNewt/pyshark#62]
Hey,

For packaging purpose it would be awesome if you can create git tags for all versions (like the missing 0.3.3 for example). Currently there is only a release for 0.3 (but not the most current one).
Pushing git tags will make github store a tarball that can be downloaded to build the package.
It would be awesome, as the pypi package does not contain the tests and in the packaging step it would be cool to also include your tests :smile:

PS: when do you plan to bump to 0.3.4? :yum:

cheers
anthraxx

**Comment by KimiNewt** [comment]
There you go! Added to pypi as well

**Comment by anthraxx** [comment]
cool, thank you very much! :smile: :+1:
