### ISSUE TITLE
OSPF duplicated layers

### ISSUE THREAD

**Issue by vityca** [KimiNewt/pyshark#646]
During analysis of ospf LS update packet I want to get all routers  that named 'Attached Router'. But I can get only the first one in packet
I just can't use this field for my ideas.

For understanding, I'm create a network map with passive sniffer. And I need to use all duplicated 'Attached Router' field for my map

**Versions:**
 - OS: Windows
 - pyshark version: 0.5.3

![example](https://user-images.githubusercontent.com/95777561/227185149-b64f300b-97cc-40ca-9a96-fd0b7307902c.jpg)

**Comment by KimiNewt** [comment]
If you are using the default XML mode, you can access the alternate values by using `pkt.ospf.lsa.network.attchrtr.all_fields`
