### ISSUE TITLE
where is param bpf_filter?

### ISSUE THREAD

**Issue by phith0n** [KimiNewt/pyshark#69]
I can't find param bpf_filter in __init__ function of FileCapture?
So I got a "TypeError: __init__() got an unexpected keyword argument 'bpf_filter' " error.

**Comment by KimiNewt** [comment]
It only exists on LiveCaptures at the moment.
IIRC, there was some problem when running it on FileCaptures, though I don't remember what it was-- so I'll try and check that out.

In the meanwhile, you can use the "display_filter" option, which is the standard wireshark filters (i.e. "http"). They're much more powerful, albeit slower.

**Comment by r2evans** [comment]
I appreciate the work you have done to deploy and maintain pyshark. However, perhaps you should remove the use of `bpf_filter` from your examples of `FileCapture`?

I don't think this is a pedantic request: there are two ways I learn about packages/modules: I read the docs and I read the source. I understand completely that it may be difficult to implement, and though I would prefer to have it than not, the docs and source are misleading.

**Comment by KimiNewt** [comment]
@r2evans Done.

**Comment by r2evans** [comment]
Thanks! Good luck implementing it, I know it can be problematic. (I apologize for not being able to contribute much to it; though my python isn't terrible, my time and proficiency are not where they need to be to be of much help to you.)
