### ISSUE TITLE
Is there anyway to set max pcap file size?

### ISSUE THREAD

**Issue by KSroido** [KimiNewt/pyshark#712]
**Is your feature request related to a problem? Please describe.**
In cli version of tshark and tcpdump, you could use `-C` arg to limit the size of pcap file
is there anyway to do so with using pyshark?
thx in advance

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bnt2025** [comment]
You can use

**Comment by KSroido** [comment]
thanks for advice：）
