### ISSUE TITLE
Fix typo in UnknownEncyptionStandardException class

### ISSUE THREAD

**Issue by ryanthomasharrison** [KimiNewt/pyshark#715]
**Is your feature request related to a problem? Please describe.**
In capture.py there is a class named UnknownEncyptionStandardException, but there appears to be a typo in the word "Encryption"

**Describe the solution you'd like**
Rename class as UnknownEncryptionStandardException

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2024-11-18 at 5 02 07 PM](https://github.com/user-attachments/assets/4a3dfc93-40dd-454e-9dc9-75db0c93fc71)

**Comment by jmiah717** [comment]
I would be happy to take a look at this and fix the typo. Would that be okay?
