### ISSUE TITLE
How to get posted content from POST request

### ISSUE THREAD

**Issue by Minzc** [KimiNewt/pyshark#79]
Hi,

I'm trying to parse POST request and want to extract posted content from those requests. Some of those contents are json strings. 

What I got using pyshark is something like this. 

``` Json
Layer JSON:
    Member Key: "userid"
    Object
    String value: 14230381863292564
    Array
    Member Key: "game"
    Member Key: "version"
    Member Key: "othergames"
    String value: com.droidhang.ph
    String value: 2
    String value: com.droidhang.ph
    String value: stericson.busybox
    String value: phongit.quickreboot
```

What I hope to get is the original  json string, like

``` Json
{
"userid": "14230381863292564",
"game": "com.droidhang.ph",
"version": "com.droidhang.ph",
"othergames": 
                      [
                         "com.droidhang.ph",
                         "stericson.busybox",
                         "phongit.quickreboot"
                       ]
}
```

Could you please give me some help?

**Comment by KimiNewt** [comment]
Can you upload an example capture file somewhere?

**Comment by Minzc** [comment]
Sure. 
The file is https://www.dropbox.com/s/avhd2exe7u2ppfj/json_sample.pcap?dl=0

**Comment by KimiNewt** [comment]
Unfortunately, this is due to the JSON dissector of wireshark/tshark, which doesn't output the raw data. You can disable the dissector in your configuration as seen here: https://ask.wireshark.org/questions/9544/how-to-disable-dissectors-in-tshark

Otherwise, the only option would be to "rebuild" the json according to what the dissector does place.

**Comment by nealmcb** [comment]
This is a big issue for me.  Has the situation gotten any better?

I also don't see how to disable the dissector - the hints at the link provided are incomplete, and I've had no luck finding or creating a `disabled_protos` file.

I'm using wireshark/tshark version 1.12.1 on Ubuntu Trusty.
