### ISSUE TITLE
Double VLAN detection

### ISSUE THREAD

**Issue by radinsky** [KimiNewt/pyshark#80]
How can you get a list of vlans if you have more than one, for example if i have this packet..

Layer ETH:
    Destination: 00:99:88:77:66:55 (00:99:88:77:66:55)
    .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Address: 00:99:88:77:66:55 (00:99:88:77:66:55)
    .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: 802.1Q Virtual LAN (0x8100)
    Source: 00:11:22:33:44:55 (00:11:22:33:44:55)
    .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
    Address: 00:11:22:33:44:55 (00:11:22:33:44:55)
    .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
Layer VLAN:
    ...0 .... .... .... = CFI: Canonical (0)
    000. .... .... .... = Priority: Best Effort (default) (0)
    .... 0000 1100 1000 = ID: 200
    Type: 802.1Q Virtual LAN (0x8100)
Layer VLAN:
    Trailer: 8dbdde29
    ...0 .... .... .... = CFI: Canonical (0)
    000. .... .... .... = Priority: Best Effort (default) (0)
    .... 0000 0110 0100 = ID: 100
    Type: IP (0x0800)
Layer IP:
    ....
Layer UDP:
    ....

if I use pyshark i got only inner vlan.

>>> print cap[0]['vlan'].id
100

I expect to get it the same as tshark :

tshark -r filename.pcap -T fields -e vlan.id
100,200

**Comment by KimiNewt** [comment]
Can you post an example capture file somewhere?

**Comment by radinsky** [comment]
You can use this sample packet:
https://www.cloudshark.org/captures/0001ea66142f

**Comment by KimiNewt** [comment]
Well, there isn't a very good way to do it at the moment, but they can be accessed via layer index.

You can use ```vlan1, vlan2 = pkt[1], pkt[2]``` or more explicitly ```vlan1, vlan2 = pkt.layers[1], pkt.layers[2]``` to access them. 

Fields can then be accessed normally: 
```python
print pkt[1].id
>>> '200'

if pkt[2].id.int_value > 150:
   pass
```

**Comment by radinsky** [comment]
`vlan1, vlan2 = pkt.layers[1], pkt.layers[2]`

but what if the packet has only one vlan? then vlan2 will equal ip layer in your case...

**Comment by KimiNewt** [comment]
If you don't know that all the packets have double vlan, you can run this code to get all vlan layers in a packet (in order):

vlan_layers = [layer for layer in a.layers if layer.layer_name == 'vlan']

**Comment by radinsky** [comment]
In my case I only need to validate that packets arrived without double vlan so I figured to check it by
`pkt.layers[2] != 'vlan'`
It doing its job but as I mentioned I was exptected to get 
`print cap[0]['vlan'].id
100,200`

**Comment by KimiNewt** [comment]
You can also do

```python
vlan_layers = [layer for layer in pkt.layers if layer.layer_name == 'vlan']
if len(vlan_layers) == 2:
    pass
```

Getting a list (or a string) instead of a single ID will be very confusing and will require type checking by anyone who uses the vlan normally.
I was considering adding custom layer attributes, so a vlan could have an attribute that allows it to access vlan layers that came before it, or something similar.

**Comment by radinsky** [comment]
>Getting a list (or a string) instead of a single ID will be very confusing and will require type checking by anyone who uses the vlan normally.

Yes, good point. 
Anyway I thinking as well my future test packets will have double ip header, dslite 4-6 and etc. so the best for me will be to write proprietry functions to my needs.
Thanks for the help and excellent work!

**Comment by KimiNewt** [comment]
I did not realise this happened often (outside of double vlans).
I added the get_multiple_layers() function to the Packet object  which should be of help to you, instead of using the above code.

You can do:
```python
if len(pkt.get_multiple_layers('vlan')) == 2: # Case insensitive
    pass
```
