### ISSUE TITLE
How can I print the s1ap or x2ap layer's fileds like wireshark

### ISSUE THREAD

**Issue by origin4u** [KimiNewt/pyshark#85]
I want to print out some protocol's fields(s1ap, x2ap, etc..)like wireshark's detail view.
The wireshark's detail view is composing the protocols relative position(like tree) thus it can be easy to read and understand among the fields's relation. 
It is probably due to follow the ASN.1 PER rules.
Once I try using the "pretty_print()" method then the output is unsorted and not tree style.
Is it possible to print like wireshark's detail view. (ASN.1 PER decoding style)

**Comment by KimiNewt** [comment]
I'm unfamiliar with the protocol, can you post an example capture file?
