### ISSUE TITLE
How to get raw request POST data

### ISSUE THREAD

**Issue by erhan-** [KimiNewt/pyshark#86]
Hey KimiNewt,

can you tell me how I can read the raw POST-data of a HTTP Package?

I have set display_filter='http.request.method == "POST"'  and can read parameters out with .ip.src  , .http.user_agent etc but I'm not sure how I can read the POST-Values.

There is .media and .data which show me things like:

Layer MEDIA:
        Media Type: application/octet-stream (123 bytes)

But from there on I don't know how I can get deeper as I need to read out the raw 123 bytes in this case.

I hope you can help me. Thank you!

**Comment by erhan-** [comment]
I found the data with something like:
> payload = cap[0].data.tcp_reassembled_data.split('0d:0a:0d:0a:')[1].split(":")

**Comment by eulerscripter** [comment]
Any other way to achieve this?
