### ISSUE TITLE
I need both summaries and decode in class packet

### ISSUE THREAD

**Issue by laoyang103** [KimiNewt/pyshark#88]
Dear Dor Green:
    I am new use pyshark, I need both summaries and decode message in class Packet. I try to read your code to do it, but I am new to python, can you help me ? Thanks a lot !!!

**Comment by KimiNewt** [comment]
If what you mean is that you want both access to the Packet Summary class and the packet data fields, that can not be done with a single class at the moment (since tshark only allows one at a time).

You can, however, do this:

```python
packets = pyshark.FileCapture('/path/to/cap')
summaries = pyshark.FileCapture('/path/to/cap', only_summaries=True)

for packet, summary in zip(packets, summaries):
    print summary
```

"Zip" simply takes on item from each iterator.

**Comment by laoyang103** [comment]
OK, I understand it was tshark's reason.Thank you very much!

**Comment by dog-2** [comment]
i also want to get both summary and detail of the packets, but the code does't works well in current version 0.3.6.2:

```python
packets = pyshark.FileCapture('/path/to/cap')
summaries = pyshark.FileCapture('/path/to/cap', only_summaries=True)

for packet, summary in zip(packets, summaries):
    print summary
```

When running the program will halt at the for statement and will never goes into it and won't print anything.
i've debugged into the source code and found that the code halt at the first line of the function _packets_from_tshark_sync() in pyshark/capture/capture.py, which is:

```python
tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
```

I guessed something wrong with multiple tshark process I/O handling in pytshark but i could not solve it.

One alternative but imperfect solution is that get summaries and detail separately and save each result in separate temp vars and finally join together through the same packet sequence number. The disadvantage is that the tow temp vars cost large memory if the input pcap file contails a large number of packets.

I really want to iterator the summaries and details simultaneously cos big pcap file should be processed and the memory saving really counts in my project.
