### ISSUE TITLE
Frame length in bits

### ISSUE THREAD

**Issue by sleighsoft** [KimiNewt/pyshark#89]
How to get the frame length in bits?
```
Layer FRAME:
	Frame Number: 12
	Time delta from previous captured frame: 0.002989000 seconds
	Time shift for this packet: 0.000000000 seconds
	Time delta from previous displayed frame: 0.027051000 seconds
	Arrival Time: Jul 10, 2015 03:50:33.656518000 PDT
	Encapsulation type: Ethernet (1)
	Frame is marked: False
	Time since reference or first frame: 0.032679000 seconds
	Frame is ignored: False
	Capture Length: 1298 bytes (10384 bits)
	Frame Length: 1298 bytes (10384 bits)
	Epoch Time: 1436525433.656518000 seconds
	Protocols in frame: eth:ip:tcp:ssl
	Interface id: 0
```

`print cap[1].frame_info.cap_len` prints only the length in bytes.

**Comment by KimiNewt** [comment]
The tshark XML does not supply the number in bits. It only appears in the nice frame description. 
We could add a custom class for frame_info, however this is just multiplying by 8-- so I don't think it's worth it. The users can easily do that themselves.

**Comment by sleighsoft** [comment]
I would like to extract the frame length in bits for a research about compression based SSL/TLS attacks.
Therefore merely multiplying by 8 does not yield the correct value as the 'nice frame description' is a rounded number.

**Comment by KimiNewt** [comment]
So the "nice frame description" is incorrect? If so, then that means tshark does not output that data-- meaning we can't read it. That means we can't have this feature unless we read the packet data ourselves, which we don't do (though we might in the future-- it could help with other issues as well).
