### ISSUE TITLE
Additional options to tshark command?  E.g. nfs.file_name_snooping

### ISSUE THREAD

**Issue by cstacey42** [KimiNewt/pyshark#96]
Hi,

Awesome tool - thank you.

I would like to send a couple of options to tshark to get it to do a little deeper analysis of NFS packet captures.

I have not yet found a way to do that as a param to any of the pyshark capture methods.

I am able to achieve what I want with an ugly hack of tshark/tshark.py...

```
# diff tshark/tshark.py.orig tshark/tshark.py
112c112
<         return '-R'

---
>         return '-o "nfs.file_name_snooping:TRUE" -o "nfs.file_full_name_snooping:TRUE" -o "nfs.fhandle_find_both_reqrep:TRUE" -R'
```

Have I missed a designed way to do this?

If not, please consider this a feature request for an optional parameter to set these options.

Thanks,
Chris

**Comment by KimiNewt** [comment]
Been possible for a while now
