### ISSUE TITLE
Using pyshark in script file

### ISSUE THREAD

**Issue by cybercuffs** [KimiNewt/pyshark#97]
The module works in the interpreter but doesn't work when I use it in the script and gives the following error.

capture = pyshark.FileCapture('test.pcap')
AttributeError: 'module' object has no attribute 'FileCapture'
Or 
capture = pyshark.LiveCapture(interface="en0")
AttributeError: 'module' object has no attribute 'LiveCapture'

Although, I am importing pyshark in my script...

**Comment by san1ker** [comment]
I just got same situation

but after I changed project directory on C:\, problem solved

Is your project directory is in D:\?????

**Comment by ernea** [comment]
I am facing the same problem. I successfully captured the packets, parsed it and store in db but suddenly I got this error.
    
                        AttributeError: module 'pyshark' has no attribute 'LiveCapture'

 Also there is no change in code . Then, I uninstalled pyshark and  reinstalled it but no success. Then I change the project directory as mentioned in the comment by san1ker (although it doesn't make any sense) but still I have the same issue. Please help if possible.

**Comment by engp0958** [comment]
I faced the same problem as it requires python version above 3.5.  I solved it by:
1. sudo apt-get install python3.5
2. sudo apt-get install python3-setuptools
3. add at top of setup.py with #! /usr/bin/env python3
4. python3 setup.py install
hope it is helpful.

**Comment by lucidGH** [comment]
same issue, windows, python 3.7.2, idk what to do

**Comment by IAMABOY** [comment]
check if it is issues of Administrator privileges .For example,if you pip install pyshark in linux using root  privilege,then you run code using general user  authority.then python will show  AttributeError: module 'pyshark' has no attribute 'FileCapture'.

solution:
chmod -R 777 XXX,XXX is the pyshark installation path

**Comment by cemtopkaya** [comment]
In my situation I was naming the python file with the same name of module :(

pyshark.py
```python
import pyshark

# http2-h2c.pcap is a sample PCAP file. 
capture = pyshark.FileCapture('./pcap_files/http2-h2c.pcap')
for packet in capture:
  if 'HTTP2' in str(packet.layers):
     field_names = packet.http2._all_fields
     for field_name in field_names:
        http2_stream_id = {val for key, val in field_names.items() if key == 'http2.streamid'}
        print("".join(http2_stream_id))
```
when I run the program with this `python pyshark.py` it was giving this `AttributeError: module 'pyshark' has no attribute 'FileCapture`
