### ISSUE TITLE
Lost the first packet when capture from a file

### ISSUE THREAD

**Issue by laoyang103** [KimiNewt/pyshark#99]
I use the last version, try the follow code:
   cap = pyshark.FileCapture('/tmp/mycapture.cap')
   print cap[0]
It print the second packet in the file

**Comment by JackSparrow94** [comment]
Only happened to me when trying to open with summary mode

**Comment by bjl72** [comment]
Hi,

I made a patch on my local install for the exact same issue. Will try and
recall what I did over the weekend

Brian

**Comment by laoyang103** [comment]
Hi bjl72, 

can you give me your patch when you try successfull?
send mail to me 553069938@qq.com
thank you !

**Comment by KimiNewt** [comment]
The patch may have been decreasing the SUMMARIES_BATCH_SIZE constant in the capture class, you can attempt that and report back.

**Comment by laoyang103** [comment]
I have decreasing the SUMMARIES_BATCH_SIZE equal 5 to solve this issue, will it have other effects when open large packet file?

**Comment by canelast** [comment]
Will issue be fixed in future releases?
